// Generated by scripts/fetch-wikidata-icons.mjs — do not edit by hand.
//
// The drawings are authored on Wikimedia Commons and attached to each Wikidata
// value item with `icon (P2910)`. Source URL, licence and author are kept per
// entry because the files are third-party and mostly PD or CC BY-SA.
//
// The local copies are the originals, unmodified and byte-identical to
// Commons, so they can be restyled later without re-downloading.

export type IconFormat = 'png' | 'svg'

export interface WikidataIcon {
  /** The enum key in src/data/wikidata/morphology-types.ts. */
  key: string
  /** Wikidata QID of the value. */
  qid: string
  /** English Wikidata label. */
  label: string
  /** Path relative to the repo root. */
  file: string
  format: IconFormat
  /** Commons file page — required for attribution. */
  source: string
  license: string | null
  author: string | null
}

export interface WikidataValueColor {
  prop: string
  /** The enum key in src/data/wikidata/morphology-types.ts. */
  key: string
  qid: string
  /** CSS sRGB triplets from `sRGB color hex triplet (P465)`, sorted. */
  colors: string[]
}

export interface MissingIcon {
  prop: string
  key: string
  qid: string
}

export interface ReviewIcon extends MissingIcon {
  reason: string
}

/** 6 icons for hymeniumType. */
export const hymeniumTypeIcons: WikidataIcon[] = [
  {
    key: 'Lamella',
    qid: 'Q269345',
    label: 'lamella',
    file: 'src/data/wikidata/icons/hymeniumType/Lamella.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Gills_icon.png',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'Pores',
    qid: 'Q19861549',
    label: 'pores',
    file: 'src/data/wikidata/icons/hymeniumType/Pores.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Pores_icon.png',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'Smooth',
    qid: 'Q19861550',
    label: 'smooth',
    file: 'src/data/wikidata/icons/hymeniumType/Smooth.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Smooth_icon.png',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'Ridges',
    qid: 'Q19861551',
    label: 'ridges',
    file: 'src/data/wikidata/icons/hymeniumType/Ridges.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Ridges_icon.png',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'Teeth',
    qid: 'Q19861552',
    label: 'teeth',
    file: 'src/data/wikidata/icons/hymeniumType/Teeth.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Teeth_icon.png',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'Gleba',
    qid: 'Q2034230',
    label: 'gleba',
    file: 'src/data/wikidata/icons/hymeniumType/Gleba.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Gleba_icon.png',
    license: 'CC BY 2.5',
    author: 'Steve Caruso (user The Thadman)',
  },
]

/** 12 icons for mushroomCapShape. */
export const mushroomCapShapeIcons: WikidataIcon[] = [
  {
    key: 'Campanulate',
    qid: 'Q19887953',
    label: 'campanulate mushroom cap',
    file: 'src/data/wikidata/icons/mushroomCapShape/Campanulate.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Campanulate_cap_icon.svg',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'Conical',
    qid: 'Q19887954',
    label: 'conical mushroom cap',
    file: 'src/data/wikidata/icons/mushroomCapShape/Conical.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Conical_cap_icon.svg',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'Convex',
    qid: 'Q14544535',
    label: 'convex mushroom cap',
    file: 'src/data/wikidata/icons/mushroomCapShape/Convex.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Convex_cap_icon.svg',
    license: 'CC BY-SA 3.0',
    author: 'Original:  Debivort Vector:  Lokal_Profil',
  },
  {
    key: 'Depressed',
    qid: 'Q19887955',
    label: 'depressed mushroom cap',
    file: 'src/data/wikidata/icons/mushroomCapShape/Depressed.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Depressed_cap_icon.svg',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'Flat',
    qid: 'Q19887957',
    label: 'flat mushroom cap',
    file: 'src/data/wikidata/icons/mushroomCapShape/Flat.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Flat_cap_icon.svg',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'Infundibuliform',
    qid: 'Q19887958',
    label: 'infundibuliform mushroom cap',
    file: 'src/data/wikidata/icons/mushroomCapShape/Infundibuliform.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Infundibuliform_cap_icon.svg',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'Offset',
    qid: 'Q14544541',
    label: 'offset mushroom cap',
    file: 'src/data/wikidata/icons/mushroomCapShape/Offset.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Offset_cap_icon.svg',
    license: 'CC BY-SA 3.0',
    author: 'Offset_cap_icon.png: Debivort\nderivative work: Jkwchui',
  },
  {
    key: 'Ovate',
    qid: 'Q19887961',
    label: 'ovate mushroom cap',
    file: 'src/data/wikidata/icons/mushroomCapShape/Ovate.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Ovate_cap_icon.svg',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'Umbilicate',
    qid: 'Q19887962',
    label: 'umbilicate mushroom cap',
    file: 'src/data/wikidata/icons/mushroomCapShape/Umbilicate.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Umbillicate_cap_icon.svg',
    license: 'Public domain',
    author: 'Original:  Debivort Vector:  Lokal_Profil',
  },
  {
    key: 'Umbonate',
    qid: 'Q19887964',
    label: 'umbonate mushroom cap',
    file: 'src/data/wikidata/icons/mushroomCapShape/Umbonate.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Umbonate_cap_icon.svg',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'NoMushroomCap',
    qid: 'Q19887965',
    label: 'no mushroom cap',
    file: 'src/data/wikidata/icons/mushroomCapShape/NoMushroomCap.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:No_cap_icon.svg',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'ConcaveToPlane',
    qid: 'Q23058598',
    label: 'concave to plane',
    file: 'src/data/wikidata/icons/mushroomCapShape/ConcaveToPlane.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Cappello_ondulato_disegno.png',
    license: 'Public domain',
    author: 'M.violante at Italian Wikipedia',
  },
]

/** 9 icons for hymeniumAttachment. */
export const hymeniumAttachmentIcons: WikidataIcon[] = [
  {
    key: 'Adnate',
    qid: 'Q14544569',
    label: 'adnate hymenium attachment',
    file: 'src/data/wikidata/icons/hymeniumAttachment/Adnate.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Adnate_gills_icon2.svg',
    license: 'CC BY-SA 3.0',
    author: 'User:Bryan Derksen',
  },
  {
    key: 'Adnexed',
    qid: 'Q19887923',
    label: 'adnexed hymenium attachment',
    file: 'src/data/wikidata/icons/hymeniumAttachment/Adnexed.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Adnexed_gills_icon2.svg',
    license: 'CC BY-SA 3.0',
    author: 'User:Bryan Derksen',
  },
  {
    key: 'Decurrent',
    qid: 'Q19887925',
    label: 'decurrent hymenium attachment',
    file: 'src/data/wikidata/icons/hymeniumAttachment/Decurrent.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Decurrent_gills_icon2.svg',
    license: 'CC BY-SA 3.0',
    author: 'Bryan Derksen',
  },
  {
    key: 'Emarginate',
    qid: 'Q19887926',
    label: 'emarginate hymenium attachment',
    file: 'src/data/wikidata/icons/hymeniumAttachment/Emarginate.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Emarginate_gills_icon2.svg',
    license: 'CC BY-SA 3.0',
    author: 'User:Bryan Derksen',
  },
  {
    key: 'Free',
    qid: 'Q14544563',
    label: 'free hymenium attachment',
    file: 'src/data/wikidata/icons/hymeniumAttachment/Free.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Free_gills_icon2.svg',
    license: 'CC BY-SA 3.0',
    author: 'Bryan Derksen',
  },
  {
    key: 'Seceding',
    qid: 'Q19887929',
    label: 'seceding hymenium attachment',
    file: 'src/data/wikidata/icons/hymeniumAttachment/Seceding.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Seceding_gills_icon2.svg',
    license: 'CC BY-SA 3.0',
    author: 'User:Bryan Derksen',
  },
  {
    key: 'Sinuate',
    qid: 'Q19887930',
    label: 'sinuate hymenium attachment',
    file: 'src/data/wikidata/icons/hymeniumAttachment/Sinuate.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Sinuate_gills_icon2.svg',
    license: 'CC BY-SA 3.0',
    author: 'User:Bryan Derksen',
  },
  {
    key: 'Subdecurrent',
    qid: 'Q19887931',
    label: 'subdecurrent hymenium attachment',
    file: 'src/data/wikidata/icons/hymeniumAttachment/Subdecurrent.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Subdecurrent_gills_icon2.svg',
    license: 'CC BY-SA 3.0',
    author: 'User:Bryan Derksen',
  },
  {
    key: 'NoHymeniumAttachment',
    qid: 'Q19887932',
    label: 'no hymenium attachment',
    file: 'src/data/wikidata/icons/hymeniumAttachment/NoHymeniumAttachment.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:No_gills_icon.svg',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
]

/** 6 icons for stipeCharacter. */
export const stipeCharacterIcons: WikidataIcon[] = [
  {
    key: 'Bare',
    qid: 'Q14544581',
    label: 'bare stipe',
    file: 'src/data/wikidata/icons/stipeCharacter/Bare.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Bare_stipe_icon.svg',
    license: 'CC BY-SA 3.0',
    author: 'User:Natr',
  },
  {
    key: 'Ring',
    qid: 'Q14544582',
    label: 'ring stipe',
    file: 'src/data/wikidata/icons/stipeCharacter/Ring.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Ring_stipe_icon.png',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'Volva',
    qid: 'Q19887985',
    label: 'volva stipe',
    file: 'src/data/wikidata/icons/stipeCharacter/Volva.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Volva_stipe_icon.png',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'RingAndVolva',
    qid: 'Q19887987',
    label: 'ring and volva stipe',
    file: 'src/data/wikidata/icons/stipeCharacter/RingAndVolva.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Ring_and_volva_stipe_icon.svg',
    license: 'CC BY-SA 3.0',
    author: 'Natr',
  },
  {
    key: 'Cortina',
    qid: 'Q19887988',
    label: 'cortina stipe',
    file: 'src/data/wikidata/icons/stipeCharacter/Cortina.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Cortina_stipe_icon.png',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'Reticulate',
    qid: 'Q131915205',
    label: 'reticulate',
    file: 'src/data/wikidata/icons/stipeCharacter/Reticulate.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Stiel_Netz.svg',
    license: 'CC BY-SA 3.0',
    author: 'Accu',
  },
]

/** 9 icons for sporePrintColor. */
export const sporePrintColorIcons: WikidataIcon[] = [
  {
    key: 'BlackishBrown',
    qid: 'Q19888339',
    label: 'blackish-brown',
    file: 'src/data/wikidata/icons/sporePrintColor/BlackishBrown.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Blackish-brown_spore_print_icon.png',
    license: 'CC BY-SA 3.0',
    author: null,
  },
  {
    key: 'Buff',
    qid: 'Q2085487',
    label: 'buff',
    file: 'src/data/wikidata/icons/sporePrintColor/Buff.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Buff_spore_print_icon.png',
    license: 'CC BY-SA 3.0',
    author: null,
  },
  {
    key: 'Olive',
    qid: 'Q864152',
    label: 'olive',
    file: 'src/data/wikidata/icons/sporePrintColor/Olive.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Olive_spore_print_icon.png',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'OliveBrown',
    qid: 'Q19888352',
    label: 'olive brown',
    file: 'src/data/wikidata/icons/sporePrintColor/OliveBrown.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Olive-brown_spore_print_icon.png',
    license: 'CC BY-SA 3.0',
    author: 'Debivort (talk)',
  },
  {
    key: 'Pink',
    qid: 'Q429220',
    label: 'pink',
    file: 'src/data/wikidata/icons/sporePrintColor/Pink.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Pink_spore_print_icon.png',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
  {
    key: 'PinkishBrown',
    qid: 'Q19888366',
    label: 'pinkish-brown',
    file: 'src/data/wikidata/icons/sporePrintColor/PinkishBrown.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Pinkish-brown_spore_print_icon.png',
    license: 'CC BY-SA 3.0',
    author: null,
  },
  {
    key: 'Purple',
    qid: 'Q3257809',
    label: 'purple',
    file: 'src/data/wikidata/icons/sporePrintColor/Purple.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Purple_spore_print_icon.png',
    license: 'CC BY-SA 3.0',
    author: null,
  },
  {
    key: 'PurpleBlack',
    qid: 'Q19888373',
    label: 'purple-black',
    file: 'src/data/wikidata/icons/sporePrintColor/PurpleBlack.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Purple-black_spore_print_icon.png',
    license: 'CC BY-SA 3.0',
    author: 'Original uploader was Debivort at en.wikipedia',
  },
  {
    key: 'Yellow',
    qid: 'Q943',
    label: 'yellow',
    file: 'src/data/wikidata/icons/sporePrintColor/Yellow.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Yellow_spore_print_icon.png',
    license: 'CC BY-SA 3.0',
    author: 'Debivort on EN wiki',
  },
]

/** 3 icons for mushroomEcologicalType. */
export const mushroomEcologicalTypeIcons: WikidataIcon[] = [
  {
    key: 'Mycorrhiza',
    qid: 'Q99974',
    label: 'mycorrhiza',
    file: 'src/data/wikidata/icons/mushroomEcologicalType/Mycorrhiza.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Mycorrhizal_fungus.svg',
    license: 'CC0',
    author: 'Natr',
  },
  {
    key: 'Saprobiont',
    qid: 'Q114750',
    label: 'saprobiont',
    file: 'src/data/wikidata/icons/mushroomEcologicalType/Saprobiont.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Saprotrophic_fungus.svg',
    license: 'CC0',
    author: 'Natr',
  },
  {
    key: 'Parasitism',
    qid: 'Q186517',
    label: 'parasitism',
    file: 'src/data/wikidata/icons/mushroomEcologicalType/Parasitism.svg',
    format: 'svg',
    source: 'https://commons.wikimedia.org/wiki/File:Parasitic_fungus.svg',
    license: 'CC0',
    author: 'Natr',
  },
]

/** 7 icons for edibility. */
export const edibilityIcons: WikidataIcon[] = [
  {
    key: 'ChoiceMushroom',
    qid: 'Q19888517',
    label: 'choice mushroom',
    file: 'src/data/wikidata/icons/edibility/ChoiceMushroom.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Mycomorphbox_Choice.png',
    license: 'CC BY-SA 4.0',
    author: 'Sven Manguard',
  },
  {
    key: 'InedibleMushroom',
    qid: 'Q4317894',
    label: 'inedible mushroom',
    file: 'src/data/wikidata/icons/edibility/InedibleMushroom.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Mycomorphbox_Inedible.png',
    license: 'CC BY-SA 4.0',
    author: 'Sven Manguard',
  },
  {
    key: 'CautionMushroom',
    qid: 'Q19888537',
    label: 'caution mushroom',
    file: 'src/data/wikidata/icons/edibility/CautionMushroom.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Mycomorphbox_Caution.png',
    license: 'CC BY-SA 4.0',
    author: 'Sven Manguard',
  },
  {
    key: 'PsychoactiveMushroom',
    qid: 'Q1169875',
    label: 'psychoactive mushroom',
    file: 'src/data/wikidata/icons/edibility/PsychoactiveMushroom.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Mycomorphbox_Psychoactive.png',
    license: 'CC BY-SA 4.0',
    author: 'Sven Manguard (talk)',
  },
  {
    key: 'AllergenicMushroom',
    qid: 'Q19888579',
    label: 'allergenic mushroom',
    file: 'src/data/wikidata/icons/edibility/AllergenicMushroom.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Mycomorphbox_Caution.png',
    license: 'CC BY-SA 4.0',
    author: 'Sven Manguard',
  },
  {
    key: 'DeadlyMushroom',
    qid: 'Q19888591',
    label: 'deadly mushroom',
    file: 'src/data/wikidata/icons/edibility/DeadlyMushroom.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Mycomorphbox_Deadly.png',
    license: 'CC BY-SA 4.0',
    author: 'Sven Manguard',
  },
  {
    key: 'PoisonousMushroom',
    qid: 'Q359511',
    label: 'poisonous mushroom',
    file: 'src/data/wikidata/icons/edibility/PoisonousMushroom.png',
    format: 'png',
    source: 'https://commons.wikimedia.org/wiki/File:Mycomorphbox_Poison.png',
    license: 'CC BY-SA 4.0',
    author: 'Sven Manguard',
  },
]

/** Every downloaded icon, keyed by QID. */
export const iconsByQid: Record<string, WikidataIcon> = {
  Q269345: hymeniumTypeIcons[0],
  Q19861549: hymeniumTypeIcons[1],
  Q19861550: hymeniumTypeIcons[2],
  Q19861551: hymeniumTypeIcons[3],
  Q19861552: hymeniumTypeIcons[4],
  Q2034230: hymeniumTypeIcons[5],
  Q19887953: mushroomCapShapeIcons[0],
  Q19887954: mushroomCapShapeIcons[1],
  Q14544535: mushroomCapShapeIcons[2],
  Q19887955: mushroomCapShapeIcons[3],
  Q19887957: mushroomCapShapeIcons[4],
  Q19887958: mushroomCapShapeIcons[5],
  Q14544541: mushroomCapShapeIcons[6],
  Q19887961: mushroomCapShapeIcons[7],
  Q19887962: mushroomCapShapeIcons[8],
  Q19887964: mushroomCapShapeIcons[9],
  Q19887965: mushroomCapShapeIcons[10],
  Q23058598: mushroomCapShapeIcons[11],
  Q14544569: hymeniumAttachmentIcons[0],
  Q19887923: hymeniumAttachmentIcons[1],
  Q19887925: hymeniumAttachmentIcons[2],
  Q19887926: hymeniumAttachmentIcons[3],
  Q14544563: hymeniumAttachmentIcons[4],
  Q19887929: hymeniumAttachmentIcons[5],
  Q19887930: hymeniumAttachmentIcons[6],
  Q19887931: hymeniumAttachmentIcons[7],
  Q19887932: hymeniumAttachmentIcons[8],
  Q14544581: stipeCharacterIcons[0],
  Q14544582: stipeCharacterIcons[1],
  Q19887985: stipeCharacterIcons[2],
  Q19887987: stipeCharacterIcons[3],
  Q19887988: stipeCharacterIcons[4],
  Q131915205: stipeCharacterIcons[5],
  Q19888339: sporePrintColorIcons[0],
  Q2085487: sporePrintColorIcons[1],
  Q864152: sporePrintColorIcons[2],
  Q19888352: sporePrintColorIcons[3],
  Q429220: sporePrintColorIcons[4],
  Q19888366: sporePrintColorIcons[5],
  Q3257809: sporePrintColorIcons[6],
  Q19888373: sporePrintColorIcons[7],
  Q943: sporePrintColorIcons[8],
  Q99974: mushroomEcologicalTypeIcons[0],
  Q114750: mushroomEcologicalTypeIcons[1],
  Q186517: mushroomEcologicalTypeIcons[2],
  Q19888517: edibilityIcons[0],
  Q4317894: edibilityIcons[1],
  Q19888537: edibilityIcons[2],
  Q1169875: edibilityIcons[3],
  Q19888579: edibilityIcons[4],
  Q19888591: edibilityIcons[5],
  Q359511: edibilityIcons[6],
}

/**
 * Values carrying an `sRGB color hex triplet (P465)`, icon or not. A value may
 * have more than one triplet (salmon has two, purple-brown five), so these are
 * all of Wikidata's answers, sorted, not a single canonical colour.
 */
export const valueColors: WikidataValueColor[] = [
  { prop: 'sporePrintColor', key: 'Black', qid: 'Q23445', colors: ['#000000'] },
  { prop: 'sporePrintColor', key: 'Brown', qid: 'Q47071', colors: ['#964B00'] },
  { prop: 'sporePrintColor', key: 'Buff', qid: 'Q2085487', colors: ['#E0AB76', '#F0DC82'] },
  { prop: 'sporePrintColor', key: 'Cream', qid: 'Q2730433', colors: ['#FFFDD0'] },
  { prop: 'sporePrintColor', key: 'Green', qid: 'Q3133', colors: ['#00FF00'] },
  { prop: 'sporePrintColor', key: 'Ochre', qid: 'Q194191', colors: ['#CC7722'] },
  { prop: 'sporePrintColor', key: 'Olive', qid: 'Q864152', colors: ['#808000'] },
  { prop: 'sporePrintColor', key: 'OliveBrown', qid: 'Q19888352', colors: ['#645403'] },
  { prop: 'sporePrintColor', key: 'Pink', qid: 'Q429220', colors: ['#FFC0DB'] },
  { prop: 'sporePrintColor', key: 'Purple', qid: 'Q3257809', colors: ['#800080'] },
  {
    prop: 'sporePrintColor',
    key: 'PurpleBrown',
    qid: 'Q19888381',
    colors: ['#67393F', '#673A3F', '#6A4540', '#6B3B44', '#6D4146'],
  },
  { prop: 'sporePrintColor', key: 'Salmon', qid: 'Q2015138', colors: ['#FA8072', '#FF91A4'] },
  { prop: 'sporePrintColor', key: 'Tan', qid: 'Q1670336', colors: ['#D2B48C'] },
  { prop: 'sporePrintColor', key: 'White', qid: 'Q23444', colors: ['#FFFFFF'] },
  { prop: 'sporePrintColor', key: 'Yellow', qid: 'Q943', colors: ['#FFFF00'] },
  {
    prop: 'sporePrintColor',
    key: 'YellowOrange',
    qid: 'Q16645086',
    colors: ['#FFAA33', '#FFAE42'],
  },
  { prop: 'sporePrintColor', key: 'Bordeaux', qid: 'Q10859033', colors: ['#800032'] },
  { prop: 'sporePrintColor', key: 'RedOrange', qid: 'Q62058583', colors: ['#FF5349'] },
]

/** Every sRGB triplet, keyed by QID. */
export const colorsByQid: Record<string, string[]> = {
  Q23445: ['#000000'],
  Q47071: ['#964B00'],
  Q2085487: ['#E0AB76', '#F0DC82'],
  Q2730433: ['#FFFDD0'],
  Q3133: ['#00FF00'],
  Q194191: ['#CC7722'],
  Q864152: ['#808000'],
  Q19888352: ['#645403'],
  Q429220: ['#FFC0DB'],
  Q3257809: ['#800080'],
  Q19888381: ['#67393F', '#673A3F', '#6A4540', '#6B3B44', '#6D4146'],
  Q2015138: ['#FA8072', '#FF91A4'],
  Q1670336: ['#D2B48C'],
  Q23444: ['#FFFFFF'],
  Q943: ['#FFFF00'],
  Q16645086: ['#FFAA33', '#FFAE42'],
  Q10859033: ['#800032'],
  Q62058583: ['#FF5349'],
}

/** Values Wikimedia Commons has no icon for. */
export const missingIcons: MissingIcon[] = [
  { prop: 'sporePrintColor', key: 'Black', qid: 'Q23445' },
  { prop: 'sporePrintColor', key: 'Brown', qid: 'Q47071' },
  { prop: 'sporePrintColor', key: 'Cream', qid: 'Q2730433' },
  { prop: 'sporePrintColor', key: 'Green', qid: 'Q3133' },
  { prop: 'sporePrintColor', key: 'Ochre', qid: 'Q194191' },
  { prop: 'sporePrintColor', key: 'PurpleBrown', qid: 'Q19888381' },
  { prop: 'sporePrintColor', key: 'Salmon', qid: 'Q2015138' },
  { prop: 'sporePrintColor', key: 'Tan', qid: 'Q1670336' },
  { prop: 'sporePrintColor', key: 'White', qid: 'Q23444' },
  { prop: 'sporePrintColor', key: 'YellowOrange', qid: 'Q16645086' },
  { prop: 'sporePrintColor', key: 'YellowBrown', qid: 'Q19888422' },
  { prop: 'sporePrintColor', key: 'Bordeaux', qid: 'Q10859033' },
  { prop: 'sporePrintColor', key: 'RedOrange', qid: 'Q62058583' },
  { prop: 'mushroomEcologicalType', key: 'NematophagousFungus', qid: 'Q357006' },
  { prop: 'edibility', key: 'EdibleMushroom', qid: 'Q654236' },
  { prop: 'edibility', key: 'EdibleWhenCooked', qid: 'Q62102033' },
  { prop: 'edibility', key: 'MedicinalMushrooms', qid: 'Q1686195' },
]

/** Values whose Wikidata icon is wrong, so nothing was downloaded. */
export const iconsToReview: ReviewIcon[] = [
  {
    prop: 'mushroomCapShape',
    key: 'SemiSpherical',
    qid: 'Q62023127',
    reason: "no icon; P18 is another value's icon (convex cap)",
  },
]
