// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
export type * from './types'
import type { WikidataSpeciesData } from './types'

import { tolypocladiumOphioglossoidesQ104084181 } from './Q104084181'
import { inocybeSindoniaQ10431265 } from './Q10431265'
import { coprinopsisPseudoniveaQ10459215 } from './Q10459215'
import { diatrypeDisciformisQ10474236 } from './Q10474236'
import { mycenaViridimarginataQ10510028 } from './Q10510028'
import { cortinariusLargusQ10570865 } from './Q10570865'
import { russulaLangeiQ10658025 } from './Q10658025'
import { cudoniellaAcicularisQ10682294 } from './Q10682294'
import { tolypocladiumLongisegmentatumQ108430550 } from './Q108430550'
import { podofomesMollisQ114852018 } from './Q114852018'
import { suillusBovinusQ1165762 } from './Q1165762'
import { mycenaEpipterygiaQ1183020 } from './Q1183020'
import { amanitaMuscariaQ131227 } from './Q131227'
import { collybiopsisVaillantiiQ136395649 } from './Q136395649'
import { hydnumRepandumQ13684 } from './Q13684'
import { clavulinaCoralloidesQ138027 } from './Q138027'
import { clavulinopsisHelvolaQ138029 } from './Q138029'
import { craterellusLutescensQ1478429 } from './Q1478429'
import { gomphusClavatusQ1478471 } from './Q1478471'
import { ramariaAureaQ1479710 } from './Q1479710'
import { caloceraCorneaQ175548 } from './Q175548'
import { clathrusArcheriQ1757951 } from './Q1757951'
import { rickenellaFibulaQ1770667 } from './Q1770667'
import { thelephoraTerrestrisQ1816880 } from './Q1816880'
import { amanitaPhalloidesQ188643 } from './Q188643'
import { cantharellusCibariusQ188749 } from './Q188749'
import { hydnellumPeckiiQ1908340 } from './Q1908340'
import { panellusMitisQ1934540 } from './Q1934540'
import { boletusEdulisQ19740 } from './Q19740'
import { pseudohydnumGelatinosumQ206711 } from './Q206711'
import { cordycepsMilitarisQ2118699 } from './Q2118699'
import { dacrymycesChrysopermusQ2152361 } from './Q2152361'
import { hygrocybeAcutoconicaQ2255842 } from './Q2255842'
import { macrolepiotaProceraQ243381 } from './Q243381'
import { rubroboletusSatanasQ26203731 } from './Q26203731'
import { butyriboletusAppendiculatusQ26203735 } from './Q26203735'
import { rubroboletusRhodoxanthusQ26203742 } from './Q26203742'
import { sarcondonImbricatusQ262105 } from './Q262105'
import { guepiniaHelvelloidesQ26678323 } from './Q26678323'
import { coprinusComatusQ275125 } from './Q275125'
import { laccariaAmethystinaQ28492278 } from './Q28492278'
import { coprinopsisNiveaQ28492325 } from './Q28492325'
import { caloboletusCalopusQ29784429 } from './Q29784429'
import { lepiotaClypeolariaQ300967 } from './Q300967'
import { auriculariaAuriculaJudaeQ321342 } from './Q321342'
import { albatrellusOvinusQ331465 } from './Q331465'
import { craterellusTubaeformisQ371126 } from './Q371126'
import { otideaAlutaceaQ3913798 } from './Q3913798'
import { hygrocybeCantharellusQ3915439 } from './Q3915439'
import { amanitaPantherinaQ45547 } from './Q45547'
import { armillariaMelleaQ473745 } from './Q473745'
import { lactariusDeterrimusQ498221 } from './Q498221'
import { mucidulaMucidaQ54371399 } from './Q54371399'
import { lycoperdonPerlatumQ545130 } from './Q545130'
import { tricholomaSulphureumQ583388 } from './Q583388'
import { caloboletusRadicansQ64785775 } from './Q64785775'
import { hericiumFlagellumQ67086840 } from './Q67086840'
import { suillellusLuridusQ752494 } from './Q752494'
import { infundibulicybeGibbaQ765631 } from './Q765631'
import { laetiporusSulphureusQ772098 } from './Q772098'
import { ganodermaApplanatumQ774576 } from './Q774576'
import { gomphidiusGlutinosusQ790626 } from './Q790626'
import { russulaDelicaQ843177 } from './Q843177'
import { russulaParazureaQ882885 } from './Q882885'
import { schizophyllumCommuneQ941733 } from './Q941733'

export interface SpeciesSnapshotMeta {
  slug: string
  scientificName: string
}

/** Every fetched species, keyed by its Wikidata QID.
 *
 *  Join it against the content collection through
 *  `speciesEntry.data.wikidataId`; that field is optional in the schema, so
 *  a lookup can legitimately come back undefined. */
export const speciesWikidata: Record<string, WikidataSpeciesData> = {
  Q104084181: tolypocladiumOphioglossoidesQ104084181,
  Q10431265: inocybeSindoniaQ10431265,
  Q10459215: coprinopsisPseudoniveaQ10459215,
  Q10474236: diatrypeDisciformisQ10474236,
  Q10510028: mycenaViridimarginataQ10510028,
  Q10570865: cortinariusLargusQ10570865,
  Q10658025: russulaLangeiQ10658025,
  Q10682294: cudoniellaAcicularisQ10682294,
  Q108430550: tolypocladiumLongisegmentatumQ108430550,
  Q114852018: podofomesMollisQ114852018,
  Q1165762: suillusBovinusQ1165762,
  Q1183020: mycenaEpipterygiaQ1183020,
  Q131227: amanitaMuscariaQ131227,
  Q136395649: collybiopsisVaillantiiQ136395649,
  Q13684: hydnumRepandumQ13684,
  Q138027: clavulinaCoralloidesQ138027,
  Q138029: clavulinopsisHelvolaQ138029,
  Q1478429: craterellusLutescensQ1478429,
  Q1478471: gomphusClavatusQ1478471,
  Q1479710: ramariaAureaQ1479710,
  Q175548: caloceraCorneaQ175548,
  Q1757951: clathrusArcheriQ1757951,
  Q1770667: rickenellaFibulaQ1770667,
  Q1816880: thelephoraTerrestrisQ1816880,
  Q188643: amanitaPhalloidesQ188643,
  Q188749: cantharellusCibariusQ188749,
  Q1908340: hydnellumPeckiiQ1908340,
  Q1934540: panellusMitisQ1934540,
  Q19740: boletusEdulisQ19740,
  Q206711: pseudohydnumGelatinosumQ206711,
  Q2118699: cordycepsMilitarisQ2118699,
  Q2152361: dacrymycesChrysopermusQ2152361,
  Q2255842: hygrocybeAcutoconicaQ2255842,
  Q243381: macrolepiotaProceraQ243381,
  Q26203731: rubroboletusSatanasQ26203731,
  Q26203735: butyriboletusAppendiculatusQ26203735,
  Q26203742: rubroboletusRhodoxanthusQ26203742,
  Q262105: sarcondonImbricatusQ262105,
  Q26678323: guepiniaHelvelloidesQ26678323,
  Q275125: coprinusComatusQ275125,
  Q28492278: laccariaAmethystinaQ28492278,
  Q28492325: coprinopsisNiveaQ28492325,
  Q29784429: caloboletusCalopusQ29784429,
  Q300967: lepiotaClypeolariaQ300967,
  Q321342: auriculariaAuriculaJudaeQ321342,
  Q331465: albatrellusOvinusQ331465,
  Q371126: craterellusTubaeformisQ371126,
  Q3913798: otideaAlutaceaQ3913798,
  Q3915439: hygrocybeCantharellusQ3915439,
  Q45547: amanitaPantherinaQ45547,
  Q473745: armillariaMelleaQ473745,
  Q498221: lactariusDeterrimusQ498221,
  Q54371399: mucidulaMucidaQ54371399,
  Q545130: lycoperdonPerlatumQ545130,
  Q583388: tricholomaSulphureumQ583388,
  Q64785775: caloboletusRadicansQ64785775,
  Q67086840: hericiumFlagellumQ67086840,
  Q752494: suillellusLuridusQ752494,
  Q765631: infundibulicybeGibbaQ765631,
  Q772098: laetiporusSulphureusQ772098,
  Q774576: ganodermaApplanatumQ774576,
  Q790626: gomphidiusGlutinosusQ790626,
  Q843177: russulaDelicaQ843177,
  Q882885: russulaParazureaQ882885,
  Q941733: schizophyllumCommuneQ941733,
}

export const speciesWikidataMeta: Record<string, SpeciesSnapshotMeta> = {
  Q104084181: {
    slug: 'tolypocladium-ophioglossoides',
    scientificName: 'Tolypocladium ophioglossoides',
  },
  Q10431265: { slug: 'inocybe-sindonia', scientificName: 'Inocybe sindonia' },
  Q10459215: { slug: 'coprinopsis-pseudonivea', scientificName: 'Coprinopsis pseudonivea' },
  Q10474236: { slug: 'diatrype-disciformis', scientificName: 'Diatrype disciformis' },
  Q10510028: { slug: 'mycena-viridimarginata', scientificName: 'Mycena viridimarginata' },
  Q10570865: { slug: 'cortinarius-largus', scientificName: 'Cortinarius largus' },
  Q10658025: { slug: 'russula-langei', scientificName: 'Russula langei' },
  Q10682294: { slug: 'cudoniella-acicularis', scientificName: 'Cudoniella acicularis' },
  Q108430550: {
    slug: 'tolypocladium-longisegmentatum',
    scientificName: 'Tolypocladium longisegmentatum',
  },
  Q114852018: { slug: 'podofomes-mollis', scientificName: 'Podofomes mollis' },
  Q1165762: { slug: 'suillus-bovinus', scientificName: 'Suillus bovinus' },
  Q1183020: { slug: 'mycena-epipterygia', scientificName: 'Mycena epipterygia' },
  Q131227: { slug: 'amanita-muscaria', scientificName: 'Amanita muscaria' },
  Q136395649: { slug: 'collybiopsis-vaillantii', scientificName: 'Collybiopsis vaillantii' },
  Q13684: { slug: 'hydnum-repandum', scientificName: 'Hydnum repandum' },
  Q138027: { slug: 'clavulina-coralloides', scientificName: 'Clavulina coralloides' },
  Q138029: { slug: 'clavulinopsis-helvola', scientificName: 'Clavulinopsis helvola' },
  Q1478429: { slug: 'craterellus-lutescens', scientificName: 'Craterellus lutescens' },
  Q1478471: { slug: 'gomphus-clavatus', scientificName: 'Gomphus clavatus' },
  Q1479710: { slug: 'ramaria-aurea', scientificName: 'Ramaria aurea' },
  Q175548: { slug: 'calocera-cornea', scientificName: 'Calocera cornea' },
  Q1757951: { slug: 'clathrus-archeri', scientificName: 'Clathrus archeri' },
  Q1770667: { slug: 'rickenella-fibula', scientificName: 'Rickenella fibula' },
  Q1816880: { slug: 'thelephora-terrestris', scientificName: 'Thelephora terrestris' },
  Q188643: { slug: 'amanita-phalloides', scientificName: 'Amanita phalloides' },
  Q188749: { slug: 'cantharellus-cibarius', scientificName: 'Cantharellus cibarius' },
  Q1908340: { slug: 'hydnellum-peckii', scientificName: 'Hydnellum peckii' },
  Q1934540: { slug: 'panellus-mitis', scientificName: 'Panellus mitis' },
  Q19740: { slug: 'boletus-edulis', scientificName: 'Boletus edulis' },
  Q206711: { slug: 'pseudohydnum-gelatinosum', scientificName: 'Pseudohydnum gelatinosum' },
  Q2118699: { slug: 'cordyceps-militaris', scientificName: 'Cordyceps militaris' },
  Q2152361: { slug: 'dacrymyces-chrysopermus', scientificName: 'Dacrymyces chrysospermus' },
  Q2255842: { slug: 'hygrocybe-acutoconica', scientificName: 'Hygrocybe acutoconica' },
  Q243381: { slug: 'macrolepiota-procera', scientificName: 'Macrolepiota procera' },
  Q26203731: { slug: 'rubroboletus-satanas', scientificName: 'Rubroboletus satanas' },
  Q26203735: {
    slug: 'butyriboletus-appendiculatus',
    scientificName: 'Butyriboletus appendiculatus',
  },
  Q26203742: { slug: 'rubroboletus-rhodoxanthus', scientificName: 'Rubroboletus rhodoxanthus' },
  Q262105: { slug: 'sarcondon-imbricatus', scientificName: 'Sarcodon imbricatus' },
  Q26678323: { slug: 'guepinia-helvelloides', scientificName: 'Guepinia helvelloides' },
  Q275125: { slug: 'coprinus-comatus', scientificName: 'Coprinus comatus' },
  Q28492278: { slug: 'laccaria-amethystina', scientificName: 'Laccaria amethystina' },
  Q28492325: { slug: 'coprinopsis-nivea', scientificName: 'Coprinopsis nivea' },
  Q29784429: { slug: 'caloboletus-calopus', scientificName: 'Caloboletus calopus' },
  Q300967: { slug: 'lepiota-clypeolaria', scientificName: 'Lepiota clypeolaria' },
  Q321342: { slug: 'auricularia-auricula-judae', scientificName: 'Auricularia auricula-judae' },
  Q331465: { slug: 'albatrellus-ovinus', scientificName: 'Albatrellus ovinus' },
  Q371126: { slug: 'craterellus-tubaeformis', scientificName: 'Craterellus tubaeformis' },
  Q3913798: { slug: 'otidea-alutacea', scientificName: 'Otidea alutacea' },
  Q3915439: { slug: 'hygrocybe-cantharellus', scientificName: 'Hygrocybe cantharellus' },
  Q45547: { slug: 'amanita-pantherina', scientificName: 'Amanita pantherina' },
  Q473745: { slug: 'armillaria-mellea', scientificName: 'Armillaria mellea' },
  Q498221: { slug: 'lactarius-deterrimus', scientificName: 'Lactarius deterrimus' },
  Q54371399: { slug: 'mucidula-mucida', scientificName: 'Mucidula mucida' },
  Q545130: { slug: 'lycoperdon-perlatum', scientificName: 'Lycoperdon perlatum' },
  Q583388: { slug: 'tricholoma-sulphureum', scientificName: 'Tricholoma sulphureum' },
  Q64785775: { slug: 'caloboletus-radicans', scientificName: 'Caloboletus radicans' },
  Q67086840: { slug: 'hericium-flagellum', scientificName: 'Hericium flagellum' },
  Q752494: { slug: 'suillellus-luridus', scientificName: 'Suillellus luridus' },
  Q765631: { slug: 'infundibulicybe-gibba', scientificName: 'Infundibulicybe gibba' },
  Q772098: { slug: 'laetiporus-sulphureus', scientificName: 'Laetiporus sulphureus' },
  Q774576: { slug: 'ganoderma-applanatum', scientificName: 'Ganoderma applanatum' },
  Q790626: { slug: 'gomphidius-glutinosus', scientificName: 'Gomphidius glutinosus' },
  Q843177: { slug: 'russula-delica', scientificName: 'Russula delica' },
  Q882885: { slug: 'russula-parazurea', scientificName: 'Russula parazurea' },
  Q941733: { slug: 'schizophyllum-commune', scientificName: 'Schizophyllum commune' },
}

/** The QIDs that have a snapshot, for asserting coverage against the collection. */
export const speciesWikidataQids: string[] = Object.keys(speciesWikidata)
