// Wikidata data for Tolypocladium ophioglossoides (Q104084181)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const tolypocladiumOphioglossoidesQ104084181: WikidataSpeciesData = {
  slug: 'tolypocladium-ophioglossoides',
  wikidataId: 'Q104084181',
  taxonomy: {
    taxonName: 'Tolypocladium ophioglossoides',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q7814691', labels: { en: 'Tolypocladium', de: 'Tolypocladium' } },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [{ pid: 'P566', qid: 'Q131413832', labels: { en: 'Sphaeria ophioglossoides' } }],
    authorCitation: '(J.F. Gmel.) C.A. Quandt, Kepler & Spatafora',
    shortName: 'T. ophioglossoides',
  },
  names: {
    labels: { en: 'Tolypocladium ophioglossoides', de: 'Tolypocladium ophioglossoides' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Tolypocladium' },
    aliases: { en: ['Elaphocordyceps ophioglossoides'] },
    commonNames: [],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: ['Elaphocordyceps ophioglossoides 01.jpg'],
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '808859',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=808859',
    },
    { pid: 'P846', source: 'GBIF', value: '7646591', url: 'https://www.gbif.org/species/7646591' },
    { pid: 'P962', source: 'MycoBank', value: '808859', url: 'https://www.mycobank.org/MB/808859' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '499797',
      url: 'https://inaturalist.org/taxa/499797',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '1163406',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/1163406',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '57BVD',
      url: 'https://www.catalogueoflife.org/data/taxon/57BVD',
    },
  ],
}

export default tolypocladiumOphioglossoidesQ104084181
