// Wikidata data for Diatrype disciformis (Q10474236)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const diatrypeDisciformisQ10474236: WikidataSpeciesData = {
  slug: 'diatrype-disciformis',
  wikidataId: 'Q10474236',
  taxonomy: {
    taxonName: 'Diatrype disciformis',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q3767761', label: 'Diatrype' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q59503472', label: 'Sphaeria disciformis' }],
    shortName: 'D. disciformis',
  },
  names: {
    labels: { en: 'Diatrype disciformis', de: 'Buchen-Eckenscheibchen' },
    descriptions: {
      en: 'species of fungus',
      de: 'Pilzart aus der Familie der Eckenscheibchenverwandten',
    },
    aliases: { de: ['Diatrype disciformis'] },
    commonNames: [
      { lang: 'cy', value: 'botwm ffawydd' },
      { lang: 'nl', value: 'Hoekig schorsschijfje' },
      { lang: 'cs', value: 'korovitka terčovitá' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: ['2012-03-01 Diatrype disciformis (Hoffm.) Fr 201716.jpg'],
    commonsCategory: 'Diatrype disciformis',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '233766' },
    { pid: 'P846', source: 'GBIF', value: '2575263' },
    { pid: 'P962', source: 'MycoBank', value: '233766' },
    { pid: 'P3151', source: 'iNaturalist', value: '382151' },
    { pid: 'P838', source: 'BioLib', value: '59774' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '188570' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '42366' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '6CR7W' },
  ],
}

export default diatrypeDisciformisQ10474236
