// Wikidata data for Inocybe sindonia (Q10431265)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const inocybeSindoniaQ10431265: WikidataSpeciesData = {
  slug: 'inocybe-sindonia',
  wikidataId: 'Q10431265',
  taxonomy: {
    taxonName: 'Inocybe sindonia',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q784343', label: 'Inocybe' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q59529404', label: 'Agaricus sindonius' }],
    shortName: 'I. sindonia',
  },
  names: {
    labels: { en: 'Inocybe sindonia', de: 'Inocybe sindonia' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Risspilze (Inocybe)' },
    commonNames: [
      { lang: 'nl', value: 'Blonde vezelkop' },
      { lang: 'cs', value: 'vláknice sindonská' },
      { lang: 'fi', value: 'kittirisakas' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: ['Inocybe.sindonia.-.lindsey.jpg'],
    commonsCategory: 'Inocybe sindonia',
    commonsGallery: 'Inocybe sindonia',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '235443' },
    { pid: 'P846', source: 'GBIF', value: '2527869' },
    { pid: 'P962', source: 'MycoBank', value: '235443' },
    { pid: 'P3151', source: 'iNaturalist', value: '416745' },
    { pid: 'P838', source: 'BioLib', value: '126301' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '188634' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '166043' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '3PRM3' },
  ],
}

export default inocybeSindoniaQ10431265
