// Wikidata data for Cortinarius largus (Q10570865)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const cortinariusLargusQ10570865: WikidataSpeciesData = {
  slug: 'cortinarius-largus',
  wikidataId: 'Q10570865',
  taxonomy: {
    taxonName: 'Cortinarius largus',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q306495', labels: { en: 'Cortinarius', de: 'Schleierlinge' } },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    authorCitation: 'Fr. (1838)',
    shortName: 'C. largus',
  },
  names: {
    labels: { en: 'Cortinarius largus', de: 'Cortinarius largus' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Schleierlinge (Cortinarius)' },
    commonNames: [{ lang: 'cs', value: 'pavučinec masitý' }],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: ['Cortinarius largus (37444855132).jpg'],
    commonsCategory: 'Cortinarius largus',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '224983',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=224983',
    },
    { pid: 'P846', source: 'GBIF', value: '2529520', url: 'https://www.gbif.org/species/2529520' },
    { pid: 'P962', source: 'MycoBank', value: '224983', url: 'https://www.mycobank.org/MB/224983' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '381926',
      url: 'https://inaturalist.org/taxa/381926',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '343480',
      url: 'https://www.biolib.cz/cz/taxon/id343480',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '188363',
      url: 'https://eol.org/pages/188363',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: 'YLB6',
      url: 'https://www.catalogueoflife.org/data/taxon/YLB6',
    },
  ],
}

export default cortinariusLargusQ10570865
