// Wikidata data for Cortinarius largus (Q10570865)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const cortinariusLargusQ10570865: WikidataSpeciesData = {
  slug: 'cortinarius-largus',
  wikidataId: 'Q10570865',
  taxonomy: {
    taxonName: 'Cortinarius largus',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q306495', label: 'Cortinarius' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    authorCitation: 'Fr. (1838)',
    shortName: 'C. largus',
  },
  names: {
    labels: { en: 'Cortinarius largus', de: 'Cortinarius largus' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Schleierlinge (Cortinarius)' },
    commonNames: [{ lang: 'cs', value: 'pavučinec masitý' }],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: ['Cortinarius largus (37444855132).jpg'],
    commonsCategory: 'Cortinarius largus',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '224983' },
    { pid: 'P846', source: 'GBIF', value: '2529520' },
    { pid: 'P962', source: 'MycoBank', value: '224983' },
    { pid: 'P3151', source: 'iNaturalist', value: '381926' },
    { pid: 'P838', source: 'BioLib', value: '343480' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '188363' },
    { pid: 'P10585', source: 'Catalogue of Life', value: 'YLB6' },
  ],
}

export default cortinariusLargusQ10570865
