// Wikidata data for Mycena viridimarginata (Q10510028)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const mycenaViridimarginataQ10510028: WikidataSpeciesData = {
  slug: 'mycena-viridimarginata',
  wikidataId: 'Q10510028',
  taxonomy: {
    taxonName: 'Mycena viridimarginata',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q1124575', label: 'Mycena' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    shortName: 'M. viridimarginata',
  },
  names: {
    labels: { en: 'Mycena viridimarginata', de: 'Mycena viridimarginata' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Helmlinge (Mycena)' },
    commonNames: [
      { lang: 'cy', value: 'bonet odre gwyrdd' },
      { lang: 'nl', value: 'Groensnedemycena' },
      { lang: 'cs', value: 'helmovka zelenobřitá' },
      { lang: 'fi', value: 'meripihkahiippo' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: ['Mycena viridimarginata.jpg'],
    commonsCategory: 'Mycena viridimarginata',
    commonsGallery: 'Mycena viridimarginata',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '235997' },
    { pid: 'P846', source: 'GBIF', value: '2527145' },
    { pid: 'P962', source: 'MycoBank', value: '235997' },
    { pid: 'P3151', source: 'iNaturalist', value: '738968' },
    { pid: 'P838', source: 'BioLib', value: '317563' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '188439' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '41249' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '6RQFF' },
  ],
}

export default mycenaViridimarginataQ10510028
