// Wikidata data for Cudoniella acicularis (Q10682294)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const cudoniellaAcicularisQ10682294: WikidataSpeciesData = {
  slug: 'cudoniella-acicularis',
  wikidataId: 'Q10682294',
  taxonomy: {
    taxonName: 'Cudoniella acicularis',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q5192540', label: 'Cudoniella' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q15411488', label: 'Helvella acicularis' }],
    shortName: 'C. acicularis',
  },
  names: {
    labels: { en: 'Cudoniella acicularis', de: 'Cudoniella acicularis' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Cudoniella' },
    commonNames: [
      { lang: 'cy', value: 'pen pin derw' },
      { lang: 'nl', value: 'Houtknoopje' },
      { lang: 'cs', value: 'vodnička jehličková' },
      { lang: 'fi', value: 'valkotatikka' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: ['Cudoniella acicularis - Lindsey.jpg'],
    commonsCategory: 'Cudoniella acicularis',
    commonsGallery: 'Cudoniella acicularis',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '220435' },
    { pid: 'P846', source: 'GBIF', value: '2582073' },
    { pid: 'P962', source: 'MycoBank', value: '220435' },
    { pid: 'P3151', source: 'iNaturalist', value: '382065' },
    { pid: 'P838', source: 'BioLib', value: '343878' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '188119' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '354080' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '6BP4P' },
  ],
}

export default cudoniellaAcicularisQ10682294
