// Wikidata data for Russula langei (Q10658025)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const russulaLangeiQ10658025: WikidataSpeciesData = {
  slug: 'russula-langei',
  wikidataId: 'Q10658025',
  taxonomy: {
    taxonName: 'Russula langei',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q216110', labels: { en: 'Russula', de: 'Täublinge' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    authorCitation: 'Bon',
    shortName: 'R. langei',
  },
  names: {
    labels: { en: 'Russula langei', de: 'Russula langei' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Täublinge (Russula)' },
    commonNames: [{ lang: 'cs', value: 'holubinka Langeho' }],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: [],
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '322933',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=322933',
    },
    { pid: 'P846', source: 'GBIF', value: '2551192', url: 'https://www.gbif.org/species/2551192' },
    { pid: 'P962', source: 'MycoBank', value: '322933', url: 'https://www.mycobank.org/MB/322933' },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '360798',
      url: 'https://www.biolib.cz/cz/taxon/id360798',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '193405',
      url: 'https://eol.org/pages/193405',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '1822442',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/1822442',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '4TS5N',
      url: 'https://www.catalogueoflife.org/data/taxon/4TS5N',
    },
  ],
}

export default russulaLangeiQ10658025
