// Wikidata data for Atheniella flavoalba (Q107504319)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const atheniellaFlavoalbaQ107504319: WikidataSpeciesData = {
  slug: 'atheniella-flavoalba',
  wikidataId: 'Q107504319',
  taxonomy: {
    taxonName: 'Atheniella flavoalba',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q4813428', labels: { en: 'Atheniella', de: 'Atheniella' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      {
        pid: 'P566',
        qid: 'Q59537881',
        labels: { en: 'Agaricus flavoalbus', de: 'Agaricus flavoalbus' },
      },
    ],
    authorCitation: '(Fr.) Redhead, Moncalvo, Vilgalys, Desjardin & B.A. Perry',
    shortName: 'A. flavoalba',
  },
  names: {
    labels: { en: 'Atheniella flavoalba', de: 'Atheniella flavoalba' },
    descriptions: {
      en: 'species of fungi in the genus Atheniella',
      de: 'Art der Gattung Atheniella',
    },
    commonNames: [],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: [],
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '550106',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=550106',
    },
    { pid: 'P846', source: 'GBIF', value: '8110284', url: 'https://www.gbif.org/species/8110284' },
    { pid: 'P962', source: 'MycoBank', value: '550106', url: 'https://www.mycobank.org/MB/550106' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '499704',
      url: 'https://inaturalist.org/taxa/499704',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '2750340',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/2750340',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '5VVC8',
      url: 'https://www.catalogueoflife.org/data/taxon/5VVC8',
    },
  ],
}

export default atheniellaFlavoalbaQ107504319
