// Wikidata data for Tolypocladium longisegmentatum (Q108430550)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const tolypocladiumLongisegmentatumQ108430550: WikidataSpeciesData = {
  slug: 'tolypocladium-longisegmentatum',
  wikidataId: 'Q108430550',
  taxonomy: {
    taxonName: 'Tolypocladium longisegmentatum',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q7814691', labels: { en: 'Tolypocladium', de: 'Tolypocladium' } },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    shortName: 'T. longisegmentatum',
  },
  names: {
    labels: { en: 'Tolypocladium longisegmentatum', de: 'Tolypocladium longisegmentatum' },
    descriptions: { de: 'Art der Gattung Tolypocladium' },
    commonNames: [],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: [],
    commonsCategory: 'Tolypocladium longisegmentatum',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '821659',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=821659',
    },
    { pid: 'P846', source: 'GBIF', value: '9799832', url: 'https://www.gbif.org/species/9799832' },
    { pid: 'P962', source: 'MycoBank', value: '821659', url: 'https://www.mycobank.org/MB/821659' },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '57BV7',
      url: 'https://www.catalogueoflife.org/data/taxon/57BV7',
    },
  ],
}

export default tolypocladiumLongisegmentatumQ108430550
