// Wikidata data for Podofomes mollis (Q114852018)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const podofomesMollisQ114852018: WikidataSpeciesData = {
  slug: 'podofomes-mollis',
  wikidataId: 'Q114852018',
  taxonomy: {
    taxonName: 'Podofomes mollis',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q7206999', labels: { en: 'Podofomes', de: 'Podofomes' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      { pid: 'P566', qid: 'Q105052646', labels: { en: 'Daedalea mollis', de: 'Daedalea mollis' } },
    ],
    shortName: 'P. mollis',
  },
  names: {
    labels: { en: 'Podofomes mollis', de: 'Podofomes mollis' },
    descriptions: {
      en: 'species of fungi in the genus Podofomes',
      de: 'Art der Gattung Podofomes',
    },
    commonNames: [],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: [],
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '836279',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=836279',
    },
    {
      pid: 'P846',
      source: 'GBIF',
      value: '12210015',
      url: 'https://www.gbif.org/species/12210015',
    },
  ],
}

export default podofomesMollisQ114852018
