// Wikidata data for Suillus bovinus (Q1165762)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const suillusBovinusQ1165762: WikidataSpeciesData = {
  slug: 'suillus-bovinus',
  wikidataId: 'Q1165762',
  taxonomy: {
    taxonName: 'Suillus bovinus',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q1338220', labels: { en: 'Suillus', de: 'Schmierröhrlinge' } },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      { pid: 'P566', qid: 'Q12200192', labels: { en: 'Boletus bovinus', de: 'Boletus bovinus' } },
    ],
    shortName: 'S. bovinus',
  },
  names: {
    labels: { en: 'Suillus bovinus', de: 'Kuh-Röhrling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Schmierröhrlinge (Suillus)' },
    aliases: {
      en: ['Jersey cow mushroom', 'bovine bolete'],
      de: ['Suillus bovinus', 'Kuhpilz', 'Kuhröhrling'],
    },
    commonNames: [
      { lang: 'cy', value: 'boled yr ych' },
      { lang: 'et', value: 'Lehmapäkk' },
      { lang: 'et', value: 'Lehmapuravik' },
      { lang: 'et', value: 'Lehmatatik' },
      { lang: 'zh', value: '乳牛肝菌' },
      { lang: 'nl', value: 'Koeieboleet' },
      { lang: 'cs', value: 'klouzek kravský' },
      { lang: 'fi', value: 'nummitatti' },
      { lang: 'ast', value: 'funganiellu les vaques' },
      { lang: 'sl', value: 'prožna lupljivka' },
      { lang: 'zh', value: '黏盖乳牛肝菌' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861549', labels: { en: 'pores', de: 'Poren' } },
    capShape: [
      { pid: 'P784', qid: 'Q19887957', labels: { en: 'flat mushroom cap', de: 'ausgebreitet' } },
    ],
    hymeniumAttachment: {
      pid: 'P785',
      qid: 'Q14544569',
      labels: { en: 'adnate hymenium attachment', de: 'Lamellen breit angewachsen' },
    },
    stipeCharacter: {
      pid: 'P786',
      qid: 'Q14544581',
      labels: { en: 'bare stipe', de: 'ringloser Stiel' },
    },
    sporePrintColor: {
      pid: 'P787',
      qid: 'Q19888352',
      labels: { en: 'olive brown', de: 'olivbraun' },
    },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q99974', labels: { en: 'mycorrhiza', de: 'Mykorrhiza' } },
    ],
  },
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q654236', labels: { en: 'edible mushroom', de: 'Speisepilz' } },
      { pid: 'P789', qid: 'Q1686195', labels: { en: 'medicinal mushrooms', de: 'Mykotherapie' } },
    ],
    conservationStatus: [
      { pid: 'P141', qid: 'Q211005', labels: { en: 'least concern', de: 'nicht gefährdet' } },
    ],
  },
  media: {
    images: ['Suillus bovinus Alberto Vázquez.jpg'],
    commonsCategory: 'Suillus bovinus',
    commonsGallery: 'Suillus bovinus',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '356928',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=356928',
    },
    { pid: 'P846', source: 'GBIF', value: '5239860', url: 'https://www.gbif.org/species/5239860' },
    { pid: 'P962', source: 'MycoBank', value: '356928', url: 'https://www.mycobank.org/MB/356928' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '337850',
      url: 'https://inaturalist.org/taxa/337850',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '60179',
      url: 'https://www.biolib.cz/cz/taxon/id60179',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '196980',
      url: 'https://eol.org/pages/196980',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '48563',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/48563',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '53F32',
      url: 'https://www.catalogueoflife.org/data/taxon/53F32',
    },
  ],
}

export default suillusBovinusQ1165762
