// Wikidata data for Mycena epipterygia (Q1183020)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const mycenaEpipterygiaQ1183020: WikidataSpeciesData = {
  slug: 'mycena-epipterygia',
  wikidataId: 'Q1183020',
  taxonomy: {
    taxonName: 'Mycena epipterygia',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q1124575', labels: { en: 'Mycena', de: 'Helmlinge' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      {
        pid: 'P566',
        qid: 'Q105048221',
        labels: { en: 'Agaricus epipterygius', de: 'Agaricus epipterygius' },
      },
    ],
    authorCitation: '(Scop.) Gray',
    shortName: 'M. epipterygia',
  },
  names: {
    labels: { en: 'Mycena epipterygia', de: 'Dehnbarer Helmling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Helmlinge (Mycena)' },
    aliases: {
      de: [
        'Gummi-Helmling',
        'Gummihelmling',
        'Überhäuteter Helmling',
        'Mycena epipterygia',
        'Schleimiger Helmling',
        'Schmieriger Helmling',
      ],
    },
    commonNames: [
      { lang: 'cy', value: 'bonet goes felen' },
      { lang: 'nl', value: 'graskleefsteelmycena' },
      { lang: 'cs', value: 'helmovka slizká' },
      { lang: 'fi', value: 'keltajalkahiippo' },
      { lang: 'fi', value: 'tahmahiippo' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q269345', labels: { en: 'lamella', de: 'Lamelle' } },
    hymeniumAttachment: {
      pid: 'P785',
      qid: 'Q14544569',
      labels: { en: 'adnate hymenium attachment', de: 'Lamellen breit angewachsen' },
    },
    stipeCharacter: {
      pid: 'P786',
      qid: 'Q14544581',
      labels: { en: 'bare stipe', de: 'ringloser Stiel' },
    },
    sporePrintColor: { pid: 'P787', qid: 'Q23444', labels: { en: 'white', de: 'Weiß' } },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q114750', labels: { en: 'saprobiont', de: 'Saprobiont' } },
    ],
  },
  edibility: {
    values: [
      {
        pid: 'P789',
        qid: 'Q4317894',
        labels: { en: 'inedible mushroom', de: 'ungenießbarer Pilz' },
      },
    ],
  },
  media: {
    images: ['Mycena epipterygia - La Maladrie.jpg', 'Dehnbare Helmling Mycena epipterygia.jpg'],
    commonsCategory: 'Mycena epipterygia',
    commonsGallery: 'Mycena epipterygia',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '162405',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=162405',
    },
    { pid: 'P846', source: 'GBIF', value: '2527146', url: 'https://www.gbif.org/species/2527146' },
    { pid: 'P962', source: 'MycoBank', value: '162405', url: 'https://www.mycobank.org/MB/162405' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '179107',
      url: 'https://inaturalist.org/taxa/179107',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '300218',
      url: 'https://www.biolib.cz/cz/taxon/id300218',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '6674908',
      url: 'https://eol.org/pages/6674908',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '230806',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/230806',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '44T39',
      url: 'https://www.catalogueoflife.org/data/taxon/44T39',
    },
  ],
}

export default mycenaEpipterygiaQ1183020
