// Wikidata data for Xylaria hypoxylon (Q1272474)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const xylariaHypoxylonQ1272474: WikidataSpeciesData = {
  slug: 'xylaria-hypoxylon',
  wikidataId: 'Q1272474',
  taxonomy: {
    taxonName: 'Xylaria hypoxylon',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q1625602', labels: { en: 'Xylaria', de: 'Holzkeulen' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      {
        pid: 'P566',
        qid: 'Q21872388',
        labels: { en: 'Clavaria hypoxylon', de: 'Clavaria hypoxylon' },
      },
    ],
    authorCitation: '(L.) Grev.',
    shortName: 'X. hypoxylon',
  },
  names: {
    labels: { en: 'Xylaria hypoxylon', de: 'Geweihförmige Holzkeule' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Holzkeulen (Xylaria)' },
    commonNames: [
      { lang: 'cy', value: 'cyrn gwyn' },
      { lang: 'nl', value: 'Geweizwam' },
      { lang: 'cs', value: 'dřevnatka parohatá' },
      { lang: 'fi', value: 'haarasarvisieni' },
      { lang: 'sl', value: 'vitka lesenjača' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: ['Xylaria hypoxylon1.jpg'],
    commonsCategory: 'Xylaria hypoxylon',
    commonsGallery: 'Xylaria hypoxylon',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '228616',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=228616',
    },
    { pid: 'P846', source: 'GBIF', value: '5255147', url: 'https://www.gbif.org/species/5255147' },
    { pid: 'P962', source: 'MycoBank', value: '228616', url: 'https://www.mycobank.org/MB/228616' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '55267',
      url: 'https://inaturalist.org/taxa/55267',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '59766',
      url: 'https://www.biolib.cz/cz/taxon/id59766',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '1017301',
      url: 'https://eol.org/pages/1017301',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '37992',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/37992',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '5CH3N',
      url: 'https://www.catalogueoflife.org/data/taxon/5CH3N',
    },
  ],
}

export default xylariaHypoxylonQ1272474
