// Wikidata data for Amanita muscaria (Q131227)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const amanitaMuscariaQ131227: WikidataSpeciesData = {
  slug: 'amanita-muscaria',
  wikidataId: 'Q131227',
  taxonomy: {
    taxonName: 'Amanita muscaria',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q213938', labels: { en: 'Amanita', de: 'Wulstlinge' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      {
        pid: 'P566',
        qid: 'Q21870095',
        labels: { en: 'Agaricus muscarius', de: 'Agaricus muscarius' },
      },
    ],
    authorCitation: '(L.) Lam.',
    shortName: 'A. muscaria',
  },
  names: {
    labels: { en: 'Amanita muscaria', de: 'Fliegenpilz' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Wulstlinge (Amanita)' },
    aliases: {
      en: ['fly amanita', 'fly agaric', 'bug agaric'],
      de: [
        'Amanita muscaria',
        'Fliegenschwamm',
        'Amanita muscaria var. muscaria',
        'Roter Fliegenpilz',
      ],
    },
    commonNames: [
      { lang: 'cy', value: "amanita'r gwybed" },
      { lang: 'bar', value: 'Fliangschwammerl' },
      { lang: 'bar', value: 'Flóingschwammerl' },
      { lang: 'be', value: 'Чырвоны мухамор' },
      { lang: 'bg', value: 'Червена мухоморка' },
      { lang: 'ca', value: 'Reig bord' },
      { lang: 'ca', value: 'Reig de fageda' },
      { lang: 'cs', value: 'muchomůrka červená' },
      { lang: 'de', value: 'Fliegenpilz' },
      { lang: 'en', value: 'Fly agaric' },
      { lang: 'et', value: 'Punane kärbseseen' },
      { lang: 'fr', value: 'Amanite tue-mouches' },
      { lang: 'hu', value: 'Légyölő galóca' },
      { lang: 'it', value: 'Ovolaccio' },
      { lang: 'it', value: 'ovolo malefico' },
      { lang: 'ja', value: 'ベニテングタケ' },
      { lang: 'lt', value: 'Paprastoji musmirė' },
      { lang: 'nl', value: 'Vliegenzwam' },
      { lang: 'nb', value: 'Rød fluesopp' },
      { lang: 'pl', value: 'muchomor czerwony' },
      { lang: 'pt', value: 'Agário-das-moscas' },
      { lang: 'pt', value: 'mata-moscas' },
      { lang: 'ru', value: 'Красный мухомор' },
      { lang: 'sk', value: 'Muchotrávka červená' },
      { lang: 'sv', value: 'Röd flugsvamp' },
      { lang: 'tr', value: 'Sinek mantarı' },
      { lang: 'uk', value: 'Мухомор червоний' },
      { lang: 'wa', value: 'Amanite touwe-moxhe' },
      { lang: 'zh', value: '毒蠅傘（繁體、正體）；毒蝇伞（简体）' },
      { lang: 'nl', value: 'vliegenzwam' },
      { lang: 'fr', value: 'amanite tue-mouches' },
      { lang: 'fi', value: 'punakärpässieni' },
      { lang: 'es', value: 'matamoscas' },
      { lang: 'sl', value: 'rdeča mušnica' },
      { lang: 'zh', value: '毒蝇鹅膏' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q269345', labels: { en: 'lamella', de: 'Lamelle' } },
    capShape: [
      { pid: 'P784', qid: 'Q19887957', labels: { en: 'flat mushroom cap', de: 'ausgebreitet' } },
      { pid: 'P784', qid: 'Q14544535', labels: { en: 'convex mushroom cap', de: 'gewölbt' } },
    ],
    hymeniumAttachment: {
      pid: 'P785',
      qid: 'Q14544563',
      labels: { en: 'free hymenium attachment' },
    },
    stipeCharacter: { pid: 'P786', qid: 'Q19887987', labels: { en: 'ring and volva stipe' } },
    sporePrintColor: { pid: 'P787', qid: 'Q23444', labels: { en: 'white', de: 'Weiß' } },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q99974', labels: { en: 'mycorrhiza', de: 'Mykorrhiza' } },
    ],
  },
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q359511', labels: { en: 'poisonous mushroom', de: 'Giftpilz' } },
      {
        pid: 'P789',
        qid: 'Q1169875',
        labels: { en: 'psychoactive mushroom', de: 'psychoaktive Pilze' },
      },
      { pid: 'P789', qid: 'Q1686195', labels: { en: 'medicinal mushrooms', de: 'Mykotherapie' } },
    ],
  },
  media: {
    images: [
      'Amanita muscaria 3 vliegenzwammen op rij.jpg',
      'Amanita muscaria, Kyiv Region, Pushcha-Vodytsia Forestry.jpg',
    ],
    commonsCategory: 'Amanita muscaria',
    commonsGallery: 'Amanita muscaria',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '161267',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=161267',
    },
    { pid: 'P846', source: 'GBIF', value: '8168319', url: 'https://www.gbif.org/species/8168319' },
    { pid: 'P962', source: 'MycoBank', value: '161267', url: 'https://www.mycobank.org/MB/161267' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '48715',
      url: 'https://inaturalist.org/taxa/48715',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '60470',
      url: 'https://www.biolib.cz/cz/taxon/id60470',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '2866150',
      url: 'https://eol.org/pages/2866150',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '41956',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/41956',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '5TYZ9',
      url: 'https://www.catalogueoflife.org/data/taxon/5TYZ9',
    },
  ],
}

export default amanitaMuscariaQ131227
