// Wikidata data for Amanita muscaria (Q131227)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const amanitaMuscariaQ131227: WikidataSpeciesData = {
  slug: 'amanita-muscaria',
  wikidataId: 'Q131227',
  taxonomy: {
    taxonName: 'Amanita muscaria',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q213938', label: 'Amanita' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q21870095', label: 'Agaricus muscarius' }],
    authorCitation: '(L.) Lam.',
    shortName: 'A. muscaria',
  },
  names: {
    labels: { en: 'Amanita muscaria', de: 'Fliegenpilz' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Wulstlinge (Amanita)' },
    aliases: {
      en: ['fly amanita', 'fly agaric', 'bug agaric'],
      de: [
        'Amanita muscaria',
        'Fliegenschwamm',
        'Amanita muscaria var. muscaria',
        'Roter Fliegenpilz',
      ],
    },
    commonNames: [
      { lang: 'cy', value: "amanita'r gwybed" },
      { lang: 'bar', value: 'Fliangschwammerl' },
      { lang: 'bar', value: 'Flóingschwammerl' },
      { lang: 'be', value: 'Чырвоны мухамор' },
      { lang: 'bg', value: 'Червена мухоморка' },
      { lang: 'ca', value: 'Reig bord' },
      { lang: 'ca', value: 'Reig de fageda' },
      { lang: 'cs', value: 'muchomůrka červená' },
      { lang: 'de', value: 'Fliegenpilz' },
      { lang: 'en', value: 'Fly agaric' },
      { lang: 'et', value: 'Punane kärbseseen' },
      { lang: 'fr', value: 'Amanite tue-mouches' },
      { lang: 'hu', value: 'Légyölő galóca' },
      { lang: 'it', value: 'Ovolaccio' },
      { lang: 'it', value: 'ovolo malefico' },
      { lang: 'ja', value: 'ベニテングタケ' },
      { lang: 'lt', value: 'Paprastoji musmirė' },
      { lang: 'nl', value: 'Vliegenzwam' },
      { lang: 'nb', value: 'Rød fluesopp' },
      { lang: 'pl', value: 'muchomor czerwony' },
      { lang: 'pt', value: 'Agário-das-moscas' },
      { lang: 'pt', value: 'mata-moscas' },
      { lang: 'ru', value: 'Красный мухомор' },
      { lang: 'sk', value: 'Muchotrávka červená' },
      { lang: 'sv', value: 'Röd flugsvamp' },
      { lang: 'tr', value: 'Sinek mantarı' },
      { lang: 'uk', value: 'Мухомор червоний' },
      { lang: 'wa', value: 'Amanite touwe-moxhe' },
      { lang: 'zh', value: '毒蠅傘（繁體、正體）；毒蝇伞（简体）' },
      { lang: 'nl', value: 'vliegenzwam' },
      { lang: 'fr', value: 'amanite tue-mouches' },
      { lang: 'fi', value: 'punakärpässieni' },
      { lang: 'es', value: 'matamoscas' },
      { lang: 'sl', value: 'rdeča mušnica' },
      { lang: 'zh', value: '毒蝇鹅膏' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q269345', label: 'lamella' },
    capShape: [
      { pid: 'P784', qid: 'Q19887957', label: 'flat mushroom cap' },
      { pid: 'P784', qid: 'Q14544535', label: 'convex mushroom cap' },
    ],
    hymeniumAttachment: { pid: 'P785', qid: 'Q14544563', label: 'free hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q19887987', label: 'ring and volva stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q23444', label: 'white' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q359511', label: 'poisonous mushroom' },
      { pid: 'P789', qid: 'Q1169875', label: 'psychoactive mushroom' },
      { pid: 'P789', qid: 'Q1686195', label: 'medicinal mushrooms' },
    ],
  },
  media: {
    images: [
      'Amanita muscaria 3 vliegenzwammen op rij.jpg',
      'Amanita muscaria, Kyiv Region, Pushcha-Vodytsia Forestry.jpg',
    ],
    commonsCategory: 'Amanita muscaria',
    commonsGallery: 'Amanita muscaria',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '161267' },
    { pid: 'P846', source: 'GBIF', value: '8168319' },
    { pid: 'P962', source: 'MycoBank', value: '161267' },
    { pid: 'P3151', source: 'iNaturalist', value: '48715' },
    { pid: 'P838', source: 'BioLib', value: '60470' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '2866150' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '41956' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '5TYZ9' },
  ],
}

export default amanitaMuscariaQ131227
