// Wikidata data for Hydnum repandum (Q13684)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const hydnumRepandumQ13684: WikidataSpeciesData = {
  slug: 'hydnum-repandum',
  wikidataId: 'Q13684',
  taxonomy: {
    taxonName: 'Hydnum repandum',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q159023', labels: { en: 'Hydnum', de: 'Hydnum' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    authorCitation: 'L.',
    shortName: 'H. repandum',
  },
  names: {
    labels: { en: 'wood hedgehog', de: 'Semmel-Stoppelpilz' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Stoppelpilze (Hydnum)' },
    aliases: {
      en: ['sweet tooth', 'Hydnum repandum', 'hedgehog mushroom'],
      de: [
        'Semmelstoppelpilz',
        'Stoppelpilz',
        'Hydnum repandum',
        'Semmelgelber Stacheling',
        'Schafsfußpilz',
      ],
    },
    commonNames: [
      { lang: 'cy', value: 'pigau draenog y coed' },
      { lang: 'cs', value: 'lišák zprohýbaný' },
      { lang: 'cs', value: 'lošák zprohýbaný' },
      { lang: 'zh', value: '卷緣齒菌' },
      { lang: 'nl', value: 'Gele stekelzwam' },
      { lang: 'fi', value: 'vaaleaorakas' },
      { lang: 'de', value: 'Semmel-Stoppelpilz' },
      { lang: 'ast', value: 'llingua de gatu' },
      { lang: 'ca', value: 'llengua de bou' },
      { lang: 'nb', value: 'sørlig blek piggsopp' },
      { lang: 'zh', value: '卷缘齿菌' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861552', labels: { en: 'teeth', de: 'Stacheln' } },
    capShape: [
      {
        pid: 'P784',
        qid: 'Q19887955',
        labels: { en: 'depressed mushroom cap', de: 'Mitte niedergedrückt' },
      },
    ],
    hymeniumAttachment: {
      pid: 'P785',
      qid: 'Q19887925',
      labels: { en: 'decurrent hymenium attachment', de: 'Lamellen herablaufend' },
    },
    stipeCharacter: {
      pid: 'P786',
      qid: 'Q14544581',
      labels: { en: 'bare stipe', de: 'ringloser Stiel' },
    },
    sporePrintColor: { pid: 'P787', qid: 'Q23444', labels: { en: 'white', de: 'Weiß' } },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q99974', labels: { en: 'mycorrhiza', de: 'Mykorrhiza' } },
    ],
  },
  edibility: {
    values: [
      {
        pid: 'P789',
        qid: 'Q19888517',
        labels: { en: 'choice mushroom', de: 'hervorragender Speisepilz' },
      },
      { pid: 'P789', qid: 'Q654236', labels: { en: 'edible mushroom', de: 'Speisepilz' } },
      { pid: 'P789', qid: 'Q1686195', labels: { en: 'medicinal mushrooms', de: 'Mykotherapie' } },
    ],
    conservationStatus: [
      { pid: 'P141', qid: 'Q211005', labels: { en: 'least concern', de: 'nicht gefährdet' } },
    ],
  },
  media: {
    images: ['Hedgehog fungi2.jpg'],
    commonsCategory: 'Hydnum repandum',
    commonsGallery: 'Hydnum repandum',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '225014',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=225014',
    },
    { pid: 'P846', source: 'GBIF', value: '2554716', url: 'https://www.gbif.org/species/2554716' },
    { pid: 'P962', source: 'MycoBank', value: '225014', url: 'https://www.mycobank.org/MB/225014' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '48641',
      url: 'https://inaturalist.org/taxa/48641',
    },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '411455',
      url: 'https://inaturalist.org/taxa/411455',
    },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '340867',
      url: 'https://inaturalist.org/taxa/340867',
    },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '122170',
      url: 'https://inaturalist.org/taxa/122170',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '59880',
      url: 'https://www.biolib.cz/cz/taxon/id59880',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '960112',
      url: 'https://eol.org/pages/960112',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '68759',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/68759',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '3N275',
      url: 'https://www.catalogueoflife.org/data/taxon/3N275',
    },
  ],
}

export default hydnumRepandumQ13684
