// Wikidata data for Collybiopsis vaillantii (Q136395649)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const collybiopsisVaillantiiQ136395649: WikidataSpeciesData = {
  slug: 'collybiopsis-vaillantii',
  wikidataId: 'Q136395649',
  taxonomy: {
    taxonName: 'Collybiopsis vaillantii',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q5147604', labels: { en: 'Collybiopsis', de: 'Collybiopsis' } },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    authorCitation: '(Pers.) R.H. Petersen',
  },
  names: {
    labels: { en: 'Collybiopsis vaillantii' },
    descriptions: { en: 'species of fungi' },
    commonNames: [],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: [],
  },
  externalIds: [],
}

export default collybiopsisVaillantiiQ136395649
