// Wikidata data for Clavulina coralloides (Q138027)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const clavulinaCoralloidesQ138027: WikidataSpeciesData = {
  slug: 'clavulina-coralloides',
  wikidataId: 'Q138027',
  taxonomy: {
    taxonName: 'Clavulina coralloides',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q336963', label: 'Clavulina' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q21872381', label: 'Clavaria coralloides' }],
    authorCitation: '(L.) J.Schröt.',
    shortName: 'C. coralloides',
  },
  names: {
    labels: { en: 'Clavulina coralloides', de: 'Kammförmiger Keulenpilz' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Keulenpilze (Clavulina)' },
    aliases: {
      en: ['Clavulina cristata'],
      de: [
        'Ramaria cristata',
        'Clavulina cristata',
        'Kammkoralle',
        'Clavulina coralloides',
        'Kammförmiger Korallenpilz',
        'Kamm-Ziegenbart',
        'Kammförmige Koralle',
        'Kammziegenbart',
        'Clavaria cristata',
      ],
    },
    commonNames: [
      { lang: 'cy', value: 'cwrel cribog' },
      { lang: 'zh', value: '冠鎖瑚菌' },
      { lang: 'cs', value: 'kuřátečko hřebenité' },
      { lang: 'fi', value: 'korallihaarakas' },
      { lang: 'zh', value: '珊瑚状锁瑚菌' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861550', label: 'smooth' },
    capShape: [{ pid: 'P784', qid: 'Q19887965', label: 'no mushroom cap' }],
    stipeCharacter: { pid: 'P786', qid: 'Q14544581', label: 'bare stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q23444', label: 'white' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q114750', label: 'saprobiont' }],
  },
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q62102033', label: 'edible when cooked' },
      { pid: 'P789', qid: 'Q654236', label: 'edible mushroom' },
    ],
  },
  media: {
    images: ['Clavulina cristata sasata.JPG'],
    commonsCategory: 'Clavulina coralloides',
    commonsGallery: 'Clavulina coralloides',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '114573' },
    { pid: 'P846', source: 'GBIF', value: '5249883' },
    { pid: 'P962', source: 'MycoBank', value: '114573' },
    { pid: 'P3151', source: 'iNaturalist', value: '63260' },
    { pid: 'P3151', source: 'iNaturalist', value: '63258' },
    { pid: 'P838', source: 'BioLib', value: '125725' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '300056' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '1329069' },
  ],
}

export default clavulinaCoralloidesQ138027
