// Wikidata data for Clavulinopsis helvola (Q138029)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const clavulinopsisHelvolaQ138029: WikidataSpeciesData = {
  slug: 'clavulinopsis-helvola',
  wikidataId: 'Q138029',
  taxonomy: {
    taxonName: 'Clavulinopsis helvola',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q979342', labels: { en: 'Clavulinopsis', de: 'Wiesenkeulen' } },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      { pid: 'P566', qid: 'Q59452834', labels: { en: 'Clavaria helvola', de: 'Clavaria helvola' } },
    ],
    authorCitation: '(Pers.) Corner (1950)',
    shortName: 'C. helvola',
  },
  names: {
    labels: { en: 'Clavulinopsis helvola', de: 'Clavulinopsis helvola' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Wiesenkeulen (Clavulinopsis)' },
    commonNames: [
      { lang: 'cs', value: 'kyjovečka hnědavá' },
      { lang: 'fi', value: 'oranssinuijakas' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: ['Clavulinopsis helvola.jpg'],
    commonsCategory: 'Clavulinopsis helvola',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '295060',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=295060',
    },
    { pid: 'P846', source: 'GBIF', value: '5244387', url: 'https://www.gbif.org/species/5244387' },
    { pid: 'P962', source: 'MycoBank', value: '295060', url: 'https://www.mycobank.org/MB/295060' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '362042',
      url: 'https://inaturalist.org/taxa/362042',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '125650',
      url: 'https://www.biolib.cz/cz/taxon/id125650',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '190899',
      url: 'https://eol.org/pages/190899',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '2872525',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/2872525',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: 'VWBD',
      url: 'https://www.catalogueoflife.org/data/taxon/VWBD',
    },
  ],
}

export default clavulinopsisHelvolaQ138029
