// Wikidata data for Craterellus lutescens (Q1478429)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const craterellusLutescensQ1478429: WikidataSpeciesData = {
  slug: 'craterellus-lutescens',
  wikidataId: 'Q1478429',
  taxonomy: {
    taxonName: 'Craterellus lutescens',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q2097845', labels: { en: 'Craterellus', de: 'Kraterellen' } },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      {
        pid: 'P566',
        qid: 'Q100378193',
        labels: { en: 'Cantharellus lutescens', de: 'Cantharellus lutescens' },
      },
    ],
    shortName: 'C. lutescens',
  },
  names: {
    labels: { en: 'Craterellus lutescens', de: 'Starkriechender Trompetenpfifferling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Kraterellen (Craterellus)' },
    aliases: {
      en: ['Yellow Foot'],
      de: [
        'Wohlduftender Pfifferling',
        'Gelbstieliger Leistling',
        'Cantharellus aurora',
        'Starkriechender Leistling',
        'Gelbe Kraterelle',
        'Duftender Gabeling',
        'Starkriechender Trompeten-Pfifferling',
        'Goldstieliger Pfifferling',
        'Gelbe Kantharelle',
        'Cantharellus lutescens',
        'Craterellus lutescens',
        'Cantharellus xanthopus',
        'Starkriechender Pfifferling',
        'Goldstieliger Leistling',
        'Morgenrot-Pfifferling',
      ],
    },
    commonNames: [
      { lang: 'fi', value: 'kosteikkovahvero' },
      { lang: 'de', value: 'Starkriechender Pfifferling' },
      { lang: 'de', value: 'Morgenrot-Pfifferling' },
      { lang: 'ast', value: 'cornetu' },
      { lang: 'zh', value: '变黄喇叭菌' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861551', labels: { en: 'ridges' } },
    capShape: [
      {
        pid: 'P784',
        qid: 'Q19887958',
        labels: { en: 'infundibuliform mushroom cap', de: 'trichterförmig' },
      },
    ],
    hymeniumAttachment: {
      pid: 'P785',
      qid: 'Q19887925',
      labels: { en: 'decurrent hymenium attachment', de: 'Lamellen herablaufend' },
    },
    stipeCharacter: {
      pid: 'P786',
      qid: 'Q14544581',
      labels: { en: 'bare stipe', de: 'ringloser Stiel' },
    },
    sporePrintColor: { pid: 'P787', qid: 'Q2730433', labels: { en: 'cream', de: 'cremefarben' } },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q114750', labels: { en: 'saprobiont', de: 'Saprobiont' } },
    ],
  },
  edibility: {
    values: [
      {
        pid: 'P789',
        qid: 'Q19888517',
        labels: { en: 'choice mushroom', de: 'hervorragender Speisepilz' },
      },
      { pid: 'P789', qid: 'Q654236', labels: { en: 'edible mushroom', de: 'Speisepilz' } },
    ],
  },
  media: {
    images: ['Cantharellus lutescens.jpg'],
    commonsCategory: 'Craterellus lutescens',
    commonsGallery: 'Craterellus lutescens',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '184644',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=184644',
    },
    { pid: 'P846', source: 'GBIF', value: '8871787', url: 'https://www.gbif.org/species/8871787' },
    { pid: 'P962', source: 'MycoBank', value: '184644', url: 'https://www.mycobank.org/MB/184644' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '514218',
      url: 'https://inaturalist.org/taxa/514218',
    },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '350293',
      url: 'https://inaturalist.org/taxa/350293',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '11524954',
      url: 'https://eol.org/pages/11524954',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: 'Z8SW',
      url: 'https://www.catalogueoflife.org/data/taxon/Z8SW',
    },
  ],
}

export default craterellusLutescensQ1478429
