// Wikidata data for Gomphus clavatus (Q1478471)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const gomphusClavatusQ1478471: WikidataSpeciesData = {
  slug: 'gomphus-clavatus',
  wikidataId: 'Q1478471',
  taxonomy: {
    taxonName: 'Gomphus clavatus',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q2068837', labels: { en: 'Gomphus', de: 'Gomphus' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      {
        pid: 'P566',
        qid: 'Q54362701',
        labels: { en: 'Merulius clavatus', de: 'Merulius clavatus' },
      },
    ],
    shortName: 'G. clavatus',
  },
  names: {
    labels: { en: 'Gomphus clavatus', de: 'Schweinsohr' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Schweinsohren (Gomphus)' },
    aliases: {
      en: ['Pigís ear', 'Pigis ear'],
      de: ['Purpurleistling', 'Schweinsohren', 'Purpur-Leistling', 'Gomphus clavatus'],
    },
    commonNames: [
      { lang: 'cy', value: 'clust mochyn' },
      { lang: 'cs', value: 'stročkovec kyjovitý' },
      { lang: 'fi', value: 'pölkkysieni' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861551', labels: { en: 'ridges' } },
    capShape: [
      {
        pid: 'P784',
        qid: 'Q19887958',
        labels: { en: 'infundibuliform mushroom cap', de: 'trichterförmig' },
      },
    ],
    hymeniumAttachment: {
      pid: 'P785',
      qid: 'Q19887925',
      labels: { en: 'decurrent hymenium attachment', de: 'Lamellen herablaufend' },
    },
    stipeCharacter: {
      pid: 'P786',
      qid: 'Q14544581',
      labels: { en: 'bare stipe', de: 'ringloser Stiel' },
    },
    sporePrintColor: { pid: 'P787', qid: 'Q943', labels: { en: 'yellow', de: 'Gelb' } },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q99974', labels: { en: 'mycorrhiza', de: 'Mykorrhiza' } },
    ],
  },
  edibility: {
    values: [{ pid: 'P789', qid: 'Q654236', labels: { en: 'edible mushroom', de: 'Speisepilz' } }],
  },
  media: {
    images: ['Gomphus clavatus best.jpg'],
    commonsCategory: 'Gomphus clavatus',
    commonsGallery: 'Gomphus clavatus',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '356880',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=356880',
    },
    { pid: 'P846', source: 'GBIF', value: '5238786', url: 'https://www.gbif.org/species/5238786' },
    { pid: 'P962', source: 'MycoBank', value: '356880', url: 'https://www.mycobank.org/MB/356880' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '54121',
      url: 'https://inaturalist.org/taxa/54121',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '59899',
      url: 'https://www.biolib.cz/cz/taxon/id59899',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '195238',
      url: 'https://eol.org/pages/195238',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '80588',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/80588',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '3GTQ3',
      url: 'https://www.catalogueoflife.org/data/taxon/3GTQ3',
    },
  ],
}

export default gomphusClavatusQ1478471
