// Wikidata data for Craterellus lutescens (Q1478429)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const craterellusLutescensQ1478429: WikidataSpeciesData = {
  slug: 'craterellus-lutescens',
  wikidataId: 'Q1478429',
  taxonomy: {
    taxonName: 'Craterellus lutescens',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q2097845', label: 'Craterellus' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q100378193', label: 'Cantharellus lutescens' }],
    shortName: 'C. lutescens',
  },
  names: {
    labels: { en: 'Craterellus lutescens', de: 'Starkriechender Trompetenpfifferling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Kraterellen (Craterellus)' },
    aliases: {
      en: ['Yellow Foot'],
      de: [
        'Wohlduftender Pfifferling',
        'Gelbstieliger Leistling',
        'Cantharellus aurora',
        'Starkriechender Leistling',
        'Gelbe Kraterelle',
        'Duftender Gabeling',
        'Starkriechender Trompeten-Pfifferling',
        'Goldstieliger Pfifferling',
        'Gelbe Kantharelle',
        'Cantharellus lutescens',
        'Craterellus lutescens',
        'Cantharellus xanthopus',
        'Starkriechender Pfifferling',
        'Goldstieliger Leistling',
        'Morgenrot-Pfifferling',
      ],
    },
    commonNames: [
      { lang: 'fi', value: 'kosteikkovahvero' },
      { lang: 'de', value: 'Starkriechender Pfifferling' },
      { lang: 'de', value: 'Morgenrot-Pfifferling' },
      { lang: 'ast', value: 'cornetu' },
      { lang: 'zh', value: '变黄喇叭菌' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861551', label: 'ridges' },
    capShape: [{ pid: 'P784', qid: 'Q19887958', label: 'infundibuliform mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887925', label: 'decurrent hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q14544581', label: 'bare stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q2730433', label: 'cream' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q114750', label: 'saprobiont' }],
  },
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q19888517', label: 'choice mushroom' },
      { pid: 'P789', qid: 'Q654236', label: 'edible mushroom' },
    ],
  },
  media: {
    images: ['Cantharellus lutescens.jpg'],
    commonsCategory: 'Craterellus lutescens',
    commonsGallery: 'Craterellus lutescens',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '184644' },
    { pid: 'P846', source: 'GBIF', value: '8871787' },
    { pid: 'P962', source: 'MycoBank', value: '184644' },
    { pid: 'P3151', source: 'iNaturalist', value: '514218' },
    { pid: 'P3151', source: 'iNaturalist', value: '350293' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '11524954' },
    { pid: 'P10585', source: 'Catalogue of Life', value: 'Z8SW' },
  ],
}

export default craterellusLutescensQ1478429
