// Wikidata data for Cyathus striatus (Q1519672)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const cyathusStriatusQ1519672: WikidataSpeciesData = {
  slug: 'cyathus-striatus',
  wikidataId: 'Q1519672',
  taxonomy: {
    taxonName: 'Cyathus striatus',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q1580329', labels: { en: 'Cyathus', de: 'Teuerlinge' } }],
    instanceOf: [
      { pid: 'P31', qid: 'Q23038290', labels: { en: 'fossil taxon', de: 'fossiles Taxon' } },
    ],
    authorCitation: '(Huds.) Pers.',
    shortName: 'C. striatus',
  },
  names: {
    labels: { en: 'Cyathus striatus', de: 'Gestreifter Teuerling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Teuerlinge (Cyathus)' },
    aliases: { de: ['Cyathus striatus'] },
    commonNames: [
      { lang: 'cy', value: 'nyth aderyn rhesog' },
      { lang: 'de', value: 'Gestreifter Teuerling' },
      { lang: 'en', value: "Fluted bird's nest" },
      { lang: 'fr', value: 'Cyathe strié' },
      { lang: 'nl', value: 'Gestreept nestzwammetje' },
      { lang: 'pl', value: 'Kubek prążkowany' },
      { lang: 'zh', value: '隆紋黑蛋巢菌' },
      { lang: 'cs', value: 'číšenka rýhovaná' },
      { lang: 'fi', value: 'uurrepesäsieni' },
      { lang: 'ast', value: 'ñeru' },
      { lang: 'zh', value: '隆纹黑蛋巢菌' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q2034230', labels: { en: 'gleba', de: 'Gleba' } },
    capShape: [
      {
        pid: 'P784',
        qid: 'Q19887958',
        labels: { en: 'infundibuliform mushroom cap', de: 'trichterförmig' },
      },
    ],
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q114750', labels: { en: 'saprobiont', de: 'Saprobiont' } },
    ],
  },
  edibility: {
    values: [
      {
        pid: 'P789',
        qid: 'Q4317894',
        labels: { en: 'inedible mushroom', de: 'ungenießbarer Pilz' },
      },
      { pid: 'P789', qid: 'Q1686195', labels: { en: 'medicinal mushrooms', de: 'Mykotherapie' } },
    ],
  },
  media: {
    images: ['Gestreifter Teuerling01.jpg'],
    commonsCategory: 'Cyathus striatus',
    commonsGallery: 'Cyathus striatus',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '211223',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=211223',
    },
    { pid: 'P846', source: 'GBIF', value: '5243151', url: 'https://www.gbif.org/species/5243151' },
    { pid: 'P846', source: 'GBIF', value: '8269749', url: 'https://www.gbif.org/species/8269749' },
    { pid: 'P962', source: 'MycoBank', value: '211223', url: 'https://www.mycobank.org/MB/211223' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '120242',
      url: 'https://inaturalist.org/taxa/120242',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '60794',
      url: 'https://www.biolib.cz/cz/taxon/id60794',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '162782',
      url: 'https://eol.org/pages/162782',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '68777',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/68777',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '32RB9',
      url: 'https://www.catalogueoflife.org/data/taxon/32RB9',
    },
  ],
}

export default cyathusStriatusQ1519672
