// Wikidata data for Clathrus archeri (Q1757951)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const clathrusArcheriQ1757951: WikidataSpeciesData = {
  slug: 'clathrus-archeri',
  wikidataId: 'Q1757951',
  taxonomy: {
    taxonName: 'Clathrus archeri',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q913940', label: 'Clathrus' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q59455934', label: 'Lysurus archeri' }],
    authorCitation: '(Berk.) Dring',
    shortName: 'C. archeri',
  },
  names: {
    labels: { en: 'Clathrus archeri', de: 'Tintenfischpilz' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Gitterlinge (Clathrus)' },
    aliases: { en: ['octopus stinkhorn', "devil's fingers"], de: ['Clathrus archeri'] },
    commonNames: [
      { lang: 'cy', value: 'bysedd cythraul' },
      { lang: 'cs', value: 'květnatec Archerův' },
      { lang: 'ast', value: 'pates de gallu' },
      { lang: 'sl', value: 'lovkasta mrežnica' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q2034230', label: 'gleba' },
    capShape: [{ pid: 'P784', qid: 'Q19887965', label: 'no mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887932', label: 'no hymenium attachment' },
    sporePrintColor: { pid: 'P787', qid: 'Q19888352', label: 'olive brown' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q114750', label: 'saprobiont' }],
  },
  edibility: {
    values: [{ pid: 'P789', qid: 'Q4317894', label: 'inedible mushroom' }],
  },
  media: {
    images: ['Clathrus archeri.jpg', 'Tintenfischpilz 1a.JPG'],
    commonsCategory: 'Clathrus archeri',
    commonsGallery: 'Clathrus archeri',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '112728' },
    { pid: 'P846', source: 'GBIF', value: '5239483' },
    { pid: 'P962', source: 'MycoBank', value: '112728' },
    { pid: 'P3151', source: 'iNaturalist', value: '51135' },
    { pid: 'P838', source: 'BioLib', value: '60809' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '1029300' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '1449397' },
    { pid: 'P10585', source: 'Catalogue of Life', value: 'VT9Z' },
  ],
}

export default clathrusArcheriQ1757951
