// Wikidata data for Calocera Cornea (Q175548)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const caloceraCorneaQ175548: WikidataSpeciesData = {
  slug: 'calocera-cornea',
  wikidataId: 'Q175548',
  taxonomy: {
    taxonName: 'Calocera cornea',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q736319', labels: { en: 'Calocera', de: 'Calocera' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      { pid: 'P566', qid: 'Q105050681', labels: { en: 'Clavaria cornea', de: 'Clavaria cornea' } },
    ],
    authorCitation: '(Batsch) Fr.',
    shortName: 'C. cornea',
  },
  names: {
    labels: { en: 'Calocera cornea', de: 'Pfriemlicher Laubholz-Hörnling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Hörnlinge (Calocera)' },
    commonNames: [
      { lang: 'cy', value: 'corn carw bach' },
      { lang: 'zh', value: '膠角耳' },
      { lang: 'nl', value: 'Geel hoorntje' },
      { lang: 'cs', value: 'krásnorůžek rohovitý' },
      { lang: 'fi', value: 'pikkusarvikka' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861550', labels: { en: 'smooth' } },
    capShape: [{ pid: 'P784', qid: 'Q19887965', labels: { en: 'no mushroom cap' } }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887932', labels: { en: 'no hymenium attachment' } },
    stipeCharacter: {
      pid: 'P786',
      qid: 'Q14544581',
      labels: { en: 'bare stipe', de: 'ringloser Stiel' },
    },
    sporePrintColor: { pid: 'P787', qid: 'Q23444', labels: { en: 'white', de: 'Weiß' } },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q114750', labels: { en: 'saprobiont', de: 'Saprobiont' } },
    ],
  },
  edibility: {
    values: [
      {
        pid: 'P789',
        qid: 'Q4317894',
        labels: { en: 'inedible mushroom', de: 'ungenießbarer Pilz' },
      },
    ],
  },
  media: {
    images: ['Calocera cornea 38121.jpg'],
    commonsCategory: 'Calocera cornea',
    commonsGallery: 'Calocera cornea',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '237408',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=237408',
    },
    { pid: 'P846', source: 'GBIF', value: '2512969', url: 'https://www.gbif.org/species/2512969' },
    { pid: 'P962', source: 'MycoBank', value: '237408', url: 'https://www.mycobank.org/MB/237408' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '118027',
      url: 'https://inaturalist.org/taxa/118027',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '59824',
      url: 'https://www.biolib.cz/cz/taxon/id59824',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '188676',
      url: 'https://eol.org/pages/188676',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '29889',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/29889',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: 'PX52',
      url: 'https://www.catalogueoflife.org/data/taxon/PX52',
    },
  ],
}

export default caloceraCorneaQ175548
