// Wikidata data for Rickenella fibula (Q1770667)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const rickenellaFibulaQ1770667: WikidataSpeciesData = {
  slug: 'rickenella-fibula',
  wikidataId: 'Q1770667',
  taxonomy: {
    taxonName: 'Rickenella fibula',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q2714656', labels: { en: 'Rickenella', de: 'Rickenella' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      { pid: 'P566', qid: 'Q105048244', labels: { en: 'Agaricus fibula', de: 'Agaricus fibula' } },
    ],
    authorCitation: '(Bull.) Raithelh.',
    shortName: 'R. fibula',
  },
  names: {
    labels: { en: 'Rickenella fibula', de: 'Orangeroter Heftelnabeling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Rickenella' },
    commonNames: [
      { lang: 'cy', value: 'cap mwsogl oren' },
      { lang: 'nl', value: 'Oranjegeel trechtertje' },
      { lang: 'cs', value: 'kalichovka oranžová' },
      { lang: 'fi', value: 'oranssilakki' },
      { lang: 'sl', value: 'oranžnorumena mahoživka' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: ['2011-10-28 Rickenella fibula (Bulliard- Fries) Raithelhuber 178120 cropped.jpg'],
    commonsCategory: 'Rickenella fibula',
    commonsGallery: 'Rickenella fibula',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '322818',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=322818',
    },
    { pid: 'P846', source: 'GBIF', value: '2523473', url: 'https://www.gbif.org/species/2523473' },
    { pid: 'P962', source: 'MycoBank', value: '322818', url: 'https://www.mycobank.org/MB/322818' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '118170',
      url: 'https://inaturalist.org/taxa/118170',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '60380',
      url: 'https://www.biolib.cz/cz/taxon/id60380',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '52786724',
      url: 'https://eol.org/pages/52786724',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '264144',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/264144',
    },
  ],
}

export default rickenellaFibulaQ1770667
