// Wikidata data for Coprinus niveus (Q1815847)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const coprinusNiveusQ1815847: WikidataSpeciesData = {
  slug: 'coprinus-niveus',
  wikidataId: 'Q1815847',
  taxonomy: {
    taxonName: 'Coprinus niveus',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q289890', labels: { en: 'Coprinus', de: 'Tintlinge' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      {
        pid: 'P566',
        qid: 'Q63033721',
        labels: { en: 'Agaricus niveus', de: 'Agaricus niveus Pers. (1801)' },
      },
    ],
    authorCitation: '(Pers.) Fr.',
    shortName: 'C. niveus',
  },
  names: {
    labels: { en: 'Coprinus niveus', de: 'Coprinus niveus' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Tintlinge (Coprinus)' },
    commonNames: [],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: [],
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '232960',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=232960',
    },
    { pid: 'P846', source: 'GBIF', value: '2534475', url: 'https://www.gbif.org/species/2534475' },
    { pid: 'P962', source: 'MycoBank', value: '232960', url: 'https://www.mycobank.org/MB/232960' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '348091',
      url: 'https://inaturalist.org/taxa/348091',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: 'Y5JG',
      url: 'https://www.catalogueoflife.org/data/taxon/Y5JG',
    },
  ],
}

export default coprinusNiveusQ1815847
