// Wikidata data for Coprinus niveus (Q1815847)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const coprinusNiveusQ1815847: WikidataSpeciesData = {
  slug: 'coprinus-niveus',
  wikidataId: 'Q1815847',
  taxonomy: {
    taxonName: 'Coprinus niveus',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q289890', label: 'Coprinus' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q63033721', label: 'Agaricus niveus' }],
    authorCitation: '(Pers.) Fr.',
    shortName: 'C. niveus',
  },
  names: {
    labels: { en: 'Coprinus niveus', de: 'Coprinus niveus' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Tintlinge (Coprinus)' },
    commonNames: [],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: [],
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '232960' },
    { pid: 'P846', source: 'GBIF', value: '2534475' },
    { pid: 'P962', source: 'MycoBank', value: '232960' },
    { pid: 'P3151', source: 'iNaturalist', value: '348091' },
    { pid: 'P10585', source: 'Catalogue of Life', value: 'Y5JG' },
  ],
}

export default coprinusNiveusQ1815847
