// Wikidata data for Amanita phalloides (Q188643)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const amanitaPhalloidesQ188643: WikidataSpeciesData = {
  slug: 'amanita-phalloides',
  wikidataId: 'Q188643',
  taxonomy: {
    taxonName: 'Amanita phalloides',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q213938', label: 'Amanita' }],
    instanceOf: [
      { pid: 'P31', qid: 'Q16521', label: 'taxon' },
      { pid: 'P31', qid: 'Q11619941', label: 'mycorrhizal fungus' },
    ],
    basionym: [{ pid: 'P566', qid: 'Q61962642', label: 'Agaricus phalloides' }],
    authorCitation: '(Vaill. ex Fr.) Link',
    shortName: 'A. phalloides',
  },
  names: {
    labels: { en: 'Amanita phalloides', de: 'Grüner Knollenblätterpilz' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Wulstlinge (Amanita)' },
    aliases: {
      en: ['death cap'],
      de: [
        'Knollenblätterpilz',
        'Grüner Gift-Wulstling',
        'Amanita phalloides',
        'Grüner Giftwulstling',
      ],
    },
    commonNames: [
      { lang: 'cy', value: 'cap marwol' },
      { lang: 'nl', value: 'Groene knolamaniet' },
      { lang: 'cs', value: 'muchomůrka zelená' },
      { lang: 'fi', value: 'kavalakärpässieni' },
      { lang: 'fr', value: 'amanite phalloïde' },
      { lang: 'ca', value: 'farinera borda' },
      { lang: 'pl', value: 'muchomor sromotnikowy' },
      { lang: 'pl', value: 'muchomor zielonawy' },
      { lang: 'nb', value: 'grønn fluesopp' },
      { lang: 'sv', value: 'lömsk flugsvamp' },
      { lang: 'sl', value: 'zelena mušnica' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q269345', label: 'lamella' },
    capShape: [{ pid: 'P784', qid: 'Q14544535', label: 'convex mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q14544563', label: 'free hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q19887987', label: 'ring and volva stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q23444', label: 'white' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q19888591', label: 'deadly mushroom' },
      { pid: 'P789', qid: 'Q1686195', label: 'medicinal mushrooms' },
    ],
  },
  media: {
    images: ['Amanita phalloides 1.JPG'],
    commonsCategory: 'Amanita phalloides',
    commonsGallery: 'Amanita phalloides',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '178962' },
    { pid: 'P846', source: 'GBIF', value: '5240325' },
    { pid: 'P962', source: 'MycoBank', value: '178962' },
    { pid: 'P3151', source: 'iNaturalist', value: '52135' },
    { pid: 'P838', source: 'BioLib', value: '60473' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '1009706' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '67723' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '65ZB2' },
  ],
}

export default amanitaPhalloidesQ188643
