// Wikidata data for Cantharellus cibarius (Q188749)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const cantharellusCibariusQ188749: WikidataSpeciesData = {
  slug: 'cantharellus-cibarius',
  wikidataId: 'Q188749',
  taxonomy: {
    taxonName: 'Cantharellus cibarius',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q922335', labels: { en: 'Cantharellus', de: 'Pfifferlinge' } },
    ],
    instanceOf: [
      { pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } },
      { pid: 'P31', qid: 'Q11619941', labels: { en: 'mycorrhizal fungus' } },
    ],
    authorCitation: 'Fr.',
    shortName: 'C. cibarius',
  },
  names: {
    labels: { en: 'Cantharellus cibarius', de: 'Echter Pfifferling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Pfifferlinge (Cantharellus)' },
    aliases: {
      en: ['golden chanterelle mushroom', 'girolle'],
      de: [
        'Reherl',
        'Nagerl',
        'Rehgoaßl',
        'Marillenschwammerl',
        'Eierschwämmli',
        'Pfefferling',
        'Kragenknöpferl',
        'Hühnerpilz',
        'Recherl',
        'Gelbschwammerl',
        'Eierschwammerl',
        'Cantharellus cibarius',
        'Gelbes Hühnel',
        'Koksch',
        'Pfifferling',
        'Eierschwamm',
      ],
    },
    commonNames: [
      { lang: 'cy', value: 'siantrel' },
      { lang: 'zh', value: '雞油菌' },
      { lang: 'nl', value: 'Hanekam' },
      { lang: 'de', value: 'Echter Pfifferling' },
      { lang: 'cs', value: 'liška obecná' },
      { lang: 'fi', value: 'keltavahvero' },
      { lang: 'de-at', value: 'Eierschwammerl' },
      { lang: 'en', value: 'golden chanterelle' },
      { lang: 'nb', value: 'kantarell' },
      { lang: 'zh', value: '鸡油菌' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861551', labels: { en: 'ridges' } },
    capShape: [
      {
        pid: 'P784',
        qid: 'Q19887958',
        labels: { en: 'infundibuliform mushroom cap', de: 'trichterförmig' },
      },
    ],
    hymeniumAttachment: {
      pid: 'P785',
      qid: 'Q19887925',
      labels: { en: 'decurrent hymenium attachment', de: 'Lamellen herablaufend' },
    },
    stipeCharacter: {
      pid: 'P786',
      qid: 'Q14544581',
      labels: { en: 'bare stipe', de: 'ringloser Stiel' },
    },
    sporePrintColor: { pid: 'P787', qid: 'Q943', labels: { en: 'yellow', de: 'Gelb' } },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q99974', labels: { en: 'mycorrhiza', de: 'Mykorrhiza' } },
    ],
  },
  edibility: {
    values: [
      {
        pid: 'P789',
        qid: 'Q19888517',
        labels: { en: 'choice mushroom', de: 'hervorragender Speisepilz' },
      },
      { pid: 'P789', qid: 'Q654236', labels: { en: 'edible mushroom', de: 'Speisepilz' } },
      { pid: 'P789', qid: 'Q1686195', labels: { en: 'medicinal mushrooms', de: 'Mykotherapie' } },
    ],
  },
  media: {
    images: ['Chanterelle Cantharellus cibarius.jpg'],
    commonsCategory: 'Cantharellus cibarius',
    commonsGallery: 'Cantharellus cibarius',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '200345',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=200345',
    },
    { pid: 'P846', source: 'GBIF', value: '5249504', url: 'https://www.gbif.org/species/5249504' },
    { pid: 'P962', source: 'MycoBank', value: '200345', url: 'https://www.mycobank.org/MB/200345' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '47347',
      url: 'https://inaturalist.org/taxa/47347',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '59853',
      url: 'https://www.biolib.cz/cz/taxon/id59853',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '6666298',
      url: 'https://eol.org/pages/6666298',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '36066',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/36066',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: 'QMKY',
      url: 'https://www.catalogueoflife.org/data/taxon/QMKY',
    },
  ],
}

export default cantharellusCibariusQ188749
