// Wikidata data for Cantharellus cibarius (Q188749)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const cantharellusCibariusQ188749: WikidataSpeciesData = {
  slug: 'cantharellus-cibarius',
  wikidataId: 'Q188749',
  taxonomy: {
    taxonName: 'Cantharellus cibarius',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q922335', label: 'Cantharellus' }],
    instanceOf: [
      { pid: 'P31', qid: 'Q16521', label: 'taxon' },
      { pid: 'P31', qid: 'Q11619941', label: 'mycorrhizal fungus' },
    ],
    authorCitation: 'Fr.',
    shortName: 'C. cibarius',
  },
  names: {
    labels: { en: 'Cantharellus cibarius', de: 'Echter Pfifferling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Pfifferlinge (Cantharellus)' },
    aliases: {
      en: ['golden chanterelle mushroom', 'girolle'],
      de: [
        'Reherl',
        'Nagerl',
        'Rehgoaßl',
        'Marillenschwammerl',
        'Eierschwämmli',
        'Pfefferling',
        'Kragenknöpferl',
        'Hühnerpilz',
        'Recherl',
        'Gelbschwammerl',
        'Eierschwammerl',
        'Cantharellus cibarius',
        'Gelbes Hühnel',
        'Koksch',
        'Pfifferling',
        'Eierschwamm',
      ],
    },
    commonNames: [
      { lang: 'cy', value: 'siantrel' },
      { lang: 'zh', value: '雞油菌' },
      { lang: 'nl', value: 'Hanekam' },
      { lang: 'de', value: 'Echter Pfifferling' },
      { lang: 'cs', value: 'liška obecná' },
      { lang: 'fi', value: 'keltavahvero' },
      { lang: 'de-at', value: 'Eierschwammerl' },
      { lang: 'en', value: 'golden chanterelle' },
      { lang: 'nb', value: 'kantarell' },
      { lang: 'zh', value: '鸡油菌' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861551', label: 'ridges' },
    capShape: [{ pid: 'P784', qid: 'Q19887958', label: 'infundibuliform mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887925', label: 'decurrent hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q14544581', label: 'bare stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q943', label: 'yellow' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q19888517', label: 'choice mushroom' },
      { pid: 'P789', qid: 'Q654236', label: 'edible mushroom' },
      { pid: 'P789', qid: 'Q1686195', label: 'medicinal mushrooms' },
    ],
  },
  media: {
    images: ['Chanterelle Cantharellus cibarius.jpg'],
    commonsCategory: 'Cantharellus cibarius',
    commonsGallery: 'Cantharellus cibarius',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '200345' },
    { pid: 'P846', source: 'GBIF', value: '5249504' },
    { pid: 'P962', source: 'MycoBank', value: '200345' },
    { pid: 'P3151', source: 'iNaturalist', value: '47347' },
    { pid: 'P838', source: 'BioLib', value: '59853' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '6666298' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '36066' },
    { pid: 'P10585', source: 'Catalogue of Life', value: 'QMKY' },
  ],
}

export default cantharellusCibariusQ188749
