// Wikidata data for Panellus Mitis (Q1934540)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const panellusMitisQ1934540: WikidataSpeciesData = {
  slug: 'panellus-mitis',
  wikidataId: 'Q1934540',
  taxonomy: {
    taxonName: 'Panellus mitis',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q244201', labels: { en: 'Panellus', de: 'Zwergknäuelinge' } },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      { pid: 'P566', qid: 'Q59548631', labels: { en: 'Agaricus mitis', de: 'Agaricus mitis' } },
    ],
    authorCitation: '(Pers.) Singer',
    shortName: 'P. mitis',
  },
  names: {
    labels: { en: 'Panellus mitis', de: 'Milder Zwergknäueling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Zwergknäuelinge (Panellus)' },
    aliases: { de: ['Panellus mitis'] },
    commonNames: [
      { lang: 'cy', value: 'corwystrysen hydwyth' },
      { lang: 'nl', value: 'Denneschelpzwam' },
      { lang: 'cs', value: 'pařezník jemný' },
      { lang: 'fi', value: 'pikkuvinokas' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: ['2007-02-23 Panellus mitis 2.tif'],
    commonsCategory: 'Panellus mitis',
    commonsGallery: 'Panellus mitis',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '271415',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=271415',
    },
    { pid: 'P846', source: 'GBIF', value: '8931746', url: 'https://www.gbif.org/species/8931746' },
    { pid: 'P962', source: 'MycoBank', value: '271415', url: 'https://www.mycobank.org/MB/271415' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '351676',
      url: 'https://inaturalist.org/taxa/351676',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '126044',
      url: 'https://www.biolib.cz/cz/taxon/id126044',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '189596',
      url: 'https://eol.org/pages/189596',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '148590',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/148590',
    },
  ],
}

export default panellusMitisQ1934540
