// Wikidata data for Boletus edulis (Q19740)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const boletusEdulisQ19740: WikidataSpeciesData = {
  slug: 'boletus-edulis',
  wikidataId: 'Q19740',
  taxonomy: {
    taxonName: 'Boletus edulis',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [
      { pid: 'P171', qid: 'Q142945', label: 'Boletus sect. Boletus' },
      { pid: 'P171', qid: 'Q19744', label: 'Boletus' },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    authorCitation: 'Bull.',
    shortName: 'B. edulis',
  },
  names: {
    labels: { en: 'Boletus edulis', de: 'Gemeiner Steinpilz' },
    descriptions: { en: 'species of fungus', de: 'Art in der Klasse Agaricomycetes' },
    aliases: {
      en: [
        'porcino',
        'bollo de centavo',
        'boletus',
        'champiñón',
        'cep',
        'penny bun',
        'porcini',
        'porcinis',
        'cèpe',
        'porcini mushroom',
      ],
      de: ['Fichten-Steinpilz', 'Herrenpilz', 'Edelpilz', 'Boletus edulis'],
    },
    commonNames: [
      { lang: 'cy', value: 'wicsen gron' },
      { lang: 'zh', value: '美味牛肝菌' },
      { lang: 'nl', value: 'Gewoon eekhoorntjesbrood' },
      { lang: 'en', value: 'cep' },
      { lang: 'cs', value: 'hřib smrkový' },
      { lang: 'fi', value: 'herkkutatti' },
      { lang: 'sl', value: 'jesenski goban' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861549', label: 'pores' },
    capShape: [{ pid: 'P784', qid: 'Q14544535', label: 'convex mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q14544569', label: 'adnate hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q14544581', label: 'bare stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q47071', label: 'brown' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q19888517', label: 'choice mushroom' },
      { pid: 'P789', qid: 'Q654236', label: 'edible mushroom' },
    ],
    conservationStatus: [{ pid: 'P141', qid: 'Q211005', label: 'least concern' }],
  },
  media: {
    images: ['(Gemeine Steinpilz) Boletus edulis.jpg'],
    commonsCategory: 'Boletus edulis',
    commonsGallery: 'Boletus edulis',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '356530' },
    { pid: 'P846', source: 'GBIF', value: '5954958' },
    { pid: 'P962', source: 'MycoBank', value: '356530' },
    { pid: 'P3151', source: 'iNaturalist', value: '48701' },
    { pid: 'P838', source: 'BioLib', value: '60135' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '195761' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '36056' },
    { pid: 'P10585', source: 'Catalogue of Life', value: 'MCH9' },
  ],
}

export default boletusEdulisQ19740
