// Wikidata data for Pseudohydnum gelatinosum (Q206711)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const pseudohydnumGelatinosumQ206711: WikidataSpeciesData = {
  slug: 'pseudohydnum-gelatinosum',
  wikidataId: 'Q206711',
  taxonomy: {
    taxonName: 'Pseudohydnum gelatinosum',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q7254872', label: 'Pseudohydnum' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q54370181', label: 'Hydnum gelatinosum' }],
    authorCitation: '(Scop.) P.Karst.',
    shortName: 'P. gelatinosum',
  },
  names: {
    labels: { en: 'Pseudohydnum gelatinosum', de: 'Zitterzahn' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Pseudohydnum' },
    commonNames: [
      { lang: 'cy', value: 'tafod jeli' },
      { lang: 'zh', value: '虎掌假齒菌' },
      { lang: 'nl', value: 'Stekeltrilzwam' },
      { lang: 'cs', value: 'rosolozub huspenitý' },
      { lang: 'fi', value: 'orahytykkä' },
      { lang: 'zh', value: '虎掌刺银耳' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861552', label: 'teeth' },
    capShape: [{ pid: 'P784', qid: 'Q19887955', label: 'depressed mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887925', label: 'decurrent hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q14544581', label: 'bare stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q23444', label: 'white' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q114750', label: 'saprobiont' }],
  },
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q654236', label: 'edible mushroom' },
      { pid: 'P789', qid: 'Q1686195', label: 'medicinal mushrooms' },
    ],
  },
  media: {
    images: ['Pseudohydnum gelatinosum.jpg'],
    commonsCategory: 'Pseudohydnum gelatinosum',
    commonsGallery: 'Pseudohydnum gelatinosum',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '120525' },
    { pid: 'P846', source: 'GBIF', value: '5249353' },
    { pid: 'P962', source: 'MycoBank', value: '120525' },
    { pid: 'P3151', source: 'iNaturalist', value: '54164' },
    { pid: 'P838', source: 'BioLib', value: '59805' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '133565' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '29895' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '4NYCM' },
  ],
}

export default pseudohydnumGelatinosumQ206711
