// Wikidata data for Cordyceps militaris (Q2118699)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const cordycepsMilitarisQ2118699: WikidataSpeciesData = {
  slug: 'cordyceps-militaris',
  wikidataId: 'Q2118699',
  taxonomy: {
    taxonName: 'Cordyceps militaris',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q312238', label: 'Cordyceps' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q21872391', label: 'Clavaria militaris' }],
    shortName: 'C. militaris',
  },
  names: {
    labels: { en: 'Cordyceps militaris', de: 'Puppen-Kernkeule' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Cordyceps' },
    aliases: { de: ['Cordyceps militaris', 'Puppenkernkeule'] },
    commonNames: [
      { lang: 'cy', value: 'pastwn coch y lindys' },
      { lang: 'zh', value: '蛹蟲草' },
      { lang: 'nl', value: 'Rupsendoder' },
      { lang: 'cs', value: 'housenice červená' },
      { lang: 'fi', value: 'punaloisikka' },
      { lang: 'sl', value: 'kokonov glavatec' },
      { lang: 'zh', value: '蛹虫草' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q1686195', label: 'medicinal mushrooms' },
      { pid: 'P789', qid: 'Q654236', label: 'edible mushroom' },
    ],
  },
  media: {
    images: ['Puppenkernkeule.jpg'],
    commonsCategory: 'Cordyceps militaris',
    commonsGallery: 'Cordyceps militaris',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '237604' },
    { pid: 'P846', source: 'GBIF', value: '7567077' },
    { pid: 'P962', source: 'MycoBank', value: '237604' },
    { pid: 'P3151', source: 'iNaturalist', value: '119118' },
    { pid: 'P838', source: 'BioLib', value: '300329' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '188679' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '73501' },
    { pid: 'P10585', source: 'Catalogue of Life', value: 'YCG6' },
  ],
}

export default cordycepsMilitarisQ2118699
