// Wikidata data for Dacrymyces chrysospermus (Q2152361)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const dacrymycesChrysopermusQ2152361: WikidataSpeciesData = {
  slug: 'dacrymyces-chrysopermus',
  wikidataId: 'Q2152361',
  taxonomy: {
    taxonName: 'Dacrymyces chrysospermus',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q1331136', labels: { en: 'Dacrymyces', de: 'Gallerttränen' } },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    authorCitation: 'Berk. & M.A.Curtis',
    shortName: 'D. chrysospermus',
  },
  names: {
    labels: { en: 'Dacrymyces chrysospermus', de: 'Dacrymyces chrysospermus' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Gallerttränen (Dacrymyces)' },
    aliases: { de: ['Dacrymyces palmatus', 'Riesen-Gallertträne'] },
    commonNames: [
      { lang: 'cy', value: 'smotiau jeli melynfrown' },
      { lang: 'zh', value: '掌狀花耳' },
      { lang: 'cs', value: 'kropilka mozkovitá' },
      { lang: 'fi', value: 'kultatipakka' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: ['Dacrymyces palmatus on a log.JPG'],
    commonsCategory: 'Dacrymyces chrysospermus',
    commonsGallery: 'Dacrymyces chrysospermus',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '141916',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=141916',
    },
    { pid: 'P846', source: 'GBIF', value: '2512921', url: 'https://www.gbif.org/species/2512921' },
    { pid: 'P962', source: 'MycoBank', value: '141916', url: 'https://www.mycobank.org/MB/141916' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '118028',
      url: 'https://inaturalist.org/taxa/118028',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '344218',
      url: 'https://www.biolib.cz/cz/taxon/id344218',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '1030838',
      url: 'https://eol.org/pages/1030838',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '29886',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/29886',
    },
  ],
}

export default dacrymycesChrysopermusQ2152361
