// Wikidata data for Hygrocybe acutoconica (Q2255842)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const hygrocybeAcutoconicaQ2255842: WikidataSpeciesData = {
  slug: 'hygrocybe-acutoconica',
  wikidataId: 'Q2255842',
  taxonomy: {
    taxonName: 'Hygrocybe acutoconica',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q520530', labels: { en: 'Hygrocybe', de: 'Saftlinge' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      {
        pid: 'P566',
        qid: 'Q59511617',
        labels: { en: 'Mycena acutoconica', de: 'Mycena acutoconica' },
      },
    ],
    authorCitation: '(Clem.) Singer',
    shortName: 'H. acutoconica',
  },
  names: {
    labels: { en: 'Hygrocybe acutoconica', de: 'Hygrocybe acutoconica' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Saftlinge (Hygrocybe)' },
    commonNames: [
      { lang: 'cy', value: 'cap cŵyr parhaol' },
      { lang: 'nl', value: 'Puntmutswasplaat' },
      { lang: 'cs', value: 'voskovka zašpičatělá' },
      { lang: 'fi', value: 'suippuvahakas' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: ['Hygrocybe persistens persistens.jpg'],
    commonsCategory: 'Hygrocybe acutoconica',
    commonsGallery: 'Hygrocybe acutoconica',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '298654',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=298654',
    },
    { pid: 'P846', source: 'GBIF', value: '3345237', url: 'https://www.gbif.org/species/3345237' },
    { pid: 'P962', source: 'MycoBank', value: '298654', url: 'https://www.mycobank.org/MB/298654' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '367288',
      url: 'https://inaturalist.org/taxa/367288',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '60248',
      url: 'https://www.biolib.cz/cz/taxon/id60248',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '6676612',
      url: 'https://eol.org/pages/6676612',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '1329068',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/1329068',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '3NB37',
      url: 'https://www.catalogueoflife.org/data/taxon/3NB37',
    },
  ],
}

export default hygrocybeAcutoconicaQ2255842
