// Wikidata data for Rubroboletus rhodoxanthus (Q26203742)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const rubroboletusRhodoxanthusQ26203742: WikidataSpeciesData = {
  slug: 'rubroboletus-rhodoxanthus',
  wikidataId: 'Q26203742',
  taxonomy: {
    taxonName: 'Rubroboletus rhodoxanthus',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q19299411', label: 'Rubroboletus' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q108571820', label: 'Boletus sanguineus var. rhodoxanthus' }],
    authorCitation: '(Krombh.) Kuan Zhao & Zhu L. Yang',
    shortName: 'R. rhodoxanthus',
  },
  names: {
    labels: { en: 'Rubroboletus rhodoxanthus', de: 'Rubroboletus rhodoxanthus' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Rubroboletus' },
    aliases: { de: ['Blasshütiger Purpur-Röhrling'] },
    commonNames: [
      { lang: 'cy', value: 'cap tyllog rhosgoch' },
      { lang: 'nl', value: 'Roodnetboleet' },
      { lang: 'cs', value: 'hřib nachový' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861549', label: 'pores' },
    capShape: [{ pid: 'P784', qid: 'Q62023127', label: 'semi-spherical mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887932', label: 'no hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q131915205', label: 'reticulate' },
    sporePrintColor: { pid: 'P787', qid: 'Q19888352', label: 'olive brown' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [{ pid: 'P789', qid: 'Q359511', label: 'poisonous mushroom' }],
    conservationStatus: [{ pid: 'P141', qid: 'Q719675', label: 'near threatened' }],
  },
  media: {
    images: ['Boletus rhodoxanthus.JPG'],
    commonsCategory: 'Rubroboletus rhodoxanthus',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '809243' },
    { pid: 'P846', source: 'GBIF', value: '7487519' },
    { pid: 'P962', source: 'MycoBank', value: '809243' },
    { pid: 'P3151', source: 'iNaturalist', value: '824010' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '178457' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '6X9KP' },
  ],
}

export default rubroboletusRhodoxanthusQ26203742
