// Wikidata data for Butyriboletus appendiculatus (Q26203735)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const butyriboletusAppendiculatusQ26203735: WikidataSpeciesData = {
  slug: 'butyriboletus-appendiculatus',
  wikidataId: 'Q26203735',
  taxonomy: {
    taxonName: 'Butyriboletus appendiculatus',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q17311833', label: 'Butyriboletus' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q545849', label: 'Boletus appendiculatus' }],
    authorCitation: '(Schaeff.) D. Arora & J.L. Frank',
    shortName: 'B. appendiculatus',
  },
  names: {
    labels: { en: 'Butyriboletus appendiculatus', de: 'Anhängsel-Röhrling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Butyriboletus' },
    aliases: {
      de: [
        'Butyriboletus appendiculatus',
        'Gelber Bronze-Röhrling',
        'Gelber Steinpilz',
        'Gelber Bronzeröhrling',
      ],
    },
    commonNames: [
      { lang: 'cy', value: 'cap tyllog derw' },
      { lang: 'nl', value: 'Geelnetboleet' },
      { lang: 'fi', value: 'keltajalkatatti' },
      { lang: 'cs', value: 'hřib přívěskatý' },
      { lang: 'de', value: 'Gelber Bronzeröhrling' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861549', label: 'pores' },
    capShape: [{ pid: 'P784', qid: 'Q14544535', label: 'convex mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q14544569', label: 'adnate hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q14544581', label: 'bare stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q864152', label: 'olive' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [{ pid: 'P789', qid: 'Q654236', label: 'edible mushroom' }],
  },
  media: {
    images: ['Boletus appendiculatus.jpg'],
    commonsCategory: 'Butyriboletus appendiculatus',
    commonsGallery: 'Butyriboletus appendiculatus',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '803319' },
    { pid: 'P846', source: 'GBIF', value: '8250249' },
    { pid: 'P962', source: 'MycoBank', value: '803319' },
    { pid: 'P3151', source: 'iNaturalist', value: '372726' },
    { pid: 'P838', source: 'BioLib', value: '60128' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '182627' },
    { pid: 'P10585', source: 'Catalogue of Life', value: 'NZ7L' },
  ],
}

export default butyriboletusAppendiculatusQ26203735
