// Wikidata data for Sarcodon imbricatus (Q262105)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const sarcondonImbricatusQ262105: WikidataSpeciesData = {
  slug: 'sarcondon-imbricatus',
  wikidataId: 'Q262105',
  taxonomy: {
    taxonName: 'Sarcodon imbricatus',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q902135', label: 'Sarcodon' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q21874616', label: 'Hydnum imbricatum' }],
    shortName: 'S. imbricatus',
  },
  names: {
    labels: { en: 'Sarcodon imbricatus', de: 'Habichtspilz' },
    descriptions: {
      en: 'species of fungus',
      de: 'Art der Gattung Braunsporstachelinge (Sarcodon)',
    },
    aliases: { en: ['Scaly tooth'] },
    commonNames: [
      { lang: 'en', value: 'Scaly tooth' },
      { lang: 'zh', value: '疊蓋肉齒菌' },
      { lang: 'cs', value: 'lošák jelení' },
      { lang: 'fi', value: 'kuusensuomuorakas' },
      { lang: 'ast', value: "pelleyu l'osu" },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861552', label: 'teeth' },
    capShape: [{ pid: 'P784', qid: 'Q19887957', label: 'flat mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q14544569', label: 'adnate hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q14544581', label: 'bare stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q47071', label: 'brown' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [{ pid: 'P789', qid: 'Q654236', label: 'edible mushroom' }],
  },
  media: {
    images: ['Habichtspilz-Sarcodon-imbricatus.jpg'],
    commonsCategory: 'Sarcodon imbricatus',
    commonsGallery: 'Sarcodon imbricatus',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '414481' },
    { pid: 'P846', source: 'GBIF', value: '5238865' },
    { pid: 'P962', source: 'MycoBank', value: '414481' },
    { pid: 'P3151', source: 'iNaturalist', value: '122335' },
    { pid: 'P838', source: 'BioLib', value: '60635' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '1007251' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '57136' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '6XLRR' },
  ],
}

export default sarcondonImbricatusQ262105
