// Wikidata data for Guepinia helvelloides (Q26678323)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const guepiniaHelvelloidesQ26678323: WikidataSpeciesData = {
  slug: 'guepinia-helvelloides',
  wikidataId: 'Q26678323',
  taxonomy: {
    taxonName: 'Guepinia helvelloides',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q5614843', labels: { en: 'Guepinia', de: 'Guepinia' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      {
        pid: 'P566',
        qid: 'Q26678308',
        labels: { en: 'Tremella helvelloides', de: 'Tremella helvelloides' },
      },
    ],
    shortName: 'G. helvelloides',
  },
  names: {
    labels: { en: 'Guepinia helvelloides', de: 'Guepinia helvelloides' },
    descriptions: { en: 'species of Agaricomycetes', de: 'Art der Gattung Guepinia' },
    commonNames: [
      { lang: 'fi', value: 'suppilohytykkä' },
      { lang: 'zh', value: '焰耳' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [{ pid: 'P789', qid: 'Q654236', labels: { en: 'edible mushroom', de: 'Speisepilz' } }],
  },
  media: {
    images: [],
  },
  externalIds: [
    { pid: 'P846', source: 'GBIF', value: '5249355', url: 'https://www.gbif.org/species/5249355' },
    { pid: 'P962', source: 'MycoBank', value: '189772', url: 'https://www.mycobank.org/MB/189772' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '348814',
      url: 'https://inaturalist.org/taxa/348814',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '160928',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/160928',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '6L5F9',
      url: 'https://www.catalogueoflife.org/data/taxon/6L5F9',
    },
  ],
}

export default guepiniaHelvelloidesQ26678323
