// Wikidata data for Coprinopsis nivea (Q28492325)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const coprinopsisNiveaQ28492325: WikidataSpeciesData = {
  slug: 'coprinopsis-nivea',
  wikidataId: 'Q28492325',
  taxonomy: {
    taxonName: 'Coprinopsis nivea',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q2253036', labels: { en: 'Coprinopsis', de: 'Coprinopsis' } },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      {
        pid: 'P566',
        qid: 'Q63033721',
        labels: { en: 'Agaricus niveus', de: 'Agaricus niveus Pers. (1801)' },
      },
    ],
    authorCitation: '(Pers.) Redhead, Vilgalys & Moncalvo (2001)',
    shortName: 'C. nivea',
  },
  names: {
    labels: { en: 'Coprinopsis nivea', de: 'Coprinopsis nivea' },
    descriptions: { en: 'species of Agaricomycetes', de: 'Art der Gattung Coprinopsis' },
    commonNames: [
      { lang: 'fi', value: 'valkomustesieni' },
      { lang: 'cy', value: 'cap inc claerwyn' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q269345', labels: { en: 'lamella', de: 'Lamelle' } },
    hymeniumAttachment: {
      pid: 'P785',
      qid: 'Q19887923',
      labels: { en: 'adnexed hymenium attachment' },
    },
    stipeCharacter: {
      pid: 'P786',
      qid: 'Q14544581',
      labels: { en: 'bare stipe', de: 'ringloser Stiel' },
    },
    sporePrintColor: { pid: 'P787', qid: 'Q23445', labels: { en: 'black', de: 'schwarz' } },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q114750', labels: { en: 'saprobiont', de: 'Saprobiont' } },
    ],
  },
  edibility: {
    values: [{ pid: 'P789', qid: 'Q654236', labels: { en: 'edible mushroom', de: 'Speisepilz' } }],
  },
  media: {
    images: ['Schneeweisse Tintlinge.jpg'],
    commonsCategory: 'Coprinopsis nivea',
    commonsGallery: 'Coprinopsis nivea',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '474625',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=474625',
    },
    { pid: 'P846', source: 'GBIF', value: '5242773', url: 'https://www.gbif.org/species/5242773' },
    { pid: 'P962', source: 'MycoBank', value: '474625', url: 'https://www.mycobank.org/MB/474625' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '348091',
      url: 'https://inaturalist.org/taxa/348091',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '343226',
      url: 'https://www.biolib.cz/cz/taxon/id343226',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '989831',
      url: 'https://eol.org/pages/989831',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '76938',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/76938',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: 'Y598',
      url: 'https://www.catalogueoflife.org/data/taxon/Y598',
    },
  ],
}

export default coprinopsisNiveaQ28492325
