// Wikidata data for Caloboletus calopus (Q29784429)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const caloboletusCalopusQ29784429: WikidataSpeciesData = {
  slug: 'caloboletus-calopus',
  wikidataId: 'Q29784429',
  taxonomy: {
    taxonName: 'Caloboletus calopus',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q19277034', label: 'Caloboletus' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q1137151', label: 'Boletus calopus' }],
    authorCitation: '(Pers.) Vizzini',
    shortName: 'C. calopus',
  },
  names: {
    labels: { en: 'Caloboletus calopus', de: 'Schönfuß-Röhrling' },
    descriptions: { en: 'species of fungi', de: 'Art der Gattung Caloboletus' },
    aliases: {
      en: ['Bitter Beech Bolete', 'Scarlet-stemmed Bolete'],
      de: ['Dickfußröhrling', 'Schönfußröhrling', 'Caloboletus calopus', 'Schönfußröhrlinge'],
    },
    commonNames: [
      { lang: 'cy', value: 'cap tyllog chwerw' },
      { lang: 'cs', value: 'hřib kříšť' },
      { lang: 'de', value: 'Schönfußröhrlinge' },
      { lang: 'et', value: 'Mõhk-kivipuravik' },
      { lang: 'hu', value: 'Farkastinóru' },
      { lang: 'zh', value: '美柄牛肝菌' },
      { lang: 'fi', value: 'kaunojalkatatti' },
      { lang: 'nb', value: 'besk rørsopp' },
      { lang: 'sl', value: 'leponogi postavnež' },
      { lang: 'zh', value: '丽柄牛肝菌' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861549', label: 'pores' },
    capShape: [{ pid: 'P784', qid: 'Q14544535', label: 'convex mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887932', label: 'no hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q14544581', label: 'bare stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q19888352', label: 'olive brown' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q4317894', label: 'inedible mushroom' },
      { pid: 'P789', qid: 'Q19888537', label: 'caution mushroom' },
    ],
  },
  media: {
    images: ['Schoenfussroehrling.jpg'],
    commonsCategory: 'Caloboletus calopus',
    commonsGallery: 'Caloboletus calopus',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '550547' },
    { pid: 'P846', source: 'GBIF', value: '8203051' },
    { pid: 'P962', source: 'MycoBank', value: '550547' },
    { pid: 'P3151', source: 'iNaturalist', value: '701434' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '141855' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '5X7DN' },
  ],
}

export default caloboletusCalopusQ29784429
