// Wikidata data for Auricularia auricula-judae (Q321342)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const auriculariaAuriculaJudaeQ321342: WikidataSpeciesData = {
  slug: 'auricularia-auricula-judae',
  wikidataId: 'Q321342',
  taxonomy: {
    taxonName: 'Auricularia auricula-judae',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q1633488', labels: { en: 'Auricularia', de: 'Ohrlappenpilze' } },
    ],
    instanceOf: [
      { pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } },
      { pid: 'P31', qid: 'Q76749327', labels: { en: 'cultivated mushroom', de: 'Kulturpilz' } },
    ],
    basionym: [
      {
        pid: 'P566',
        qid: 'Q64667999',
        labels: { en: 'Tremella auricula-judae', de: 'Tremella auricula-judae' },
      },
    ],
    shortName: 'A. auricula-judae',
  },
  names: {
    labels: { en: 'Auricularia auricula-judae', de: 'Judasohr' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Ohrlappenpilze (Auricularia)' },
    aliases: {
      en: [
        'wood ear',
        "Jew's ear",
        'jelly ear',
        'ear fungus',
        'common ear fungus',
        'black wood ear',
        'Wood Ear',
      ],
      de: [
        'Mu Err',
        'Wolkenohrenpilz',
        'Holunderschwamm',
        'Mu-Err-Pilz',
        'Mu-Err',
        'Auricularia auricula-judae',
        'Ohrlappenpilz',
        'Holzohr',
        'Mu-Err-Pilze',
      ],
    },
    commonNames: [
      { lang: 'cy', value: "clustiau'r ysgaw" },
      { lang: 'cs', value: 'ucho Jidášovo' },
      { lang: 'ru', value: 'Иудины уши' },
      { lang: 'de', value: 'Judasohr' },
      { lang: 'mk', value: 'Јудино уво' },
      { lang: 'sl', value: 'bezgova uhljevka' },
    ],
  },
  morphology: {
    sporePrintColor: { pid: 'P787', qid: 'Q23444', labels: { en: 'white', de: 'Weiß' } },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q114750', labels: { en: 'saprobiont', de: 'Saprobiont' } },
      { pid: 'P788', qid: 'Q186517', labels: { en: 'parasitism', de: 'Parasitismus' } },
    ],
  },
  edibility: {
    values: [{ pid: 'P789', qid: 'Q654236', labels: { en: 'edible mushroom', de: 'Speisepilz' } }],
  },
  media: {
    images: ['Auricularia auricula-judae (xndr).jpg'],
    commonsCategory: 'Auricularia auricula-judae',
    commonsGallery: 'Auricularia auricula-judae',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '102281',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=102281',
    },
    { pid: 'P846', source: 'GBIF', value: '5249271', url: 'https://www.gbif.org/species/5249271' },
    { pid: 'P962', source: 'MycoBank', value: '102281', url: 'https://www.mycobank.org/MB/102281' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '50813',
      url: 'https://inaturalist.org/taxa/50813',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '59817',
      url: 'https://www.biolib.cz/cz/taxon/id59817',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '152249',
      url: 'https://eol.org/pages/152249',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '29892',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/29892',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '5W9WJ',
      url: 'https://www.catalogueoflife.org/data/taxon/5W9WJ',
    },
  ],
}

export default auriculariaAuriculaJudaeQ321342
