// Wikidata data for Auricularia auricula-judae (Q321342)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const auriculariaAuriculaJudaeQ321342: WikidataSpeciesData = {
  slug: 'auricularia-auricula-judae',
  wikidataId: 'Q321342',
  taxonomy: {
    taxonName: 'Auricularia auricula-judae',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q1633488', label: 'Auricularia' }],
    instanceOf: [
      { pid: 'P31', qid: 'Q16521', label: 'taxon' },
      { pid: 'P31', qid: 'Q76749327', label: 'cultivated mushroom' },
    ],
    basionym: [{ pid: 'P566', qid: 'Q64667999', label: 'Tremella auricula-judae' }],
    shortName: 'A. auricula-judae',
  },
  names: {
    labels: { en: 'Auricularia auricula-judae', de: 'Judasohr' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Ohrlappenpilze (Auricularia)' },
    aliases: {
      en: [
        'wood ear',
        "Jew's ear",
        'jelly ear',
        'ear fungus',
        'common ear fungus',
        'black wood ear',
        'Wood Ear',
      ],
      de: [
        'Mu Err',
        'Wolkenohrenpilz',
        'Holunderschwamm',
        'Mu-Err-Pilz',
        'Mu-Err',
        'Auricularia auricula-judae',
        'Ohrlappenpilz',
        'Holzohr',
        'Mu-Err-Pilze',
      ],
    },
    commonNames: [
      { lang: 'cy', value: "clustiau'r ysgaw" },
      { lang: 'cs', value: 'ucho Jidášovo' },
      { lang: 'ru', value: 'Иудины уши' },
      { lang: 'de', value: 'Judasohr' },
      { lang: 'mk', value: 'Јудино уво' },
      { lang: 'sl', value: 'bezgova uhljevka' },
    ],
  },
  morphology: {
    sporePrintColor: { pid: 'P787', qid: 'Q23444', label: 'white' },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q114750', label: 'saprobiont' },
      { pid: 'P788', qid: 'Q186517', label: 'parasitism' },
    ],
  },
  edibility: {
    values: [{ pid: 'P789', qid: 'Q654236', label: 'edible mushroom' }],
  },
  media: {
    images: ['Auricularia auricula-judae (xndr).jpg'],
    commonsCategory: 'Auricularia auricula-judae',
    commonsGallery: 'Auricularia auricula-judae',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '102281' },
    { pid: 'P846', source: 'GBIF', value: '5249271' },
    { pid: 'P962', source: 'MycoBank', value: '102281' },
    { pid: 'P3151', source: 'iNaturalist', value: '50813' },
    { pid: 'P838', source: 'BioLib', value: '59817' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '152249' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '29892' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '5W9WJ' },
  ],
}

export default auriculariaAuriculaJudaeQ321342
