// Wikidata data for Albatrellus ovinus (Q331465)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const albatrellusOvinusQ331465: WikidataSpeciesData = {
  slug: 'albatrellus-ovinus',
  wikidataId: 'Q331465',
  taxonomy: {
    taxonName: 'Albatrellus ovinus',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q1073187', label: 'Albatrellus' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q59419388', label: 'Boletus ovinus' }],
    authorCitation: '(Schaeff.) Kotl. & Pouzar (1957)',
    shortName: 'A. ovinus',
  },
  names: {
    labels: { en: 'Albatrellus ovinus', de: 'Schaf-Porling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Schafporlinge (Albatrellus)' },
    aliases: { en: ['forest lamb', 'sheep polypore'], de: ['Schafporling', 'Albatrellus ovinus'] },
    commonNames: [
      { lang: 'cs', value: 'krásnopórka mlynářka' },
      { lang: 'fi', value: 'lampaankääpä' },
      { lang: 'de', value: 'Schafporling' },
      { lang: 'sl', value: 'ovčji mesnatovec' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861549', label: 'pores' },
    capShape: [{ pid: 'P784', qid: 'Q14544535', label: 'convex mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887925', label: 'decurrent hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q14544581', label: 'bare stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q23444', label: 'white' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [{ pid: 'P789', qid: 'Q654236', label: 'edible mushroom' }],
  },
  media: {
    images: ['Schaf-Porling Albatrellus ovinus.jpg'],
    commonsCategory: 'Albatrellus ovinus',
    commonsGallery: 'Albatrellus ovinus',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '292351' },
    { pid: 'P846', source: 'GBIF', value: '2551823' },
    { pid: 'P962', source: 'MycoBank', value: '292351' },
    { pid: 'P3151', source: 'iNaturalist', value: '123891' },
    { pid: 'P838', source: 'BioLib', value: '59889' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '190125' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '139090' },
    { pid: 'P10585', source: 'Catalogue of Life', value: 'BFM3' },
  ],
}

export default albatrellusOvinusQ331465
