// Wikidata data for Craterellus tubaeformis (Q371126)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const craterellusTubaeformisQ371126: WikidataSpeciesData = {
  slug: 'craterellus-tubaeformis',
  wikidataId: 'Q371126',
  taxonomy: {
    taxonName: 'Craterellus tubaeformis',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q2097845', label: 'Craterellus' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q105050279', label: 'Cantharellus tubaeformis' }],
    authorCitation: '(Fr.) Quél.',
    shortName: 'C. tubaeformis',
  },
  names: {
    labels: { en: 'Craterellus tubaeformis', de: 'Trompetenpfifferling' },
    descriptions: {
      en: 'Edible mushroom growing in temperate regions',
      de: 'Art der Gattung Kraterellen (Craterellus)',
    },
    aliases: {
      en: ['yellowfoot', 'funnel chanterelle', 'winter mushroom', 'Craterellus tubiformis'],
      de: ['Trompeten-Pfifferling', 'Craterellus tubaeformis'],
    },
    commonNames: [
      { lang: 'cs', value: 'liška nálevkovitá' },
      { lang: 'fi', value: 'suppilovahvero' },
      { lang: 'de', value: 'Trompeten-Pfifferling' },
      { lang: 'zh', value: '管形喇叭菌' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861551', label: 'ridges' },
    capShape: [{ pid: 'P784', qid: 'Q19887958', label: 'infundibuliform mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887925', label: 'decurrent hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q14544581', label: 'bare stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q2730433', label: 'cream' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q114750', label: 'saprobiont' }],
  },
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q19888517', label: 'choice mushroom' },
      { pid: 'P789', qid: 'Q654236', label: 'edible mushroom' },
    ],
  },
  media: {
    images: ['Cantharellus tubaeformis G28.JPG'],
    commonsCategory: 'Craterellus tubaeformis',
    commonsGallery: 'Craterellus tubaeformis',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '455453' },
    { pid: 'P846', source: 'GBIF', value: '2554536' },
    { pid: 'P962', source: 'MycoBank', value: '455453' },
    { pid: 'P3151', source: 'iNaturalist', value: '350511' },
    { pid: 'P838', source: 'BioLib', value: '59857' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '11446829' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '57200' },
    { pid: 'P10585', source: 'Catalogue of Life', value: 'Z8TV' },
  ],
}

export default craterellusTubaeformisQ371126
