// Wikidata data for Craterellus tubaeformis (Q371126)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const craterellusTubaeformisQ371126: WikidataSpeciesData = {
  slug: 'craterellus-tubaeformis',
  wikidataId: 'Q371126',
  taxonomy: {
    taxonName: 'Craterellus tubaeformis',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q2097845', labels: { en: 'Craterellus', de: 'Kraterellen' } },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      {
        pid: 'P566',
        qid: 'Q105050279',
        labels: { en: 'Cantharellus tubaeformis', de: 'Cantharellus tubaeformis' },
      },
    ],
    authorCitation: '(Fr.) Quél.',
    shortName: 'C. tubaeformis',
  },
  names: {
    labels: { en: 'Craterellus tubaeformis', de: 'Trompetenpfifferling' },
    descriptions: {
      en: 'Edible mushroom growing in temperate regions',
      de: 'Art der Gattung Kraterellen (Craterellus)',
    },
    aliases: {
      en: ['yellowfoot', 'funnel chanterelle', 'winter mushroom', 'Craterellus tubiformis'],
      de: ['Trompeten-Pfifferling', 'Craterellus tubaeformis'],
    },
    commonNames: [
      { lang: 'cs', value: 'liška nálevkovitá' },
      { lang: 'fi', value: 'suppilovahvero' },
      { lang: 'de', value: 'Trompeten-Pfifferling' },
      { lang: 'zh', value: '管形喇叭菌' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861551', labels: { en: 'ridges' } },
    capShape: [
      {
        pid: 'P784',
        qid: 'Q19887958',
        labels: { en: 'infundibuliform mushroom cap', de: 'trichterförmig' },
      },
    ],
    hymeniumAttachment: {
      pid: 'P785',
      qid: 'Q19887925',
      labels: { en: 'decurrent hymenium attachment', de: 'Lamellen herablaufend' },
    },
    stipeCharacter: {
      pid: 'P786',
      qid: 'Q14544581',
      labels: { en: 'bare stipe', de: 'ringloser Stiel' },
    },
    sporePrintColor: { pid: 'P787', qid: 'Q2730433', labels: { en: 'cream', de: 'cremefarben' } },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q114750', labels: { en: 'saprobiont', de: 'Saprobiont' } },
    ],
  },
  edibility: {
    values: [
      {
        pid: 'P789',
        qid: 'Q19888517',
        labels: { en: 'choice mushroom', de: 'hervorragender Speisepilz' },
      },
      { pid: 'P789', qid: 'Q654236', labels: { en: 'edible mushroom', de: 'Speisepilz' } },
    ],
  },
  media: {
    images: ['Cantharellus tubaeformis G28.JPG'],
    commonsCategory: 'Craterellus tubaeformis',
    commonsGallery: 'Craterellus tubaeformis',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '455453',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=455453',
    },
    { pid: 'P846', source: 'GBIF', value: '2554536', url: 'https://www.gbif.org/species/2554536' },
    { pid: 'P962', source: 'MycoBank', value: '455453', url: 'https://www.mycobank.org/MB/455453' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '350511',
      url: 'https://inaturalist.org/taxa/350511',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '59857',
      url: 'https://www.biolib.cz/cz/taxon/id59857',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '11446829',
      url: 'https://eol.org/pages/11446829',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '57200',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/57200',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: 'Z8TV',
      url: 'https://www.catalogueoflife.org/data/taxon/Z8TV',
    },
  ],
}

export default craterellusTubaeformisQ371126
