// Wikidata data for Hygrocybe cantharellus (Q3915439)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const hygrocybeCantharellusQ3915439: WikidataSpeciesData = {
  slug: 'hygrocybe-cantharellus',
  wikidataId: 'Q3915439',
  taxonomy: {
    taxonName: 'Hygrocybe cantharellus',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q520530', label: 'Hygrocybe' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q105048108', label: 'Agaricus cantharellus' }],
    authorCitation: '(Schwein.) Murrill',
    shortName: 'H. cantharellus',
  },
  names: {
    labels: { en: 'Hygrocybe cantharellus', de: 'Hygrocybe cantharellus' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Saftlinge (Hygrocybe)' },
    commonNames: [
      { lang: 'cy', value: 'cap cwyr melyn' },
      { lang: 'zh', value: '雞油濕傘' },
      { lang: 'nl', value: 'Trechterwasplaat' },
      { lang: 'cs', value: 'voskovka lišková' },
      { lang: 'fi', value: 'vahverovahakas' },
      { lang: 'zh', value: '鸡油湿伞' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q654236', label: 'edible mushroom' },
      { pid: 'P789', qid: 'Q1686195', label: 'medicinal mushrooms' },
    ],
  },
  media: {
    images: ['2011-06-17 Hygrocybe cantharellus 69428 cropped.jpg'],
    commonsCategory: 'Hygrocybe cantharellus',
    commonsGallery: 'Hygrocybe cantharellus',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '355720' },
    { pid: 'P846', source: 'GBIF', value: '2538595' },
    { pid: 'P962', source: 'MycoBank', value: '355720' },
    { pid: 'P3151', source: 'iNaturalist', value: '63282' },
    { pid: 'P838', source: 'BioLib', value: '348498' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '1008011' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '80589' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '3NB5H' },
  ],
}

export default hygrocybeCantharellusQ3915439
