// Wikidata data for Mycena Flavoalba (Q3914302)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const mycenaFlavoalbaQ3914302: WikidataSpeciesData = {
  slug: 'mycena-flavoalba',
  wikidataId: 'Q3914302',
  taxonomy: {
    taxonName: 'Mycena flavoalba',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q1124575', labels: { en: 'Mycena', de: 'Helmlinge' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      {
        pid: 'P566',
        qid: 'Q59537881',
        labels: { en: 'Agaricus flavoalbus', de: 'Agaricus flavoalbus' },
      },
    ],
    authorCitation: '(Fr.) Quél.',
    shortName: 'M. flavoalba',
  },
  names: {
    labels: { en: 'Mycena flavoalba', de: 'Mycena flavoalba' },
    descriptions: {
      en: 'species of fungus',
      de: 'Pilzart aus der Familie der Schwindlingsverwandten (Marasmiaceae)',
    },
    aliases: { en: ['ivory bonnet'] },
    commonNames: [
      { lang: 'cy', value: 'bonet ifori' },
      { lang: 'nl', value: 'Bleekgele mycena' },
      { lang: 'cs', value: 'helmovka žlutobílá' },
      { lang: 'fi', value: 'kermahiippo' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q269345', labels: { en: 'lamella', de: 'Lamelle' } },
    capShape: [
      { pid: 'P784', qid: 'Q19887954', labels: { en: 'conical mushroom cap', de: 'kegelig' } },
    ],
    hymeniumAttachment: {
      pid: 'P785',
      qid: 'Q14544569',
      labels: { en: 'adnate hymenium attachment', de: 'Lamellen breit angewachsen' },
    },
    stipeCharacter: {
      pid: 'P786',
      qid: 'Q14544581',
      labels: { en: 'bare stipe', de: 'ringloser Stiel' },
    },
    sporePrintColor: { pid: 'P787', qid: 'Q23444', labels: { en: 'white', de: 'Weiß' } },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q114750', labels: { en: 'saprobiont', de: 'Saprobiont' } },
    ],
  },
  edibility: {
    values: [
      {
        pid: 'P789',
        qid: 'Q4317894',
        labels: { en: 'inedible mushroom', de: 'ungenießbarer Pilz' },
      },
    ],
  },
  media: {
    images: ['Mycena spec. - Lindsey 6a.jpg'],
    commonsCategory: 'Mycena flavoalba',
    commonsGallery: 'Mycena flavoalba',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '201778',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=201778',
    },
    { pid: 'P846', source: 'GBIF', value: '2527092', url: 'https://www.gbif.org/species/2527092' },
    { pid: 'P962', source: 'MycoBank', value: '201778', url: 'https://www.mycobank.org/MB/201778' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '565201',
      url: 'https://inaturalist.org/taxa/565201',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '126075',
      url: 'https://www.biolib.cz/cz/taxon/id126075',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '42685746',
      url: 'https://eol.org/pages/42685746',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '139087',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/139087',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '44T4W',
      url: 'https://www.catalogueoflife.org/data/taxon/44T4W',
    },
  ],
}

export default mycenaFlavoalbaQ3914302
