// Wikidata data for Amanita pantherina (Q45547)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const amanitaPantherinaQ45547: WikidataSpeciesData = {
  slug: 'amanita-pantherina',
  wikidataId: 'Q45547',
  taxonomy: {
    taxonName: 'Amanita pantherina',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q213938', label: 'Amanita' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q33038753', label: 'Agaricus pantherinus' }],
    authorCitation: '(DC.) Krombh. (1846)',
    shortName: 'A. pantherina',
  },
  names: {
    labels: { en: 'Amanita pantherina', de: 'Pantherpilz' },
    descriptions: {
      en: 'species of fungus',
      de: 'Eine Pilzart aus der Familie der Wulstlingsverwandten (Amanitaceae)',
    },
    aliases: {
      en: ['Amanita pantherina var. pantherina', 'panther cap', 'false blusher', 'panther amanita'],
      de: ['Brauner Knollenblätterpilz', 'Amanita pantherina', 'Panterpilz'],
    },
    commonNames: [
      { lang: 'cy', value: 'amanita panther' },
      { lang: 'zh', value: '豹斑鵝膏' },
      { lang: 'nl', value: 'Panteramaniet' },
      { lang: 'cs', value: 'muchomůrka tygrovaná' },
      { lang: 'fi', value: 'pantterikärpässieni' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q269345', label: 'lamella' },
    capShape: [{ pid: 'P784', qid: 'Q19887957', label: 'flat mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q14544563', label: 'free hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q19887987', label: 'ring and volva stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q23444', label: 'white' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [{ pid: 'P789', qid: 'Q359511', label: 'poisonous mushroom' }],
  },
  media: {
    images: [
      'Amanita pantherina (1468298504).jpg',
      'Amanita pantherina 2013 G1.jpg',
      'Spore print Amanita Pantherina.jpg',
    ],
    commonsCategory: 'Amanita pantherina',
    commonsGallery: 'Amanita pantherina',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '156565' },
    { pid: 'P846', source: 'GBIF', value: '8961574' },
    { pid: 'P962', source: 'MycoBank', value: '156565' },
    { pid: 'P3151', source: 'iNaturalist', value: '48418' },
    { pid: 'P838', source: 'BioLib', value: '60471' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '1029661' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '67721' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '5TYZH' },
  ],
}

export default amanitaPantherinaQ45547
