// Wikidata data for Clitocybe Gibba (Q46795429)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const clitocybeGibbaQ46795429: WikidataSpeciesData = {
  slug: 'clitocybe-gibba',
  wikidataId: 'Q46795429',
  taxonomy: {
    taxonName: 'Clitocybe gibba',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q368612', labels: { en: 'Clitocybe', de: 'Trichterlinge' } },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      { pid: 'P566', qid: 'Q46795858', labels: { en: 'Agaricus gibbus', de: 'Agaricus gibbus' } },
    ],
    authorCitation: '(Pers.) P.Kumm. (1871)',
    shortName: 'C. gibba',
  },
  names: {
    labels: { en: 'Clitocybe gibba', de: 'Clitocybe gibba' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Trichterlinge (Clitocybe)' },
    aliases: { en: ['Infundibulicybe gibba'] },
    commonNames: [],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: [],
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '356792',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=356792',
    },
    { pid: 'P846', source: 'GBIF', value: '2531144', url: 'https://www.gbif.org/species/2531144' },
    { pid: 'P962', source: 'MycoBank', value: '356792', url: 'https://www.mycobank.org/MB/356792' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '327568',
      url: 'https://inaturalist.org/taxa/327568',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '195545',
      url: 'https://eol.org/pages/195545',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: 'W8KS',
      url: 'https://www.catalogueoflife.org/data/taxon/W8KS',
    },
  ],
}

export default clitocybeGibbaQ46795429
