// Wikidata data for Armillaria mellea (Q473745)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const armillariaMelleaQ473745: WikidataSpeciesData = {
  slug: 'armillaria-mellea',
  wikidataId: 'Q473745',
  taxonomy: {
    taxonName: 'Armillaria mellea',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q952036', label: 'Armillaria' }],
    instanceOf: [
      { pid: 'P31', qid: 'Q16521', label: 'taxon' },
      { pid: 'P31', qid: 'Q765940', label: 'cryptic species complex' },
    ],
    basionym: [{ pid: 'P566', qid: 'Q62071518', label: 'Agaricus melleus' }],
    authorCitation: '(Vahl) P.Kumm. (1871)',
    shortName: 'A. mellea',
  },
  names: {
    labels: { en: 'Armillaria mellea', de: 'Honiggelber Hallimasch' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Hallimasche (Armillaria)' },
    aliases: {
      en: ['Armillariella mellea', 'honey fungus'],
      de: [
        'Halawatsch',
        'Armillaria mellea',
        'Stuppling',
        'Goldgelber Hallimasch',
        'Halamarsch',
        'Hallimasch',
      ],
    },
    commonNames: [
      { lang: 'cy', value: 'ffwng melog' },
      { lang: 'zh', value: '假蜜環菌' },
      { lang: 'nl', value: 'Echte honingzwam' },
      { lang: 'cs', value: 'václavka obecná' },
      { lang: 'de', value: 'Honiggelber Hallimasch' },
      { lang: 'en', value: 'Honey Fungus' },
      { lang: 'zh', value: '蜜环菌' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q269345', label: 'lamella' },
  },
  ecology: {},
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q62102033', label: 'edible when cooked' },
      { pid: 'P789', qid: 'Q654236', label: 'edible mushroom' },
      { pid: 'P789', qid: 'Q1686195', label: 'medicinal mushrooms' },
    ],
  },
  media: {
    images: [
      'Armillaria mellea, Honey Fungus, UK 1.jpg',
      'Armillaria mellea (1).jpg',
      'Armillaria mellea Linden.jpg',
    ],
    commonsCategory: 'Armillaria mellea',
    commonsGallery: 'Armillaria mellea',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '190066' },
    { pid: 'P846', source: 'GBIF', value: '2536891' },
    { pid: 'P962', source: 'MycoBank', value: '190066' },
    { pid: 'P3151', source: 'iNaturalist', value: '55950' },
    { pid: 'P838', source: 'BioLib', value: '60288' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '1029436' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '47429' },
    { pid: 'P10585', source: 'Catalogue of Life', value: 'GSMV' },
  ],
}

export default armillariaMelleaQ473745
