// Wikidata data for Lactarius deterrimus (Q498221)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const lactariusDeterrimusQ498221: WikidataSpeciesData = {
  slug: 'lactarius-deterrimus',
  wikidataId: 'Q498221',
  taxonomy: {
    taxonName: 'Lactarius deterrimus',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q2142268', label: 'Deliciosi' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    authorCitation: 'Gröger',
    shortName: 'L. deterrimus',
  },
  names: {
    labels: { en: 'Lactarius deterrimus', de: 'Fichten-Reizker' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Milchlinge (Lactarius)' },
    aliases: {
      en: ['false saffron milkcap', 'orange milkcap'],
      de: [
        'Fichten-Blutreizker',
        'Fichten-Milchling',
        'Fichtenblutreizker',
        'Fichtenreizker',
        'Lactarius deterrimus',
      ],
    },
    commonNames: [
      { lang: 'cy', value: 'cap llaeth saffrwm ffug' },
      { lang: 'cs', value: 'ryzec smrkový' },
      { lang: 'fi', value: 'kuusenleppärousku' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q269345', label: 'lamella' },
    capShape: [{ pid: 'P784', qid: 'Q19887955', label: 'depressed mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887925', label: 'decurrent hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q14544581', label: 'bare stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q1670336', label: 'tan' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [{ pid: 'P789', qid: 'Q654236', label: 'edible mushroom' }],
  },
  media: {
    images: ['Lactarius-deterrimus-Fichten-Reizker.jpg'],
    commonsCategory: 'Lactarius deterrimus',
    commonsGallery: 'Lactarius deterrimus',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '332881' },
    { pid: 'P846', source: 'GBIF', value: '5248699' },
    { pid: 'P962', source: 'MycoBank', value: '332881' },
    { pid: 'P3151', source: 'iNaturalist', value: '194385' },
    { pid: 'P838', source: 'BioLib', value: '59999' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '1016697' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '36060' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '3RRSG' },
  ],
}

export default lactariusDeterrimusQ498221
