// Wikidata data for Cordyceps ophioglossoides (Q54366414)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const cordycepsOphioglossoidesQ54366414: WikidataSpeciesData = {
  slug: 'cordyceps-ophioglossoides',
  wikidataId: 'Q54366414',
  taxonomy: {
    taxonName: 'Cordyceps ophioglossoides',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q312238', label: 'Cordyceps' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    shortName: 'C. ophioglossoides',
  },
  names: {
    labels: { en: 'Cordyceps ophioglossoides', de: 'Cordyceps ophioglossoides' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Kernkeule (Cordyceps)' },
    commonNames: [],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: [],
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '164093' },
    { pid: 'P846', source: 'GBIF', value: '2564391' },
    { pid: 'P962', source: 'MycoBank', value: '164093' },
    { pid: 'P3151', source: 'iNaturalist', value: '217587' },
    { pid: 'P10585', source: 'Catalogue of Life', value: 'YCHN' },
  ],
}

export default cordycepsOphioglossoidesQ54366414
