// Wikidata data for Lycoperdon perlatum (Q545130)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const lycoperdonPerlatumQ545130: WikidataSpeciesData = {
  slug: 'lycoperdon-perlatum',
  wikidataId: 'Q545130',
  taxonomy: {
    taxonName: 'Lycoperdon perlatum',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q1335970', labels: { en: 'Lycoperdon', de: 'Stäublinge' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    authorCitation: 'Pers.',
    shortName: 'L. perlatum',
  },
  names: {
    labels: { en: 'Lycoperdon perlatum', de: 'Flaschen-Stäubling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Stäublinge (Lycoperdon)' },
    aliases: {
      en: ["devil's snuff-box", 'common puffball', 'warted puffball', 'gem-studded puffball'],
      de: ['Lycoperdon perlatum'],
    },
    commonNames: [
      { lang: 'cy', value: 'coden fwg gyffredin' },
      { lang: 'zh', value: '網紋馬勃' },
      { lang: 'cs', value: 'pýchavka obecná' },
      { lang: 'sk', value: 'prášnica bradavičnatá' },
      { lang: 'en', value: "devil's snuff-box" },
      { lang: 'en', value: 'common puffball' },
      { lang: 'en', value: 'warted puffball' },
      { lang: 'en', value: 'gem-studded puffball' },
      { lang: 'da', value: 'Krystal-Støvbold' },
      { lang: 'nl', value: 'Parelstuifzwam' },
      { lang: 'hr', value: 'tikvasta puhara' },
      { lang: 'de', value: 'Flaschen-Stäubling' },
      { lang: 'pl', value: 'purchawka chropowata' },
      { lang: 'es', value: 'cuesco de lobo' },
      { lang: 'es', value: 'pedo de lobo' },
      { lang: 'et', value: 'harilik murumuna' },
      { lang: 'eu', value: 'Otsoputz' },
      { lang: 'fr', value: 'Vesse-de-loup perlée' },
      { lang: 'gl', value: 'Fungato' },
      { lang: 'hu', value: 'Bimbós pöfeteg' },
      { lang: 'ja', value: 'ホコリタケ' },
      { lang: 'ku', value: 'Fisegur' },
      { lang: 'lt', value: 'Karpotasis pumpotaukšlis' },
      { lang: 'ru', value: 'Дождевик шиповатый' },
      { lang: 'sr', value: 'Тикваста пухара' },
      { lang: 'sv', value: 'Vårtig röksvamp' },
      { lang: 'uk', value: 'Дощовик їстівний' },
      { lang: 'wa', value: 'Vesse di leu' },
      { lang: 'zh-tw', value: '網紋馬勃' },
      { lang: 'zh-tw', value: '芽狀馬勃' },
      { lang: 'fi', value: 'känsätuhkelo' },
      { lang: 'ast', value: 'peudellobu' },
      { lang: 'zh', value: '网纹马勃' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q2034230', labels: { en: 'gleba', de: 'Gleba' } },
    capShape: [
      { pid: 'P784', qid: 'Q14544535', labels: { en: 'convex mushroom cap', de: 'gewölbt' } },
    ],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887932', labels: { en: 'no hymenium attachment' } },
    stipeCharacter: {
      pid: 'P786',
      qid: 'Q14544581',
      labels: { en: 'bare stipe', de: 'ringloser Stiel' },
    },
    sporePrintColor: { pid: 'P787', qid: 'Q47071', labels: { en: 'brown', de: 'Braun' } },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q114750', labels: { en: 'saprobiont', de: 'Saprobiont' } },
    ],
  },
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q654236', labels: { en: 'edible mushroom', de: 'Speisepilz' } },
      { pid: 'P789', qid: 'Q1686195', labels: { en: 'medicinal mushrooms', de: 'Mykotherapie' } },
    ],
    conservationStatus: [
      { pid: 'P141', qid: 'Q211005', labels: { en: 'least concern', de: 'nicht gefährdet' } },
    ],
  },
  media: {
    images: ['Single lycoperdon perlatum.jpg'],
    commonsCategory: 'Lycoperdon perlatum',
    commonsGallery: 'Lycoperdon perlatum',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '220647',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=220647',
    },
    { pid: 'P846', source: 'GBIF', value: '5243258', url: 'https://www.gbif.org/species/5243258' },
    { pid: 'P962', source: 'MycoBank', value: '220647', url: 'https://www.mycobank.org/MB/220647' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '48443',
      url: 'https://inaturalist.org/taxa/48443',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '60754',
      url: 'https://www.biolib.cz/cz/taxon/id60754',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '162875',
      url: 'https://eol.org/pages/162875',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '90686',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/90686',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '3WLKC',
      url: 'https://www.catalogueoflife.org/data/taxon/3WLKC',
    },
  ],
}

export default lycoperdonPerlatumQ545130
