// Wikidata data for Tricholoma sulphureum (Q583388)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const tricholomaSulphureumQ583388: WikidataSpeciesData = {
  slug: 'tricholoma-sulphureum',
  wikidataId: 'Q583388',
  taxonomy: {
    taxonName: 'Tricholoma sulphureum',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q573661', label: 'Tricholoma' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q105048907', label: 'Agaricus sulphureus' }],
    authorCitation: '(Bull.) P.Kumm.',
    shortName: 'T. sulphureum',
  },
  names: {
    labels: { en: 'Tricholoma sulphureum', de: 'Gemeiner Schwefel-Ritterling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Ritterlinge (Tricholoma)' },
    commonNames: [
      { lang: 'cy', value: 'marchog swlffwraidd' },
      { lang: 'nl', value: 'Narcisridderzwam' },
      { lang: 'cs', value: 'čirůvka sírožlutá' },
      { lang: 'fi', value: 'rikkivalmuska' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q269345', label: 'lamella' },
    capShape: [{ pid: 'P784', qid: 'Q14544535', label: 'convex mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887923', label: 'adnexed hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q14544581', label: 'bare stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q23444', label: 'white' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q359511', label: 'poisonous mushroom' },
      { pid: 'P789', qid: 'Q654236', label: 'edible mushroom' },
      { pid: 'P789', qid: 'Q1686195', label: 'medicinal mushrooms' },
    ],
  },
  media: {
    images: ['Tricholoma sulphureum 031123w.jpg'],
    commonsCategory: 'Tricholoma sulphureum',
    commonsGallery: 'Tricholoma sulphureum',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '227491' },
    { pid: 'P846', source: 'GBIF', value: '3324436' },
    { pid: 'P962', source: 'MycoBank', value: '227491' },
    { pid: 'P3151', source: 'iNaturalist', value: '408299' },
    { pid: 'P838', source: 'BioLib', value: '60408' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '6681318' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '181718' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '7D3FT' },
  ],
}

export default tricholomaSulphureumQ583388
