// Wikidata data for Leccinum scabrum (Q628977)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const leccinumScabrumQ628977: WikidataSpeciesData = {
  slug: 'leccinum-scabrum',
  wikidataId: 'Q628977',
  taxonomy: {
    taxonName: 'Leccinum scabrum',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q573152', labels: { en: 'Leccinum', de: 'Leccinum' } }],
    instanceOf: [
      { pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } },
      { pid: 'P31', qid: 'Q654236', labels: { en: 'edible mushroom', de: 'Speisepilz' } },
    ],
    basionym: [
      { pid: 'P566', qid: 'Q42048228', labels: { en: 'Boletus scaber', de: 'Boletus scaber' } },
    ],
    authorCitation: '(Bull.) Gray',
    shortName: 'L. scabrum',
  },
  names: {
    labels: { en: 'Leccinum scabrum', de: 'Gemeiner Birkenpilz' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Raufußröhrlinge (Leccinum)' },
    aliases: {
      en: ['rough-stemmed bolete', 'scaber stalk', 'birch bolete'],
      de: [
        'Gemeiner Raufußröhrling',
        'Birkenpilz',
        'Leccinum scabrum',
        'Birkenröhrling',
        'Birken-Röhrling',
        'Krombholzia scabra',
        'Kapuziner',
        'Geißpilz',
        'Rötender Birkenpilz',
      ],
    },
    commonNames: [
      { lang: 'cy', value: 'cap tyllog brown bedw' },
      { lang: 'nl', value: 'Gewone berkeboleet' },
      { lang: 'cs', value: 'kozák březový' },
      { lang: 'fi', value: 'lehmäntatti' },
      { lang: 'nl', value: 'Blozende berkeboleet' },
      { lang: 'cs', value: 'kozák červenající' },
      { lang: 'be-tarask', value: 'абабак' },
      { lang: 'sl', value: 'brezov ded' },
      { lang: 'nb', value: 'brunskrubb' },
      { lang: 'zh', value: '褐疣柄牛肝菌' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861549', labels: { en: 'pores', de: 'Poren' } },
    capShape: [
      { pid: 'P784', qid: 'Q14544535', labels: { en: 'convex mushroom cap', de: 'gewölbt' } },
    ],
    hymeniumAttachment: {
      pid: 'P785',
      qid: 'Q14544569',
      labels: { en: 'adnate hymenium attachment', de: 'Lamellen breit angewachsen' },
    },
    stipeCharacter: {
      pid: 'P786',
      qid: 'Q14544581',
      labels: { en: 'bare stipe', de: 'ringloser Stiel' },
    },
    sporePrintColor: { pid: 'P787', qid: 'Q864152', labels: { en: 'olive', de: 'Oliv' } },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q99974', labels: { en: 'mycorrhiza', de: 'Mykorrhiza' } },
    ],
  },
  edibility: {
    values: [{ pid: 'P789', qid: 'Q654236', labels: { en: 'edible mushroom', de: 'Speisepilz' } }],
  },
  media: {
    images: ['Birkenpilz01.jpg', 'Leccinum 2026 G2.jpg'],
    commonsCategory: 'Leccinum scabrum',
    commonsGallery: 'Leccinum scabrum',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '100712',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=100712',
    },
    { pid: 'P846', source: 'GBIF', value: '2524575', url: 'https://www.gbif.org/species/2524575' },
    { pid: 'P962', source: 'MycoBank', value: '100712', url: 'https://www.mycobank.org/MB/100712' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '63232',
      url: 'https://inaturalist.org/taxa/63232',
    },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '63225',
      url: 'https://inaturalist.org/taxa/63225',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '60168',
      url: 'https://www.biolib.cz/cz/taxon/id60168',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '6669889',
      url: 'https://eol.org/pages/6669889',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '121051',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/121051',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '3STFC',
      url: 'https://www.catalogueoflife.org/data/taxon/3STFC',
    },
  ],
}

export default leccinumScabrumQ628977
