// Wikidata data for Caloboletus radicans (Q64785775)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const caloboletusRadicansQ64785775: WikidataSpeciesData = {
  slug: 'caloboletus-radicans',
  wikidataId: 'Q64785775',
  taxonomy: {
    taxonName: 'Caloboletus radicans',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q19277034', label: 'Caloboletus' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q1478484', label: 'Boletus radicans' }],
    authorCitation: '(Pers.) Vizzini',
    shortName: 'C. radicans',
  },
  names: {
    labels: { en: 'Caloboletus radicans', de: 'Wurzelnder Bitter-Röhrling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Caloboletus' },
    aliases: {
      en: ['rooting bolete', 'whitish bolete'],
      de: ['Wurzelnder Bitterröhrling', 'Bitterschwamm', 'Caloboletus radicans'],
    },
    commonNames: [
      { lang: 'cy', value: 'cap tyllog gwreiddiog' },
      { lang: 'nl', value: 'Wortelende boleet' },
      { lang: 'cs', value: 'hřib medotrpký' },
      { lang: 'sl', value: 'grenki goban' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861549', label: 'pores' },
    capShape: [{ pid: 'P784', qid: 'Q14544535', label: 'convex mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887923', label: 'adnexed hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q14544581', label: 'bare stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q19888352', label: 'olive brown' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [{ pid: 'P789', qid: 'Q4317894', label: 'inedible mushroom' }],
  },
  media: {
    images: ['Bol006.jpg'],
    commonsCategory: 'Caloboletus radicans',
    commonsGallery: 'Caloboletus radicans',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '550548' },
    { pid: 'P846', source: 'GBIF', value: '7550396' },
    { pid: 'P962', source: 'MycoBank', value: '550548' },
    { pid: 'P3151', source: 'iNaturalist', value: '507493' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '46705962' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '150783' },
    { pid: 'P10585', source: 'Catalogue of Life', value: 'PWYN' },
  ],
}

export default caloboletusRadicansQ64785775
