// Wikidata data for Suillellus luridus (Q752494)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const suillellusLuridusQ752494: WikidataSpeciesData = {
  slug: 'suillellus-luridus',
  wikidataId: 'Q752494',
  taxonomy: {
    taxonName: 'Suillellus luridus',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q18907506', label: 'Suillellus' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q41597775', label: 'Boletus luridus' }],
    authorCitation: '(Schaeff.) Murrill',
    shortName: 'S. luridus',
  },
  names: {
    labels: { en: 'Suillellus luridus', de: 'Netzstieliger Hexen-Röhrling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Dickröhrlinge (Boletus)' },
    aliases: {
      en: ['Boletus luridus', 'lurid bolete'],
      de: ['Netzstieliger Hexenröhrling', 'Suillellus luridus', 'Boletus luridus'],
    },
    commonNames: [
      { lang: 'cy', value: 'cap tyllog llwydfelyn' },
      { lang: 'nl', value: 'Netstelige heksenboleet' },
      { lang: 'fi', value: 'tauriontatti' },
      { lang: 'cs', value: 'hřib koloděj' },
      { lang: 'sl', value: 'svinjski lupljivec' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861549', label: 'pores' },
    capShape: [{ pid: 'P784', qid: 'Q14544535', label: 'convex mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887932', label: 'no hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q14544581', label: 'bare stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q19888352', label: 'olive brown' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q62102033', label: 'edible when cooked' },
      { pid: 'P789', qid: 'Q654236', label: 'edible mushroom' },
    ],
  },
  media: {
    images: [
      '2010-09-13 Boletus luridus Schaeff 104527 crop.jpg',
      'Netzstieliger Hexen-Röhrling Boletus luridus.jpg',
    ],
    commonsCategory: 'Suillellus luridus',
    commonsGallery: 'Suillellus luridus',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '102402' },
    { pid: 'P846', source: 'GBIF', value: '3355021' },
    { pid: 'P962', source: 'MycoBank', value: '102402' },
    { pid: 'P3151', source: 'iNaturalist', value: '824777' },
    { pid: 'P838', source: 'BioLib', value: '60143' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '18506462' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '121041' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '7B4RP' },
  ],
}

export default suillellusLuridusQ752494
