// Wikidata data for Infundibulicybe gibba (Q765631)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const infundibulicybeGibbaQ765631: WikidataSpeciesData = {
  slug: 'infundibulicybe-gibba',
  wikidataId: 'Q765631',
  taxonomy: {
    taxonName: 'Infundibulicybe gibba',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q142749', labels: { en: 'Infundibulicybe', de: 'Infundibulicybe' } },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      { pid: 'P566', qid: 'Q46795858', labels: { en: 'Agaricus gibbus', de: 'Agaricus gibbus' } },
    ],
    shortName: 'I. gibba',
  },
  names: {
    labels: { en: 'Infundibulicybe gibba', de: 'Ockerbrauner Trichterling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Infundibulicybe' },
    aliases: { en: ['Clitocybe gibba'], de: ['Infundibulicybe gibba'] },
    commonNames: [
      { lang: 'cy', value: 'twmffat|twndish cefngrwm' },
      { lang: 'cs', value: 'strmělka nálevkovitá' },
      { lang: 'fi', value: 'suppilomalikka' },
      { lang: 'nl', value: 'Slanke trechterzwam' },
      { lang: 'zh', value: '深凹漏斗伞' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q654236', labels: { en: 'edible mushroom', de: 'Speisepilz' } },
      { pid: 'P789', qid: 'Q19888537', labels: { en: 'caution mushroom' } },
      {
        pid: 'P789',
        qid: 'Q1169875',
        labels: { en: 'psychoactive mushroom', de: 'psychoaktive Pilze' },
      },
      { pid: 'P789', qid: 'Q359511', labels: { en: 'poisonous mushroom', de: 'Giftpilz' } },
    ],
  },
  media: {
    images: ['2006-08-10 Infundibulicybe gibba.jpg'],
    commonsCategory: 'Infundibulicybe gibba',
    commonsGallery: 'Infundibulicybe gibba',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '487939',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=487939',
    },
    { pid: 'P846', source: 'GBIF', value: '2531146', url: 'https://www.gbif.org/species/2531146' },
    { pid: 'P962', source: 'MycoBank', value: '487939', url: 'https://www.mycobank.org/MB/487939' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '921916',
      url: 'https://inaturalist.org/taxa/921916',
    },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '327568',
      url: 'https://inaturalist.org/taxa/327568',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '60305',
      url: 'https://www.biolib.cz/cz/taxon/id60305',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '378275',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/378275',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '3PP8H',
      url: 'https://www.catalogueoflife.org/data/taxon/3PP8H',
    },
  ],
}

export default infundibulicybeGibbaQ765631
