// Wikidata data for Laetiporus sulphureus (Q772098)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const laetiporusSulphureusQ772098: WikidataSpeciesData = {
  slug: 'laetiporus-sulphureus',
  wikidataId: 'Q772098',
  taxonomy: {
    taxonName: 'Laetiporus sulphureus',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q11158661', labels: { en: 'Laetiporus', de: 'Schwefelporlinge' } },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    basionym: [
      {
        pid: 'P566',
        qid: 'Q105050001',
        labels: { en: 'Boletus sulphureus', de: 'Boletus sulphureus' },
      },
    ],
    authorCitation: '(Bull.) Murrill',
    shortName: 'L. sulphureus',
  },
  names: {
    labels: { en: 'Laetiporus sulphureus', de: 'Schwefelporling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Laetiporus' },
    aliases: {
      en: ['chicken-of-the-woods', 'crab-of-the-woods', 'lobster-of-the-woods'],
      de: ['Laetiporus sulphureus'],
    },
    commonNames: [
      { lang: 'cy', value: 'ysgwydd felen' },
      { lang: 'zh', value: '硫磺菌' },
      { lang: 'nl', value: 'Zwavelzwam' },
      { lang: 'cs', value: 'sírovec žlutooranžový' },
      { lang: 'pl', value: 'żółciak siarkowy' },
      { lang: 'fi', value: 'rikkikääpä' },
      { lang: 'en', value: 'chicken of the woods' },
      { lang: 'sl', value: 'žvepleni lepoluknjičar' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q19861549', labels: { en: 'pores', de: 'Poren' } },
    capShape: [
      { pid: 'P784', qid: 'Q19887957', labels: { en: 'flat mushroom cap', de: 'ausgebreitet' } },
    ],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887932', labels: { en: 'no hymenium attachment' } },
    sporePrintColor: { pid: 'P787', qid: 'Q23444', labels: { en: 'white', de: 'Weiß' } },
  },
  ecology: {
    ecologicalType: [
      { pid: 'P788', qid: 'Q114750', labels: { en: 'saprobiont', de: 'Saprobiont' } },
      { pid: 'P788', qid: 'Q186517', labels: { en: 'parasitism', de: 'Parasitismus' } },
    ],
  },
  edibility: {
    values: [
      {
        pid: 'P789',
        qid: 'Q62102033',
        labels: { en: 'edible when cooked', de: 'nur zubereitet essbar' },
      },
      { pid: 'P789', qid: 'Q1686195', labels: { en: 'medicinal mushrooms', de: 'Mykotherapie' } },
      { pid: 'P789', qid: 'Q359511', labels: { en: 'poisonous mushroom', de: 'Giftpilz' } },
      { pid: 'P789', qid: 'Q654236', labels: { en: 'edible mushroom', de: 'Speisepilz' } },
    ],
  },
  media: {
    images: ['Laetiporus sulphureus big.jpg'],
    commonsCategory: 'Laetiporus sulphureus',
    commonsGallery: 'Laetiporus sulphureus',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '299348',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=299348',
    },
    { pid: 'P846', source: 'GBIF', value: '9072021', url: 'https://www.gbif.org/species/9072021' },
    { pid: 'P962', source: 'MycoBank', value: '299348', url: 'https://www.mycobank.org/MB/299348' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '53713',
      url: 'https://inaturalist.org/taxa/53713',
    },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '130925',
      url: 'https://inaturalist.org/taxa/130925',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '59936',
      url: 'https://www.biolib.cz/cz/taxon/id59936',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '191234',
      url: 'https://eol.org/pages/191234',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '5630',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/5630',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '6NSSX',
      url: 'https://www.catalogueoflife.org/data/taxon/6NSSX',
    },
  ],
}

export default laetiporusSulphureusQ772098
