// Wikidata data for Oudemansiella Mucida (Q783554)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const oudemansiellaMucidaQ783554: WikidataSpeciesData = {
  slug: 'oudemansiella-mucida',
  wikidataId: 'Q783554',
  taxonomy: {
    taxonName: 'Oudemansiella mucida',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [
      { pid: 'P171', qid: 'Q1243899', labels: { en: 'Oudemansiella', de: 'Schleimrüblinge' } },
    ],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    shortName: 'O. mucida',
  },
  names: {
    labels: { en: 'Oudemansiella mucida', de: 'Buchen-Schleimrübling' },
    descriptions: {
      en: 'species of fungus',
      de: 'Art der Gattung Schleimrüblinge (Oudemansiella)',
    },
    commonNames: [
      { lang: 'cy', value: 'cap porslen' },
      { lang: 'zh', value: '霉狀小奧德蘑' },
      { lang: 'nl', value: 'Porseleinzwam' },
      { lang: 'cs', value: 'slizečka porcelánová' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: ['2025-11-01 D500-1475 Achim-Lammerts Oudemansiella-mucida.jpg'],
    commonsCategory: 'Oudemansiella mucida',
    commonsGallery: 'Oudemansiella mucida',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '120947',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=120947',
    },
    { pid: 'P846', source: 'GBIF', value: '5243647', url: 'https://www.gbif.org/species/5243647' },
    { pid: 'P962', source: 'MycoBank', value: '120947', url: 'https://www.mycobank.org/MB/120947' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '55964',
      url: 'https://inaturalist.org/taxa/55964',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '60368',
      url: 'https://www.biolib.cz/cz/taxon/id60368',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '301838',
      url: 'https://eol.org/pages/301838',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '4B8NJ',
      url: 'https://www.catalogueoflife.org/data/taxon/4B8NJ',
    },
  ],
}

export default oudemansiellaMucidaQ783554
