// Wikidata data for Gomphidius glutinosus (Q790626)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const gomphidiusGlutinosusQ790626: WikidataSpeciesData = {
  slug: 'gomphidius-glutinosus',
  wikidataId: 'Q790626',
  taxonomy: {
    taxonName: 'Gomphidius glutinosus',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q1631217', label: 'Gomphidius' }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', label: 'taxon' }],
    basionym: [{ pid: 'P566', qid: 'Q12229296', label: 'Agaricus glutinosus' }],
    shortName: 'G. glutinosus',
  },
  names: {
    labels: { en: 'Gomphidius glutinosus', de: 'Großer Schmierling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Schmierlinge (Gomphidius)' },
    aliases: {
      en: ['slimy spike-cap'],
      de: ['Kuhmaul', 'Gomphidius glutinosus', 'Großer Gelbfuß', 'Grosser Gelbfuss'],
    },
    commonNames: [
      { lang: 'cy', value: 'spigyn gludiog' },
      { lang: 'nl', value: 'Slijmige spijkerzwam' },
      { lang: 'cs', value: 'slizák mazlavý' },
      { lang: 'fi', value: 'limanuljaska' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q269345', label: 'lamella' },
    capShape: [{ pid: 'P784', qid: 'Q19887957', label: 'flat mushroom cap' }],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887925', label: 'decurrent hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q14544582', label: 'ring stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q19888339', label: 'blackish-brown' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [{ pid: 'P789', qid: 'Q654236', label: 'edible mushroom' }],
    conservationStatus: [{ pid: 'P141', qid: 'Q211005', label: 'least concern' }],
  },
  media: {
    images: ['Gomphidius glutinosus 131007.jpg'],
    commonsCategory: 'Gomphidius glutinosus',
    commonsGallery: 'Gomphidius glutinosus',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '209017' },
    { pid: 'P846', source: 'GBIF', value: '2525027' },
    { pid: 'P962', source: 'MycoBank', value: '209017' },
    { pid: 'P3151', source: 'iNaturalist', value: '48424' },
    { pid: 'P838', source: 'BioLib', value: '60197' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '1017422' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '5393' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '3GSMW' },
  ],
}

export default gomphidiusGlutinosusQ790626
