// Wikidata data for Russula delica (Q843177)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const russulaDelicaQ843177: WikidataSpeciesData = {
  slug: 'russula-delica',
  wikidataId: 'Q843177',
  taxonomy: {
    taxonName: 'Russula delica',
    taxonRank: { pid: 'P105', qid: 'Q7432', label: 'species' },
    parentTaxon: [{ pid: 'P171', qid: 'Q216110', label: 'Russula' }],
    instanceOf: [
      { pid: 'P31', qid: 'Q16521', label: 'taxon' },
      { pid: 'P31', qid: 'Q11619941', label: 'mycorrhizal fungus' },
    ],
    authorCitation: '(Paul.) Fr.',
    shortName: 'R. delica',
  },
  names: {
    labels: { en: 'Russula delica', de: 'Gemeiner Weiß-Täubling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Täublinge (Russula)' },
    aliases: {
      de: [
        'Russula delica',
        'Blaublättriger Weißtäubling',
        'Gewöhnlicher Weiß-Täubling',
        'Gewöhnlicher Weißtäubling',
        'Breitblättriger Weißtäubling',
        'Gemeiner Weißtäubling',
        'Breitblättriger Weiß-Täubling',
        'Blaublättriger Weiß-Täubling',
      ],
    },
    commonNames: [
      { lang: 'cy', value: 'tegyll brau llaethwyn' },
      { lang: 'zh', value: '美味紅菇' },
      { lang: 'nl', value: 'Witte russula' },
      { lang: 'cs', value: 'holubinka bílá' },
      { lang: 'et', value: 'kuiv pilvik' },
      { lang: 'fi', value: 'suppilohapero' },
      { lang: 'zh', value: '美味红菇' },
    ],
  },
  morphology: {
    hymeniumType: { pid: 'P783', qid: 'Q269345', label: 'lamella' },
    capShape: [
      { pid: 'P784', qid: 'Q14544535', label: 'convex mushroom cap' },
      { pid: 'P784', qid: 'Q19887957', label: 'flat mushroom cap' },
    ],
    hymeniumAttachment: { pid: 'P785', qid: 'Q19887925', label: 'decurrent hymenium attachment' },
    stipeCharacter: { pid: 'P786', qid: 'Q14544581', label: 'bare stipe' },
    sporePrintColor: { pid: 'P787', qid: 'Q23444', label: 'white' },
  },
  ecology: {
    ecologicalType: [{ pid: 'P788', qid: 'Q99974', label: 'mycorrhiza' }],
  },
  edibility: {
    values: [
      { pid: 'P789', qid: 'Q654236', label: 'edible mushroom' },
      { pid: 'P789', qid: 'Q1686195', label: 'medicinal mushrooms' },
    ],
  },
  media: {
    images: ['Russ.del.jpg'],
    commonsCategory: 'Russula delica',
    commonsGallery: 'Russula delica',
  },
  externalIds: [
    { pid: 'P1391', source: 'Index Fungorum', value: '184527' },
    { pid: 'P846', source: 'GBIF', value: '2551331' },
    { pid: 'P962', source: 'MycoBank', value: '184527' },
    { pid: 'P3151', source: 'iNaturalist', value: '352278' },
    { pid: 'P838', source: 'BioLib', value: '60063' },
    { pid: 'P830', source: 'Encyclopedia of Life', value: '1009665' },
    { pid: 'P685', source: 'NCBI Taxonomy', value: '111140' },
    { pid: 'P10585', source: 'Catalogue of Life', value: '6X9H6' },
  ],
}

export default russulaDelicaQ843177
