// Wikidata data for Russula Parazurea (Q882885)
// Generated by scripts/fetch-species-wikidata.mjs -- do not edit by hand.
import type { WikidataSpeciesData } from './types'

export const russulaParazureaQ882885: WikidataSpeciesData = {
  slug: 'russula-parazurea',
  wikidataId: 'Q882885',
  taxonomy: {
    taxonName: 'Russula parazurea',
    taxonRank: { pid: 'P105', qid: 'Q7432', labels: { en: 'species', de: 'Art' } },
    parentTaxon: [{ pid: 'P171', qid: 'Q216110', labels: { en: 'Russula', de: 'Täublinge' } }],
    instanceOf: [{ pid: 'P31', qid: 'Q16521', labels: { en: 'taxon', de: 'Taxon' } }],
    authorCitation: 'Jul. Schäff.',
    shortName: 'R. parazurea',
  },
  names: {
    labels: { en: 'Russula parazurea', de: 'Blaugrüner Reif-Täubling' },
    descriptions: { en: 'species of fungus', de: 'Art der Gattung Täublinge (Russula)' },
    aliases: { de: ['Russula parazurea', 'Blaugrüner Reiftäubling'] },
    commonNames: [
      { lang: 'cy', value: 'tegyll brau blodiog' },
      { lang: 'nl', value: 'Berijpte russula' },
      { lang: 'cs', value: 'holubinka podmračná' },
      { lang: 'fi', value: 'patinahapero' },
    ],
  },
  morphology: {},
  ecology: {},
  edibility: {
    values: [],
  },
  media: {
    images: ['Russula parazurea (43426610610).jpg'],
    commonsCategory: 'Russula parazurea',
    commonsGallery: 'Russula parazurea',
  },
  externalIds: [
    {
      pid: 'P1391',
      source: 'Index Fungorum',
      value: '356926',
      url: 'https://www.indexfungorum.org/names/NamesRecord.asp?RecordID=356926',
    },
    { pid: 'P846', source: 'GBIF', value: '2551458', url: 'https://www.gbif.org/species/2551458' },
    { pid: 'P962', source: 'MycoBank', value: '356926', url: 'https://www.mycobank.org/MB/356926' },
    {
      pid: 'P3151',
      source: 'iNaturalist',
      value: '122332',
      url: 'https://inaturalist.org/taxa/122332',
    },
    {
      pid: 'P838',
      source: 'BioLib',
      value: '323240',
      url: 'https://www.biolib.cz/cz/taxon/id323240',
    },
    {
      pid: 'P830',
      source: 'Encyclopedia of Life',
      value: '196979',
      url: 'https://eol.org/pages/196979',
    },
    {
      pid: 'P685',
      source: 'NCBI Taxonomy',
      value: '176814',
      url: 'https://www.ncbi.nlm.nih.gov/taxonomy/176814',
    },
    {
      pid: 'P10585',
      source: 'Catalogue of Life',
      value: '4TSDF',
      url: 'https://www.catalogueoflife.org/data/taxon/4TSDF',
    },
  ],
}

export default russulaParazureaQ882885
