// Catalogue of Life classification for amanita-muscaria
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'amanita-muscaria',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '5TYZ9',
  acceptedName: 'Amanita muscaria',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'N8', name: 'Agaricales' },
    family: { id: '68Y', name: 'Amanitaceae' },
    genus: { id: 'T7Z', name: 'Amanita' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
