// Catalogue of Life classification for armillaria-mellea
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'armillaria-mellea',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: 'GSMV',
  acceptedName: 'Armillaria mellea',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'N8', name: 'Agaricales' },
    family: { id: '625LK', name: 'Physalacriaceae' },
    genus: { id: '332Z', name: 'Armillaria' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
