// Catalogue of Life classification for caloboletus-radicans
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'caloboletus-radicans',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: 'PWYN',
  acceptedName: 'Caloboletus radicans',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'TS', name: 'Boletales' },
    family: { id: '79Z', name: 'Boletaceae' },
    genus: { id: '3FRV', name: 'Caloboletus' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
