// Catalogue of Life classification for calocera-cornea
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'calocera-cornea',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: 'PX52',
  acceptedName: 'Calocera cornea',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '622DM', name: 'Dacrymycetes' },
    order: { id: '62237', name: 'Dacrymycetales' },
    family: { id: '8XZ', name: 'Dacrymycetaceae' },
    genus: { id: '3FS9', name: 'Calocera' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
