// Catalogue of Life classification for clathrus-archeri
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'clathrus-archeri',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: 'VT9Z',
  acceptedName: 'Clathrus archeri',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: '3T3', name: 'Phallales' },
    family: { id: '62697', name: 'Phallaceae' },
    genus: { id: '3QL5', name: 'Clathrus' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
