// Catalogue of Life classification for clavulinopsis-helvola
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'clavulinopsis-helvola',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: 'VWBD',
  acceptedName: 'Clavulinopsis helvola',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'N8', name: 'Agaricales' },
    family: { id: '8B7', name: 'Clavariaceae' },
    genus: { id: '3QR2', name: 'Clavulinopsis' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
