// Catalogue of Life classification for clavulina-coralloides
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'clavulina-coralloides',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: 'VW6K',
  acceptedName: 'Clavulina coralloides',
  status: 'accepted',
  matchedBy: 'name-search',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'VD', name: 'Cantharellales' },
    family: { id: '9XBLB', name: 'Hydnaceae' },
    genus: { id: '3QQZ', name: 'Clavulina' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
