// Catalogue of Life classification for collybiopsis-vaillantii
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'collybiopsis-vaillantii',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: 'B2PWM',
  acceptedName: 'Collybiopsis vaillantii',
  status: 'accepted',
  matchedBy: 'name-search',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'N8', name: 'Agaricales' },
    family: { id: 'DL7', name: 'Omphalotaceae' },
    genus: { id: '62N66', name: 'Collybiopsis' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
