// Catalogue of Life classification for collybia-phyllophila
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'collybia-phyllophila',
  colDatasetKey: 1028,
  colRelease: 'Index Fungorum',
  colId: '847236',
  acceptedName: 'Collybia phyllophila',
  status: 'accepted',
  matchedBy: 'index-fungorum',
  classification: {
    phylum: { id: '90050', name: 'Basidiomycota' },
    class: { id: '501297', name: 'Agaricomycetes' },
    order: { id: '90508', name: 'Agaricales' },
    family: { id: '557869', name: 'Clitocybaceae' },
    genus: { id: '17339', name: 'Collybia' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
