// Catalogue of Life classification for cordyceps-militaris
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'cordyceps-militaris',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: 'YCG6',
  acceptedName: 'Cordyceps militaris',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'SM', name: 'Ascomycota' },
    class: { id: 'J2', name: 'Sordariomycetes' },
    family: { id: '8K4', name: 'Cordycipitaceae' },
    genus: { id: '62MKV', name: 'Cordyceps' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
