// Catalogue of Life classification for cudoniella-acicularis
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'cudoniella-acicularis',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '6BP4P',
  acceptedName: 'Cudoniella acicularis',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'SM', name: 'Ascomycota' },
    class: { id: 'DQ', name: 'Leotiomycetes' },
    order: { id: '3BV', name: 'Helotiales' },
    family: { id: '9YL6F', name: 'Tricladiaceae' },
    genus: { id: '3X9C', name: 'Cudoniella' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
