// Catalogue of Life classification for cyathus-striatus
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'cyathus-striatus',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '32RB9',
  acceptedName: 'Cyathus striatus',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'N8', name: 'Agaricales' },
    family: { id: '64F', name: 'Agaricaceae' },
    genus: { id: '3XS7', name: 'Cyathus' },
  },
  lastUpdated: '2026-10-10',
}

export default classification
