// Catalogue of Life classification for dacrymyces-chrysopermus
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'dacrymyces-chrysopermus',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '33TCJ',
  acceptedName: 'Dacrymyces chrysospermus',
  status: 'accepted',
  matchedBy: 'name-search',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '622DM', name: 'Dacrymycetes' },
    order: { id: '62237', name: 'Dacrymycetales' },
    family: { id: '8XZ', name: 'Dacrymycetaceae' },
    genus: { id: '3Z9H', name: 'Dacrymyces' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
