// Catalogue of Life classification for ganoderma-applanatum
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'ganoderma-applanatum',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '3F96J',
  acceptedName: 'Ganoderma applanatum',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: '3VM', name: 'Polyporales' },
    family: { id: '627LB', name: 'Polyporaceae' },
    genus: { id: '4M63', name: 'Ganoderma' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
