// Catalogue of Life classification for gomphidius-glutinosus
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'gomphidius-glutinosus',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '3GSMW',
  acceptedName: 'Gomphidius glutinosus',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'TS', name: 'Boletales' },
    family: { id: '623L6', name: 'Gomphidiaceae' },
    genus: { id: '4PVR', name: 'Gomphidius' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
