// Catalogue of Life classification for guepinia-helvelloides
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'guepinia-helvelloides',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '6L5F9',
  acceptedName: 'Guepinia helvelloides',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: '62295', name: 'Auriculariales' },
    genus: { id: '635Y3', name: 'Guepinia' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
