// Catalogue of Life classification for hericium-flagellum
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'hericium-flagellum',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '3KYXY',
  acceptedName: 'Hericium flagellum',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: '3ZF', name: 'Russulales' },
    family: { id: '62556', name: 'Hericiaceae' },
    genus: { id: '4VT4', name: 'Hericium' },
  },
  lastUpdated: '2026-10-10',
}

export default classification
