// Catalogue of Life classification for hydnellum-peckii
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'hydnellum-peckii',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '3MZF9',
  acceptedName: 'Hydnellum peckii',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: '47M', name: 'Thelephorales' },
    family: { id: '72V', name: 'Bankeraceae' },
    genus: { id: '4ZNP', name: 'Hydnellum' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
