// Catalogue of Life classification for hydnum-repandum
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'hydnum-repandum',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '3N275',
  acceptedName: 'Hydnum repandum',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'VD', name: 'Cantharellales' },
    family: { id: '9XBLB', name: 'Hydnaceae' },
    genus: { id: '4ZPC', name: 'Hydnum' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
