// Catalogue of Life classification for hygrocybe-acutoconica
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'hygrocybe-acutoconica',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '3NB37',
  acceptedName: 'Hygrocybe acutoconica',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'N8', name: 'Agaricales' },
    family: { id: 'B9D', name: 'Hygrophoraceae' },
    genus: { id: '4ZXK', name: 'Hygrocybe' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
