// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
export type * from '../types'

import { classification as albatrellus_ovinusClassification } from './albatrellus-ovinus'
import { classification as amanita_muscariaClassification } from './amanita-muscaria'
import { classification as amanita_pantherinaClassification } from './amanita-pantherina'
import { classification as amanita_phalloidesClassification } from './amanita-phalloides'
import { classification as armillaria_melleaClassification } from './armillaria-mellea'
import { classification as auricularia_auricula_judaeClassification } from './auricularia-auricula-judae'
import { classification as boletus_edulisClassification } from './boletus-edulis'
import { classification as butyriboletus_appendiculatusClassification } from './butyriboletus-appendiculatus'
import { classification as caloboletus_calopusClassification } from './caloboletus-calopus'
import { classification as caloboletus_radicansClassification } from './caloboletus-radicans'
import { classification as calocera_corneaClassification } from './calocera-cornea'
import { classification as cantharellus_cibariusClassification } from './cantharellus-cibarius'
import { classification as clathrus_archeriClassification } from './clathrus-archeri'
import { classification as clavulina_coralloidesClassification } from './clavulina-coralloides'
import { classification as clavulinopsis_helvolaClassification } from './clavulinopsis-helvola'
import { classification as collybia_phyllophilaClassification } from './collybia-phyllophila'
import { classification as collybiopsis_vaillantiiClassification } from './collybiopsis-vaillantii'
import { classification as coprinopsis_niveaClassification } from './coprinopsis-nivea'
import { classification as coprinopsis_pseudoniveaClassification } from './coprinopsis-pseudonivea'
import { classification as coprinus_comatusClassification } from './coprinus-comatus'
import { classification as cordyceps_militarisClassification } from './cordyceps-militaris'
import { classification as cortinarius_largusClassification } from './cortinarius-largus'
import { classification as craterellus_lutescensClassification } from './craterellus-lutescens'
import { classification as craterellus_tubaeformisClassification } from './craterellus-tubaeformis'
import { classification as cudoniella_acicularisClassification } from './cudoniella-acicularis'
import { classification as dacrymyces_chrysopermusClassification } from './dacrymyces-chrysopermus'
import { classification as diatrype_disciformisClassification } from './diatrype-disciformis'
import { classification as ganoderma_applanatumClassification } from './ganoderma-applanatum'
import { classification as gomphidius_glutinosusClassification } from './gomphidius-glutinosus'
import { classification as gomphus_clavatusClassification } from './gomphus-clavatus'
import { classification as guepinia_helvelloidesClassification } from './guepinia-helvelloides'
import { classification as hydnellum_peckiiClassification } from './hydnellum-peckii'
import { classification as hydnum_repandumClassification } from './hydnum-repandum'
import { classification as hygrocybe_acutoconicaClassification } from './hygrocybe-acutoconica'
import { classification as hygrocybe_cantharellusClassification } from './hygrocybe-cantharellus'
import { classification as infundibulicybe_gibbaClassification } from './infundibulicybe-gibba'
import { classification as inocybe_sindoniaClassification } from './inocybe-sindonia'
import { classification as laccaria_amethystinaClassification } from './laccaria-amethystina'
import { classification as lactarius_deterrimusClassification } from './lactarius-deterrimus'
import { classification as laetiporus_sulphureusClassification } from './laetiporus-sulphureus'
import { classification as lepiota_clypeolariaClassification } from './lepiota-clypeolaria'
import { classification as lycoperdon_perlatumClassification } from './lycoperdon-perlatum'
import { classification as macrolepiota_proceraClassification } from './macrolepiota-procera'
import { classification as mucidula_mucidaClassification } from './mucidula-mucida'
import { classification as mycena_epipterygiaClassification } from './mycena-epipterygia'
import { classification as mycena_viridimarginataClassification } from './mycena-viridimarginata'
import { classification as otidea_alutaceaClassification } from './otidea-alutacea'
import { classification as panellus_mitisClassification } from './panellus-mitis'
import { classification as podofomes_mollisClassification } from './podofomes-mollis'
import { classification as pseudohydnum_gelatinosumClassification } from './pseudohydnum-gelatinosum'
import { classification as ramaria_aureaClassification } from './ramaria-aurea'
import { classification as rickenella_fibulaClassification } from './rickenella-fibula'
import { classification as rubroboletus_rhodoxanthusClassification } from './rubroboletus-rhodoxanthus'
import { classification as rubroboletus_satanasClassification } from './rubroboletus-satanas'
import { classification as russula_delicaClassification } from './russula-delica'
import { classification as russula_langeiClassification } from './russula-langei'
import { classification as russula_parazureaClassification } from './russula-parazurea'
import { classification as sarcondon_imbricatusClassification } from './sarcondon-imbricatus'
import { classification as schizophyllum_communeClassification } from './schizophyllum-commune'
import { classification as suillellus_luridusClassification } from './suillellus-luridus'
import { classification as suillus_bovinusClassification } from './suillus-bovinus'
import { classification as thelephora_terrestrisClassification } from './thelephora-terrestris'
import { classification as tolypocladium_longisegmentatumClassification } from './tolypocladium-longisegmentatum'
import { classification as tolypocladium_ophioglossoidesClassification } from './tolypocladium-ophioglossoides'
import { classification as tricholoma_sulphureumClassification } from './tricholoma-sulphureum'

export const speciesClassification: Record<string, import('../types').ColClassification> = {
  'albatrellus-ovinus': albatrellus_ovinusClassification,
  'amanita-muscaria': amanita_muscariaClassification,
  'amanita-pantherina': amanita_pantherinaClassification,
  'amanita-phalloides': amanita_phalloidesClassification,
  'armillaria-mellea': armillaria_melleaClassification,
  'auricularia-auricula-judae': auricularia_auricula_judaeClassification,
  'boletus-edulis': boletus_edulisClassification,
  'butyriboletus-appendiculatus': butyriboletus_appendiculatusClassification,
  'caloboletus-calopus': caloboletus_calopusClassification,
  'caloboletus-radicans': caloboletus_radicansClassification,
  'calocera-cornea': calocera_corneaClassification,
  'cantharellus-cibarius': cantharellus_cibariusClassification,
  'clathrus-archeri': clathrus_archeriClassification,
  'clavulina-coralloides': clavulina_coralloidesClassification,
  'clavulinopsis-helvola': clavulinopsis_helvolaClassification,
  'collybia-phyllophila': collybia_phyllophilaClassification,
  'collybiopsis-vaillantii': collybiopsis_vaillantiiClassification,
  'coprinopsis-nivea': coprinopsis_niveaClassification,
  'coprinopsis-pseudonivea': coprinopsis_pseudoniveaClassification,
  'coprinus-comatus': coprinus_comatusClassification,
  'cordyceps-militaris': cordyceps_militarisClassification,
  'cortinarius-largus': cortinarius_largusClassification,
  'craterellus-lutescens': craterellus_lutescensClassification,
  'craterellus-tubaeformis': craterellus_tubaeformisClassification,
  'cudoniella-acicularis': cudoniella_acicularisClassification,
  'dacrymyces-chrysopermus': dacrymyces_chrysopermusClassification,
  'diatrype-disciformis': diatrype_disciformisClassification,
  'ganoderma-applanatum': ganoderma_applanatumClassification,
  'gomphidius-glutinosus': gomphidius_glutinosusClassification,
  'gomphus-clavatus': gomphus_clavatusClassification,
  'guepinia-helvelloides': guepinia_helvelloidesClassification,
  'hydnellum-peckii': hydnellum_peckiiClassification,
  'hydnum-repandum': hydnum_repandumClassification,
  'hygrocybe-acutoconica': hygrocybe_acutoconicaClassification,
  'hygrocybe-cantharellus': hygrocybe_cantharellusClassification,
  'infundibulicybe-gibba': infundibulicybe_gibbaClassification,
  'inocybe-sindonia': inocybe_sindoniaClassification,
  'laccaria-amethystina': laccaria_amethystinaClassification,
  'lactarius-deterrimus': lactarius_deterrimusClassification,
  'laetiporus-sulphureus': laetiporus_sulphureusClassification,
  'lepiota-clypeolaria': lepiota_clypeolariaClassification,
  'lycoperdon-perlatum': lycoperdon_perlatumClassification,
  'macrolepiota-procera': macrolepiota_proceraClassification,
  'mucidula-mucida': mucidula_mucidaClassification,
  'mycena-epipterygia': mycena_epipterygiaClassification,
  'mycena-viridimarginata': mycena_viridimarginataClassification,
  'otidea-alutacea': otidea_alutaceaClassification,
  'panellus-mitis': panellus_mitisClassification,
  'podofomes-mollis': podofomes_mollisClassification,
  'pseudohydnum-gelatinosum': pseudohydnum_gelatinosumClassification,
  'ramaria-aurea': ramaria_aureaClassification,
  'rickenella-fibula': rickenella_fibulaClassification,
  'rubroboletus-rhodoxanthus': rubroboletus_rhodoxanthusClassification,
  'rubroboletus-satanas': rubroboletus_satanasClassification,
  'russula-delica': russula_delicaClassification,
  'russula-langei': russula_langeiClassification,
  'russula-parazurea': russula_parazureaClassification,
  'sarcondon-imbricatus': sarcondon_imbricatusClassification,
  'schizophyllum-commune': schizophyllum_communeClassification,
  'suillellus-luridus': suillellus_luridusClassification,
  'suillus-bovinus': suillus_bovinusClassification,
  'thelephora-terrestris': thelephora_terrestrisClassification,
  'tolypocladium-longisegmentatum': tolypocladium_longisegmentatumClassification,
  'tolypocladium-ophioglossoides': tolypocladium_ophioglossoidesClassification,
  'tricholoma-sulphureum': tricholoma_sulphureumClassification,
}
