// Catalogue of Life classification for infundibulicybe-gibba
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'infundibulicybe-gibba',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '3PP8H',
  acceptedName: 'Infundibulicybe gibba',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'N8', name: 'Agaricales' },
    family: { id: '6272D', name: 'Tricholomataceae' },
    genus: { id: '54F3', name: 'Infundibulicybe' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
