// Catalogue of Life classification for inocybe-sindonia
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'inocybe-sindonia',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '3PRM3',
  acceptedName: 'Inocybe sindonia',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'N8', name: 'Agaricales' },
    family: { id: '624VH', name: 'Inocybaceae' },
    genus: { id: '54HL', name: 'Inocybe' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
