// Catalogue of Life classification for laetiporus-sulphureus
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'laetiporus-sulphureus',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '6NSSX',
  acceptedName: 'Laetiporus sulphureus',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: '3VM', name: 'Polyporales' },
    family: { id: '9YL2Q', name: 'Laetiporaceae' },
    genus: { id: '637P3', name: 'Laetiporus' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
