// Catalogue of Life classification for leccinum-scabrum
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'leccinum-scabrum',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '3STFC',
  acceptedName: 'Leccinum scabrum',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'TS', name: 'Boletales' },
    family: { id: '79Z', name: 'Boletaceae' },
    genus: { id: '5BP3', name: 'Leccinum' },
  },
  lastUpdated: '2026-10-10',
}

export default classification
