// Catalogue of Life classification for lepiota-clypeolaria
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'lepiota-clypeolaria',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '6PDNS',
  acceptedName: 'Lepiota clypeolaria',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'N8', name: 'Agaricales' },
    family: { id: '64F', name: 'Agaricaceae' },
    genus: { id: '5CMR', name: 'Lepiota' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
