// Catalogue of Life classification for lycoperdon-perlatum
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'lycoperdon-perlatum',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '3WLKC',
  acceptedName: 'Lycoperdon perlatum',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'N8', name: 'Agaricales' },
    family: { id: '9YL2V', name: 'Lycoperdaceae' },
    genus: { id: '5HL4', name: 'Lycoperdon' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
