// Catalogue of Life classification for mycena-viridimarginata
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'mycena-viridimarginata',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '6RQFF',
  acceptedName: 'Mycena viridimarginata',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'N8', name: 'Agaricales' },
    family: { id: 'D22', name: 'Mycenaceae' },
    genus: { id: '5W27', name: 'Mycena' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
