// Catalogue of Life classification for otidea-alutacea
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'otidea-alutacea',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '75CQ5',
  acceptedName: 'Otidea alutacea',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'SM', name: 'Ascomycota' },
    class: { id: 'G4', name: 'Pezizomycetes' },
    order: { id: '3SS', name: 'Pezizales' },
    family: { id: '9XCVG', name: 'Otideaceae' },
    genus: { id: '63HVT', name: 'Otidea' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
