// Catalogue of Life classification for panellus-mitis
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'panellus-mitis',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '4CC67',
  acceptedName: 'Panellus mitis',
  status: 'accepted',
  matchedBy: 'name-search',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'N8', name: 'Agaricales' },
    family: { id: 'D22', name: 'Mycenaceae' },
    genus: { id: '6D77', name: 'Panellus' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
