// Catalogue of Life classification for podofomes-mollis
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'podofomes-mollis',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: 'B2SZ9',
  acceptedName: 'Podofomes mollis',
  status: 'accepted',
  matchedBy: 'name-search',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: '3VM', name: 'Polyporales' },
    family: { id: '627LB', name: 'Polyporaceae' },
    genus: { id: '6TD5', name: 'Podofomes' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
