// Catalogue of Life classification for pseudohydnum-gelatinosum
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'pseudohydnum-gelatinosum',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '4NYCM',
  acceptedName: 'Pseudohydnum gelatinosum',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: '62295', name: 'Auriculariales' },
    family: { id: 'B7H', name: 'Hyaloriaceae' },
    genus: { id: '642ZF', name: 'Pseudohydnum' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
