// Catalogue of Life classification for ramaria-aurea
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'ramaria-aurea',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '4RBLM',
  acceptedName: 'Ramaria aurea',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: '62247', name: 'Gomphales' },
    family: { id: '623M5', name: 'Gomphaceae' },
    genus: { id: '76WS', name: 'Ramaria' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
