// Catalogue of Life classification for rickenella-fibula
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'rickenella-fibula',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '4T2CL',
  acceptedName: 'Rickenella fibula',
  status: 'accepted',
  matchedBy: 'name-search',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: '3D7', name: 'Hymenochaetales' },
    family: { id: '9YL56', name: 'Rickenellaceae' },
    genus: { id: '79XH', name: 'Rickenella' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
