// Catalogue of Life classification for russula-parazurea
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'russula-parazurea',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '4TSDF',
  acceptedName: 'Russula parazurea',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: '3ZF', name: 'Russulales' },
    family: { id: '62794', name: 'Russulaceae' },
    genus: { id: '7B7X', name: 'Russula' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
