// Catalogue of Life classification for sarcondon-imbricatus
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'sarcondon-imbricatus',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '6XLRR',
  acceptedName: 'Sarcodon imbricatus',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: '47M', name: 'Thelephorales' },
    family: { id: '72V', name: 'Bankeraceae' },
    genus: { id: '643Q6', name: 'Sarcodon' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
