// Catalogue of Life classification for schizophyllum-commune
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'schizophyllum-commune',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '79WX9',
  acceptedName: 'Schizophyllum commune',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'N8', name: 'Agaricales' },
    family: { id: '6278F', name: 'Schizophyllaceae' },
    genus: { id: '84TGP', name: 'Schizophyllum' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
