// Catalogue of Life classification for thelephora-terrestris
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'thelephora-terrestris',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '9YNW5',
  acceptedName: 'Thelephora terrestris',
  status: 'accepted',
  matchedBy: 'name-search',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: '47M', name: 'Thelephorales' },
    family: { id: 'H65', name: 'Thelephoraceae' },
    genus: { id: '7VJX', name: 'Thelephora' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
