// Catalogue of Life classification for tolypocladium-longisegmentatum
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'tolypocladium-longisegmentatum',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '57BV7',
  acceptedName: 'Tolypocladium longisegmentatum',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'SM', name: 'Ascomycota' },
    class: { id: 'J2', name: 'Sordariomycetes' },
    family: { id: 'DMR', name: 'Ophiocordycipitaceae' },
    genus: { id: '7XJJ', name: 'Tolypocladium' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
