// Catalogue of Life classification for tricholoma-sulphureum
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'tricholoma-sulphureum',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '7D3FT',
  acceptedName: 'Tricholoma sulphureum',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'BM', name: 'Basidiomycota' },
    class: { id: '7C', name: 'Agaricomycetes' },
    order: { id: 'N8', name: 'Agaricales' },
    family: { id: '6272D', name: 'Tricholomataceae' },
    genus: { id: '63VS5', name: 'Tricholoma' },
  },
  lastUpdated: '2026-10-09',
}

export default classification
