// Catalogue of Life classification for xylaria-hypoxylon
// Generated by scripts/update-species-col-classification.mjs -- do not edit by hand.
import type { ColClassification } from '../types'

export const classification: ColClassification = {
  slug: 'xylaria-hypoxylon',
  colDatasetKey: 316441,
  colRelease: 'COL26.9 XR',
  colId: '5CH3N',
  acceptedName: 'Xylaria hypoxylon',
  status: 'accepted',
  matchedBy: 'wikidata-p10585',
  classification: {
    phylum: { id: 'SM', name: 'Ascomycota' },
    class: { id: 'J2', name: 'Sordariomycetes' },
    order: { id: '622VK', name: 'Xylariales' },
    family: { id: 'HYK', name: 'Xylariaceae' },
    genus: { id: '63XB2', name: 'Xylaria' },
  },
  lastUpdated: '2026-10-10',
}

export default classification
