// Taxonomy topology for clathrus-archeri
// Generated by scripts/update-species-taxonomy.mjs -- do not edit by hand.
import type { TaxonomyData } from '../types'

export const taxonomy: TaxonomyData = {
  colDatasetKey: 1028,
  colUsageId: '112728',
  accepted: {
    scientificName: 'Clathrus archeri',
    authorship: '(Berk.) Dring',
    rank: 'species',
    usageId: '112728',
    status: 'accepted',
    parentUsageId: '19069',
    year: 1980,
  },
  basionym: {
    scientificName: 'Lysurus archeri',
    authorship: 'Berk.',
    rank: 'species',
    usageId: '196873',
    status: 'synonym',
    parentUsageId: '112728',
    year: 1859,
  },
  variations: [
    {
      scientificName: 'Clathrus archeri var. archeri',
      authorship: '(Berk.) Dring',
      rank: 'variety',
      usageId: '549388',
      status: 'accepted',
      parentUsageId: '112728',
      year: 1980,
    },
  ],
  fullHistory: [
    {
      scientificName: 'Lysurus archeri',
      authorship: 'Berk.',
      rank: 'species',
      usageId: '196873',
      status: 'synonym',
      parentUsageId: '112728',
      year: 1859,
    },
    {
      scientificName: 'Clathrus archeri',
      authorship: '(Berk.) Dring',
      rank: 'species',
      usageId: '112728',
      status: 'accepted',
      parentUsageId: '19069',
      year: 1980,
    },
    {
      scientificName: 'Clathrus archeri var. archeri',
      authorship: '(Berk.) Dring',
      rank: 'variety',
      usageId: '549388',
      status: 'accepted',
      parentUsageId: '112728',
      year: 1980,
    },
    {
      scientificName: 'Anthurus archeri',
      authorship: '(Berk.) E. Fisch.',
      rank: 'species',
      usageId: '226700',
      status: 'synonym',
      parentUsageId: '112728',
      year: 1886,
    },
    {
      scientificName: 'Aserophallus archeri',
      authorship: '(Berk.) Kuntze',
      rank: 'species',
      usageId: '292955',
      status: 'synonym',
      parentUsageId: '112728',
      year: 1891,
    },
    {
      scientificName: 'Pseudocolus archeri',
      authorship: '(Berk.) Lloyd',
      rank: 'species',
      usageId: '297404',
      status: 'synonym',
      parentUsageId: '112728',
      year: 1913,
    },
  ],
  lastUpdated: '2026-10-06',
}

export default taxonomy
