// Taxonomy topology for coprinopsis-nivea
// Generated by scripts/update-species-taxonomy.mjs -- do not edit by hand.
import type { TaxonomyData } from '../types'

export const taxonomy: TaxonomyData = {
  colDatasetKey: 1028,
  colUsageId: '474625',
  accepted: {
    scientificName: 'Coprinopsis nivea',
    authorship: '(Pers.) Redhead, Vilgalys & Moncalvo',
    rank: 'species',
    usageId: '474625',
    status: 'accepted',
    parentUsageId: '17366',
    year: 2001,
  },
  basionym: {
    scientificName: 'Agaricus niveus',
    authorship: 'Pers.',
    rank: 'species',
    usageId: '476775',
    status: 'synonym',
    parentUsageId: '474625',
    year: 1801,
  },
  variations: [],
  fullHistory: [
    {
      scientificName: 'Agaricus niveus',
      authorship: 'Pers.',
      rank: 'species',
      usageId: '476775',
      status: 'synonym',
      parentUsageId: '474625',
      year: 1801,
    },
    {
      scientificName: 'Coprinopsis nivea',
      authorship: '(Pers.) Redhead, Vilgalys & Moncalvo',
      rank: 'species',
      usageId: '474625',
      status: 'accepted',
      parentUsageId: '17366',
      year: 2001,
    },
    {
      scientificName: 'Coprinus niveus',
      authorship: '(Pers.) Fr.',
      rank: 'species',
      usageId: '232960',
      status: 'synonym',
      parentUsageId: '474625',
      year: 1838,
    },
    {
      scientificName: 'Coprinus latisporus',
      authorship: 'P.D. Orton',
      rank: 'species',
      usageId: '311715',
      status: 'synonym',
      parentUsageId: '474625',
      year: 1972,
    },
  ],
  lastUpdated: '2026-10-08',
}

export default taxonomy
