// Taxonomy topology for coprinopsis-pseudonivea
// Generated by scripts/update-species-taxonomy.mjs -- do not edit by hand.
import type { TaxonomyData } from '../types'

export const taxonomy: TaxonomyData = {
  colDatasetKey: 1028,
  colUsageId: '474121',
  accepted: {
    scientificName: 'Coprinopsis pseudonivea',
    authorship: '(Bender & Uljé) Redhead, Vilgalys & Moncalvo',
    rank: 'species',
    usageId: '474121',
    status: 'accepted',
    parentUsageId: '17366',
    year: 2001,
  },
  basionym: {
    scientificName: 'Coprinus pseudoniveus',
    authorship: 'Bender & Uljé',
    rank: 'species',
    usageId: '361018',
    status: 'synonym',
    parentUsageId: '474121',
    year: 1993,
  },
  variations: [
    {
      scientificName: 'Coprinopsis pseudonivea var. pseudonivea',
      authorship: '(Bender & Uljé) Redhead, Vilgalys & Moncalvo',
      rank: 'variety',
      usageId: '587885',
      status: 'accepted',
      parentUsageId: '474121',
      year: 2001,
    },
  ],
  fullHistory: [
    {
      scientificName: 'Coprinus pseudoniveus',
      authorship: 'Bender & Uljé',
      rank: 'species',
      usageId: '361018',
      status: 'synonym',
      parentUsageId: '474121',
      year: 1993,
    },
    {
      scientificName: 'Coprinopsis pseudonivea',
      authorship: '(Bender & Uljé) Redhead, Vilgalys & Moncalvo',
      rank: 'species',
      usageId: '474121',
      status: 'accepted',
      parentUsageId: '17366',
      year: 2001,
    },
    {
      scientificName: 'Coprinopsis pseudonivea var. pseudonivea',
      authorship: '(Bender & Uljé) Redhead, Vilgalys & Moncalvo',
      rank: 'variety',
      usageId: '587885',
      status: 'accepted',
      parentUsageId: '474121',
      year: 2001,
    },
    {
      scientificName: 'Coprinopsis pseudonivea var. tenuicystidiata',
      authorship: '(Chalange) Valade',
      rank: 'variety',
      usageId: '550628',
      status: 'synonym',
      parentUsageId: '474121',
      year: 2014,
    },
    {
      scientificName: 'Coprinus pseudoniveus var. tenuicystidiatus',
      authorship: 'Chalange',
      rank: 'variety',
      usageId: '374504',
      status: 'synonym',
      parentUsageId: '474121',
      year: 2002,
    },
  ],
  lastUpdated: '2026-10-08',
}

export default taxonomy
