// Taxonomy topology for cortinarius-largus
// Generated by scripts/update-species-taxonomy.mjs -- do not edit by hand.
import type { TaxonomyData } from '../types'

export const taxonomy: TaxonomyData = {
  colDatasetKey: 1028,
  colUsageId: '224983',
  accepted: {
    scientificName: 'Cortinarius largus',
    authorship: 'Fr.',
    rank: 'species',
    usageId: '224983',
    status: 'accepted',
    parentUsageId: '17391',
    year: 1838,
  },
  basionym: null,
  variations: [
    {
      scientificName: 'Cortinarius largus var. largus',
      authorship: 'Fr.',
      rank: 'variety',
      usageId: '449680',
      status: 'accepted',
      parentUsageId: '224983',
      year: 1838,
    },
  ],
  fullHistory: [
    {
      scientificName: 'Cortinarius largus',
      authorship: 'Fr.',
      rank: 'species',
      usageId: '224983',
      status: 'accepted',
      parentUsageId: '17391',
      year: 1838,
    },
    {
      scientificName: 'Cortinarius largus var. largus',
      authorship: 'Fr.',
      rank: 'variety',
      usageId: '449680',
      status: 'accepted',
      parentUsageId: '224983',
      year: 1838,
    },
    {
      scientificName: 'Gomphos largus',
      authorship: '(Fr.) Kuntze',
      rank: 'species',
      usageId: '629194',
      status: 'synonym',
      parentUsageId: '224983',
      year: 1891,
    },
    {
      scientificName: 'Phlegmacium largum',
      authorship: '(Fr.) Wünsche',
      rank: 'species',
      usageId: '517964',
      status: 'synonym',
      parentUsageId: '224983',
      year: 1877,
    },
    {
      scientificName: 'Cortinarius largus var. crucius',
      authorship: 'Bidaud, Moënne-Locc. & Reumaux',
      rank: 'variety',
      usageId: '446291',
      status: 'synonym',
      parentUsageId: '224983',
      year: 1996,
    },
    {
      scientificName: 'Cortinarius largus var. rubrozonatus',
      authorship: 'Bidaud, Moënne-Locc. & Reumaux',
      rank: 'variety',
      usageId: '446292',
      status: 'synonym',
      parentUsageId: '224983',
      year: 1996,
    },
    {
      scientificName: 'Cortinarius lividoviolaceus',
      authorship: 'Rob. Henry',
      rank: 'species',
      usageId: '132911',
      status: 'synonym',
      parentUsageId: '224983',
      year: 1987,
    },
  ],
  lastUpdated: '2026-10-08',
}

export default taxonomy
