// Taxonomy topology for cyathus-striatus
// Generated by scripts/update-species-taxonomy.mjs -- do not edit by hand.
import type { TaxonomyData } from '../types'

export const taxonomy: TaxonomyData = {
  colDatasetKey: 1028,
  colUsageId: '211223',
  accepted: {
    scientificName: 'Cyathus striatus',
    authorship: 'Willd.',
    rank: 'species',
    usageId: '211223',
    status: 'accepted',
    parentUsageId: '19085',
    year: 1787,
  },
  basionym: null,
  variations: [
    {
      scientificName: 'Cyathus striatus var. striatus',
      authorship: 'Willd.',
      rank: 'variety',
      usageId: '419932',
      status: 'accepted',
      parentUsageId: '211223',
      year: 1787,
    },
  ],
  fullHistory: [
    {
      scientificName: 'Cyathus striatus',
      authorship: 'Willd.',
      rank: 'species',
      usageId: '211223',
      status: 'accepted',
      parentUsageId: '19085',
      year: 1787,
    },
    {
      scientificName: 'Cyathus striatus var. striatus',
      authorship: 'Willd.',
      rank: 'variety',
      usageId: '419932',
      status: 'accepted',
      parentUsageId: '211223',
      year: 1787,
    },
    {
      scientificName: 'Cyathella striata',
      authorship: '(Willd.) Brot.',
      rank: 'species',
      usageId: '492528',
      status: 'synonym',
      parentUsageId: '211223',
      year: 1804,
    },
    {
      scientificName: 'Nidularia striata',
      authorship: '(Willd.) With.',
      rank: 'species',
      usageId: '244769',
      status: 'synonym',
      parentUsageId: '211223',
      year: 1792,
    },
    {
      scientificName: 'Nidularia striata var. pusilla',
      authorship: 'Berk.',
      rank: 'variety',
      usageId: '139403',
      status: 'synonym',
      parentUsageId: '211223',
      year: 1839,
    },
    {
      scientificName: 'Peziza striata',
      authorship: 'Huds.',
      rank: 'species',
      usageId: '227483',
      status: 'synonym',
      parentUsageId: '211223',
      year: 1778,
    },
  ],
  lastUpdated: '2026-10-10',
}

export default taxonomy
