// Taxonomy topology for dacrymyces-chrysopermus
// Generated by scripts/update-species-taxonomy.mjs -- do not edit by hand.
import type { TaxonomyData } from '../types'

export const taxonomy: TaxonomyData = {
  colDatasetKey: 1028,
  colUsageId: '141916',
  accepted: {
    scientificName: 'Dacrymyces chrysospermus',
    authorship: 'Berk. & M.A. Curtis',
    rank: 'species',
    usageId: '141916',
    status: 'accepted',
    parentUsageId: '17455',
    year: 1873,
  },
  basionym: null,
  variations: [],
  fullHistory: [
    {
      scientificName: 'Dacrymyces chrysospermus',
      authorship: 'Berk. & M.A. Curtis',
      rank: 'species',
      usageId: '141916',
      status: 'accepted',
      parentUsageId: '17455',
      year: 1873,
    },
    {
      scientificName: 'Dacrymyces palmatus',
      authorship: 'Bres.',
      rank: 'species',
      usageId: '293870',
      status: 'synonym',
      parentUsageId: '141916',
      year: 1904,
    },
    {
      scientificName: 'Dacrymyces palmatus var. minor',
      authorship: 'B. Liu & L. Fan',
      rank: 'variety',
      usageId: '126184',
      status: 'synonym',
      parentUsageId: '141916',
      year: 1990,
    },
    {
      scientificName: 'Dacryopsis palmata',
      authorship: 'Lloyd',
      rank: 'species',
      usageId: '273373',
      status: 'synonym',
      parentUsageId: '141916',
      year: 1920,
    },
    {
      scientificName: 'Tremella palmata',
      authorship: 'Schwein.',
      rank: 'species',
      usageId: '159571',
      status: 'synonym',
      parentUsageId: '141916',
      year: 1832,
    },
  ],
  lastUpdated: '2026-10-08',
}

export default taxonomy
