// Taxonomy topology for hydnellum-peckii
// Generated by scripts/update-species-taxonomy.mjs -- do not edit by hand.
import type { TaxonomyData } from '../types'

export const taxonomy: TaxonomyData = {
  colDatasetKey: 1028,
  colUsageId: '414442',
  accepted: {
    scientificName: 'Hydnellum peckii',
    authorship: 'Banker',
    rank: 'species',
    usageId: '414442',
    status: 'accepted',
    parentUsageId: '17781',
    year: 1912,
  },
  basionym: null,
  variations: [],
  fullHistory: [
    {
      scientificName: 'Hydnellum peckii',
      authorship: 'Banker',
      rank: 'species',
      usageId: '414442',
      status: 'accepted',
      parentUsageId: '17781',
      year: 1912,
    },
    {
      scientificName: 'Calodon peckii',
      authorship: '(Banker) Snell & E.A. Dick',
      rank: 'species',
      usageId: '293929',
      status: 'synonym',
      parentUsageId: '414442',
      year: 1956,
    },
    {
      scientificName: 'Hydnum peckii',
      authorship: '(Banker) Sacc. & Trotter',
      rank: 'species',
      usageId: '229916',
      status: 'synonym',
      parentUsageId: '414442',
      year: 1925,
    },
    {
      scientificName: 'Calodon diabolus',
      authorship: '(Banker) Snell',
      rank: 'species',
      usageId: '293928',
      status: 'synonym',
      parentUsageId: '414442',
      year: 1956,
    },
    {
      scientificName: 'Hydnellum diabolus',
      authorship: 'Banker',
      rank: 'species',
      usageId: '438447',
      status: 'synonym',
      parentUsageId: '414442',
      year: 1913,
    },
    {
      scientificName: 'Hydnum diabolus',
      authorship: '(Banker) Sacc. & Trotter',
      rank: 'species',
      usageId: '298557',
      status: 'synonym',
      parentUsageId: '414442',
      year: 1925,
    },
  ],
  lastUpdated: '2026-10-06',
}

export default taxonomy
