// Taxonomy topology for lactarius-deterrimus
// Generated by scripts/update-species-taxonomy.mjs -- do not edit by hand.
import type { TaxonomyData } from '../types'

export const taxonomy: TaxonomyData = {
  colDatasetKey: 1028,
  colUsageId: '332881',
  accepted: {
    scientificName: 'Lactarius deterrimus',
    authorship: 'Gröger',
    rank: 'species',
    usageId: '332881',
    status: 'accepted',
    parentUsageId: '17895',
    year: 1968,
  },
  basionym: null,
  variations: [],
  fullHistory: [
    {
      scientificName: 'Lactarius deterrimus',
      authorship: 'Gröger',
      rank: 'species',
      usageId: '332881',
      status: 'accepted',
      parentUsageId: '17895',
      year: 1968,
    },
    {
      scientificName: 'Lactarius deliciosus var. deterrimus',
      authorship: '(Gröger) Hesler & A.H. Sm.',
      rank: 'variety',
      usageId: '117765',
      status: 'synonym',
      parentUsageId: '332881',
      year: 1979,
    },
  ],
  lastUpdated: '2026-10-06',
}

export default taxonomy
