// Taxonomy topology for mycena-viridimarginata
// Generated by scripts/update-species-taxonomy.mjs -- do not edit by hand.
import type { TaxonomyData } from '../types'

export const taxonomy: TaxonomyData = {
  colDatasetKey: 1028,
  colUsageId: '235997',
  accepted: {
    scientificName: 'Mycena viridimarginata',
    authorship: 'P. Karst.',
    rank: 'species',
    usageId: '235997',
    status: 'accepted',
    parentUsageId: '18084',
    year: 1892,
  },
  basionym: null,
  variations: [
    {
      scientificName: 'Mycena viridimarginata var. viridimarginata',
      authorship: 'P. Karst.',
      rank: 'variety',
      usageId: '426455',
      status: 'accepted',
      parentUsageId: '235997',
      year: 1892,
    },
  ],
  fullHistory: [
    {
      scientificName: 'Mycena viridimarginata',
      authorship: 'P. Karst.',
      rank: 'species',
      usageId: '235997',
      status: 'accepted',
      parentUsageId: '18084',
      year: 1892,
    },
    {
      scientificName: 'Mycena viridimarginata var. viridimarginata',
      authorship: 'P. Karst.',
      rank: 'variety',
      usageId: '426455',
      status: 'accepted',
      parentUsageId: '235997',
      year: 1892,
    },
  ],
  lastUpdated: '2026-10-08',
}

export default taxonomy
