// Taxonomy topology for russula-langei
// Generated by scripts/update-species-taxonomy.mjs -- do not edit by hand.
import type { TaxonomyData } from '../types'

export const taxonomy: TaxonomyData = {
  colDatasetKey: 1028,
  colUsageId: '322933',
  accepted: {
    scientificName: 'Russula langei',
    authorship: 'Bon',
    rank: 'species',
    usageId: '322933',
    status: 'accepted',
    parentUsageId: '18493',
    year: 1970,
  },
  basionym: null,
  variations: [
    {
      scientificName: 'Russula langei var. langei',
      authorship: 'Bon',
      rank: 'variety',
      usageId: '313060',
      status: 'accepted',
      parentUsageId: '322933',
      year: 1970,
    },
  ],
  fullHistory: [
    {
      scientificName: 'Russula langei',
      authorship: 'Bon',
      rank: 'species',
      usageId: '322933',
      status: 'accepted',
      parentUsageId: '18493',
      year: 1970,
    },
    {
      scientificName: 'Russula langei var. langei',
      authorship: 'Bon',
      rank: 'variety',
      usageId: '313060',
      status: 'accepted',
      parentUsageId: '322933',
      year: 1970,
    },
    {
      scientificName: 'Russula langei var. cutefractoides',
      authorship: 'Bon & Ramm',
      rank: 'variety',
      usageId: '370533',
      status: 'synonym',
      parentUsageId: '322933',
      year: 2004,
    },
  ],
  lastUpdated: '2026-10-08',
}

export default taxonomy
